salemove/android-sdk-widgets

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/layout/main_fragment.xml

Integrators example app navigation to the chat view removed and button hidden
Causing too much confusion as dev is testing there instead of widgets chat activity

MUIC-362: [Android] Disable "Start chat in integrator app" button

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/FilePreviewActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/helper/FileHelper.java
widgetssdk/src/main/java/com/glia/widgets/screensharing/ScreenSharingController.java

Using printStackTrace in the release application might introduce a potential security risk. It should be removed from SDK.
https://salemove.atlassian.net/browse/MOB-875
https://salemove.atlassian.net/browse/SSD-19423

Avoid using printStackTrace in SDK

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java

[MUIC-615](https://glia.atlassian.net/browse/MUIC-615)
Fixes issue in https://github.com/salemove/android-sdk-widgets/pull/139/files#diff-9a3bcdbdd5b69de704f92d16dffc971d6bab25e811f3bcdec39bc2e465a53a20R645

Fix visitor typing indication doesn't disappear after the message is sent

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/themes.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.java
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/themes.xml

https://glia.atlassian.net/browse/MUIC-623
Buildtime attribute fix for whitelabel - to test it don't forget to
DISABLE runtime override
- as agreed on spring:
```
false = enabled 
true = disabled 
```

MUIC-623: [Android] - Whitelabel customisation

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/themes.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/SingleChoiceCardView.java
widgetssdk/src/main/java/com/glia/widgets/view/configuration/TextConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/view/textview/BaseConfigurableTextView.java
widgetssdk/src/main/java/com/glia/widgets/view/textview/ChoiceCardContentTextView.java
widgetssdk/src/main/res/layout/single_choice_card_view.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/styles.xml

https://glia.atlassian.net/browse/MUIC-625
For Runtime customisation add this `TextConfiguration` to `UiThemeBuilder`:
```
private static TextConfiguration getChoiceCardContentTextConfiguration(Context context) {
return TextConfiguration.builder()
.textSize(16f)      // in sp
.fontFamily(R.font.tangerine)
.textColor(ContextCompat.getColorStateList(context, R.color.color_dark_cyan))
.build();
}
```
For Buildtime customisation define or pass a style to `ThemeOverlay.GliaAndroidSDKWidgetsExample.Chat` like this:
```
<item name="choiceCardContentTextStyle">
@style/Application.GliaAndroidSdkWidgetsExample.ChoiceCard.ContentText
</item>
```
style example:
```
<style name="Application.GliaAndroidSdkWidgetsExample.ChoiceCard.ContentText" …
```

MUIC-625: [Android] - Customisation for Choice Card Content TextView

---

widgetssdk/build.gradle

Change configuration to make Glia Core SDK the end project dependency

SDK dependency

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallState.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java

Fixed bug where when an operator upgrades to two-way video, a visitor sees an Audio call screen title
Used the requested media type to set the title on the call screen.
[MOB-1037](https://glia.atlassian.net/browse/MOB-1037)

Fix incorrect "Audio call" title during connection with operator

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorMessageViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/view/SingleChoiceCardView.java
widgetssdk/src/main/res/layout/single_choice_card_view.xml
widgetssdk/src/main/res/values/dimens.xml

https://glia.atlassian.net/browse/MUIC-634
- Improved the ui to match the design and iOS
- Choice card image height is fixed to 200px just like on the iOS. This solves the issue with card height jumping after image loading finished.
- Broke down a larger method to improve the readability.
Before:
After:

MUIC-634 Fix choice card ui issues

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/OperatorImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/VisitorImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/res/layout/chat_attachment_operator_image_layout.xml

https://glia.atlassian.net/browse/MUIC-593
- Changed the operator message and attachments order as per the hub. Message is shown first and then attachments/images.

Fix operator avatar not removed issue

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java

https://glia.atlassian.net/browse/MUIC-647
From the docs: https://developer.android.com/reference/androidx/core/app/ActivityCompat.OnRequestPermissionsResultCallback#onRequestPermissionsResult(int,java.lang.String[],int[])
>Note: It is possible that the permissions request interaction with the user is interrupted. In this case you will receive empty permissions and results arrays which should be treated as a cancellation.

MUIC-647 Fix permission request related crash

---

widgetssdk/src/main/java/com/glia/widgets/core/notification/NotificationFactory.java

https://glia.atlassian.net/browse/MUIC-682
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

MUIC-682 Fix screensharing notification crash

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatViewCallback.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java

https://glia.atlassian.net/browse/MUIC-665
https://glia.atlassian.net/browse/MUIC-685
I changed the two-way data flow in the editText to one way only. Two-way created many issues with the editText, it is not suggested and it was used only for clearing the editText. Clearing happens now via the viewCallback.

Fix "visitor is typing" not cleared bug and editText cursor jumping bug

---

widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.java

https://glia.atlassian.net/browse/MUIC-702
UseOverlay and ScreenSharingMode extras were missing when navigating from chat head to chat activity and thus default values were used.

Add missing intent extras when navigating from chat head to ChatActivity

---

app/src/main/java/com/glia/exampleapp/ChatFragment.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

https://glia.atlassian.net/browse/MUIC-710
We need to keep track of the currently active (topmost) view. This can be either ChatView
or CallView. CallView has translucent theme and this changes the usual lifecycle of an activity.
When the translucent CallActivity is on top of the ChatActivity and config change happens (e.g screen rotation)
then ChatActivity onResume and onPause are called right after CallActivity's onResume. Current
solution ignores such onResume calls because another activity is already in resumed state.

Fix chat head visibility issue on screen rotation

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/core/chathead/ChatHeadService.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorMediaRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/ViewHelpers.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoContract.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoController.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoCoordinatorLayout.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoView.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadLayout.java
widgetssdk/src/main/res/layout-land/call_view.xml
widgetssdk/src/main/res/layout/call_view.xml
widgetssdk/src/main/res/layout/visitor_video_floating_view.xml
widgetssdk/src/main/res/layout/visitor_video_layout_view.xml
widgetssdk/src/main/res/values/dimens.xml

https://glia.atlassian.net/browse/MUIC-648
**Additional info**
There is some sort of visual bug when you hover visitor video over operator video edges that are over operator video are displayed sharp, so edges are now set to sharp to get rid of the issue. (Needs core-SDK team input - or research)
Also sometimes when operator video is created after visitor video (post methods order), visitor video is positioned behind the operator video. Not sure why (might need core-SDK team input on this) - tried to add z-vector and elevation but it still happens. View hierarchy seems to be ignored? (check last image)

Visitor Video Popup

---

widgetssdk/src/main/res/layout/operator_status_view.xml

https://glia.atlassian.net/browse/MUIC-758
On hold indicator needs padding aswell. Shapeable Imageview content padding is buggy at the moment so this is temporary solution.

Fix on hold indicator size

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyContract.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyController.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.java

Fix: hide keyboard if the visitor interacts with other elements after the text field
[MUIC-764](https://glia.atlassian.net/browse/MUIC-764)

Fix: hide keyboard on survey screen

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.java

Possible fix for the bug. It hides a soft keyboard on orientation changed.
[MUIC-766](https://glia.atlassian.net/browse/MUIC-766)

Fix keyboard overlay

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyAdapter.java
widgetssdk/src/main/java/com/glia/widgets/view/configuration/survey/InputQuestionConfiguration.java

https://glia.atlassian.net/browse/MOB-1281
Agreed on the following expected behavior:
On Android in Dark Mode the input box will stay white with dark text. And there will be an ability for integrators to set custom color for input box background and text.

Apply custom color for survey input box background and text

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java

Fix: Not show the "End engagement" dialog if the engagement ends by a Visitor
[MOB-1284](https://glia.atlassian.net/browse/MOB-1284)
[MUIC-768](https://glia.atlassian.net/browse/MUIC-768)

Fix end engagement dialog

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/chat/helper/FileHelper.java

https://glia.atlassian.net/browse/MUIC-767
* fix image loading crash when loading was interrupted
* add global RxErrorHandler to handle undeliverable exceptions that otherwise cause app crashes.

Add global RxErrorHandler to handle undeliverable exceptions.

---

widgetssdk/src/main/java/com/glia/widgets/helper/ResourceProvider.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.java
widgetssdk/src/main/java/com/glia/widgets/view/configuration/survey/SurveyStyle.java

https://glia.atlassian.net/browse/SSD-27140
Currently, Survey style defaults are overriding two XML attributes: button background and button text color.
This PR changes this to use defaults from XML styles.

Use default attributes from XML for Survey buttons

---

widgetssdk/src/main/java/com/glia/widgets/helper/ResourceProvider.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.java
widgetssdk/src/main/java/com/glia/widgets/view/configuration/survey/SurveyStyle.java

https://glia.atlassian.net/browse/SSD-27140
Currently, Survey style defaults are overriding two XML attributes: button background and button text color.
This PR changes this to use defaults from XML styles.

Use default attributes from XML for Survey buttons (develop)

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallIntentBuilder.java
widgetssdk/src/main/java/com/glia/widgets/call/CallIntentReader.java
widgetssdk/src/main/java/com/glia/widgets/call/Configuration.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.java

https://glia.atlassian.net/browse/MUIC-318
Part of MUIC-318 implementation - created a builder class for Call Activity in order to hold Activity configuration and ease up serialisation process
Note for future implementation: I propose to remove WidgetsConfiguration from Activity Initialisation and receive it via some Provider instead. It will require deprecation notice and a lot of rework on how things are tied up. But the configuration will be held and will not be lost in case activity is started from service (or deeplink)
(with current implementation it will be matter of moving sdkConfiguration out of the builder and activity configuration to proper widgets configuration holder class :) )

Call Activity Configuration Impl

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatRecyclerView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java

Fix: stop auto-scrolling if chat is not in the bottom.

Fix chat recyclerview autoscroll

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/core/survey/GliaSurveyRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/survey/domain/GliaSurveyUseCase.java

Navigate to survey on resuming CallActivity if engagement ended.
This is alternative solution of https://github.com/salemove/android-sdk-widgets/pull/317 .
[MOB-1383](https://glia.atlassian.net/browse/MOB-1383)
[MUIC-838](https://glia.atlassian.net/browse/MUIC-838)

Fix: show survey on resume

---

widgetssdk/src/main/res/values/strings.xml

Fix the typo in the word "screen"
`<string name="glia_notification_screen_sharing_title">You are currently sharing your screen</string>`

Fix the typo in the word "screen"

---

build.gradle
widgetssdk/src/main/res/layout/chat_head_view.xml
widgetssdk/src/main/res/layout/chat_view.xml

MOB-1468
https://glia.atlassian.net/browse/MOB-1468
`lottie-scale` property is completely removed from new versions and there is no equivalent, they recommend combining size with ImageView's `ScaleType` 

Update Lottie dependency

---

widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogManager.java

Fix: show current dialog state on add callback to the DialogController

Fix: show Overlay permissions Dialog

---

widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogManager.java
widgetssdk/src/test/java/com/glia/widgets/core/dialog/DialogManagerTest.java

Added possibility to show dialogs one by one.
Used to show the No More Operators Dialog (returned to previous logic).

Fix: show dialogs by list

---

bitrise.yml

In order to ensure that the release process of the widgets is done
with a working version of the SDK, unit tests for both SDK and testing
app have been added to the `publish_to_nexus` workflow, which is the
one in charge of releasing the widgets to Maven Central.
MOB-1510

Add unit testing to release process

---

.github/workflows/deployment.yml
bitrise.yml

Instead of going to GitHub and manually generating a release, the deployment workflow will be in charge of generating the release, the tag, and the changelog. The only thing needed from our side is to send it the NEW_VERSION environment variable. To make this even easier, a new GitHub Action is created to do exactly that. Just send the version through GitHub’s interface, and it will do everything. The tag trigger is not available anymore.
Apart from that, the increment_project_version is updated so that it doesn’t have unnecessary steps. This time it will succeed always.
I don't know why always Bitrise changes its formatting. The changes to the bitrise.yml are here https://github.com/salemove/android-sdk-widgets/compare/MOB-1589?expand=1#diff-61d1ee831cb1df242161a7d23171914a1d5d628c7659b52 …

Update Bitrise deployment workflow

---

.github/workflows/post-release.yml
bitrise.yml

Because our android-sdk-widgets release depends on Maven Central, then we cannot increase the android-sdk-widgets dependency in android_cortex_banking_app until Maven Central reflects our release. This step thus needs to be done manually. The tag to be sent is the same as the released version.
I also had to re-add the spaces that were deleted in a previous PR because this absolutely screws up the formatting inside Bitrise and makes all steps with scripts to fail because commands show up overlapped.
MOB-1589

Add post release workflow

---

scripts/version-updater.gradle

In order to make it easier to update the project version from Bitrise, the version updater, instead of receiving the specific version name and code, receives a `type` parameter. This way, we can make a GitHub Action to which you can send `patch`, `minor`, or `major`.

Allow version updater to receive update type

---

version.properties

Done manually because Bitrise is still not using the work done to support patch updates yet.

Increment project version to 1.9.1

---

.github/workflows/increment-project-version.yml
bitrise.yml

Sometimes we will need to increment the minor version. However, right now the `_increment_project_version` will increment with type set as `patch` by default. This workflow lets you choose on a dropdown what type you want to use for the version increment. Bitrise then executes an authenticated version of incrementing project version. This is needed because _increment_project_version on its own cannot work, as it needs the SSH key.

Add GitHub Action for manual version increment

---

widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/view/configuration/ChatHeadConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/view/configuration/TextConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ViewExstensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/parse/Deserializers.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/parse/RemoteConfigurationParser.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/base/ThemeBaseMappers.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/base/ThemeColor.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/base/ThemeLayer.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/base/ThemeText.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyThemeMappers.kt

For now, I've only created mappers for the base config classes. I don't understand the parts of the old and new themes clearly, so I decided to start implementing screen-by-screen and add mappers according to what I find on specific screens.
https://glia.atlassian.net/browse/MOB-1618
- Add mappers
- Add ViewBinding to project
- Add extension functions to apply the new theme to views
MOB-1618

Create Mappers to map old UiTheme to new GliaTheme

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/core/queue/GliaQueueRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/queue/domain/QueueTicketStateChangeToUnstaffedUseCase.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/test/java/com/glia/widgets/core/queue/GliaQueueRepositoryTest.java

**Description:**
This PR is very similar to https://github.com/salemove/android-sdk-widgets/pull/395 but uses subscription to a specific QueueTicket state changes rather than a subscription to all Queue Tickets updates.
So the difference is in:
- GliaQueueRepository.java
- QueueTicketStateChangeToUnstaffedUseCase.java
- GliaQueueRepositoryTest.java
- GliaCore.java
- GliaCoreImpl.java
⚠️ Bitrise will fail the build because Core SDK changes are missing now
https://glia.atlassian.net/browse/MOB-1592
**Screen recording:**
https://user-images.githubusercontent.com/57521863/202743755-9e33e708-a346-4a0c-a95a-bddf689d336a.mov

Show popup message if queue ticket state changes to 'unstaffed'

---

widgetssdk/src/main/java/com/glia/widgets/call/CallButtonLabelView.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallState.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/call/ThemedStateText.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/call/CallRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/MessageBalloonRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/MessageBalloonTheme.kt
widgetssdk/src/main/res/layout-land/call_view.xml
widgetssdk/src/main/res/layout/call_view.xml

- Implement Remote `Configuration` for remaining widgets on `Call` screen
- Update `MessageBalloonRemoteConfig.kt`
- Add Custom view to ease theme management for different states
- Add `CallState.isOnlyTimeChanged` parameter to avoid entire view re-rendering on timer update
MOB-1649
https://glia.atlassian.net/browse/MOB-1649

Call Screen. Implement Remote configuration for remaining widgets

---

widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ViewExstensions.kt

[MOB-1663](https://glia.atlassian.net/browse/MOB-1663)
Close icon in Alert Dialog view is currently invisible. This PR should fix the issue.
Expected:
Actual:

Do not replace default color with null for Alert Dialog close icon

---

widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/CustomCardItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/LinkedChatItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/OperatorAttachmentItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/OperatorChatItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/OperatorMessageItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/VisitorAttachmentItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/VisitorMessageItem.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/GliaOnEngagementEndUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/GliaOnEngagementUseCase.java

https://glia.atlassian.net/browse/MUIC-1612
These changes depend on still unreleased changes in Core SDK. Before merging need to wait for the Core SDK release.
Core SDK has breaking changes related to local chat message storage. There are slight changes to the behavior of 2 Core SDK methods:
- Chat.sendResponse(...)
- Glia.getChatHistory(...)

Resolve breaking changes related to Core SDK update

---

widgetssdk/src/main/java/com/glia/widgets/core/queue/GliaQueueRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversations.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/FetchChatTranscriptUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/IsMessageCenterAvailableUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/MarkMessagesReadUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/SendSecureMessageUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterContract.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/res/layout/message_center_view.xml
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/IsMessageCenterAvailableUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/messagecenter/MessageCenterControllerTest.kt

[MOB-1725](https://glia.atlassian.net/browse/MOB-1725)
Add unavailable status to secure conversations welcome screen:
- сheck if secure conversations feature is available
- hide views if unavailable
- show alert if unavailable
https://user-images.githubusercontent.com/57521863/210087931-e9094a0e-ea3c-4f63-9fcf-9f3cf5613a23.mov
[MOB-1725]: https://glia.atlassian.net/browse/MOB-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add unavailable status to secure conversations welcome screen

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/res/layout/message_center_view.xml

Added scroll view to the Welcome to Message Center screen. It needs to handle the keyboard appearance according to the design.
MOB-1679
[device-2023-01-04-202025.webm](https://user-images.githubusercontent.com/79906470/210623798-0013bc03-55f3-4473-b3b3-cbf8dc06083c.webm)
[MOB-1679]: https://glia.atlassian.net/browse/MOB-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle when keyboard appears

---

catalog-info.yaml

The catalog-info.yaml is intentionally very small. This is just to get the
basic integration working with Backstage. The teams can add additional
information like the project description and other annotations.
This was created using an automated script.
DEVEXP-106

Add catalog-info.yaml for integration with Backstage

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java

After migration to Kotlin, the support for the operator picture being nullable was lost in one place. Because of that in case of the operator not having an image (as in acceptance tests) the chat state does not get updated on the engagement start

Fix nullable operator image issue

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.java
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsTest.java

[MOB-1822](https://glia.atlassian.net/browse/MOB-1822)
1. Start listening for engagement requests once SDK is initialized
2. Auto-accept incoming Call Visualizer engagement request
3. Listen for new engagement without effecting the integrator app (there is no specific handling yet within this ticket, just listen)
There is an [open question](https://salemove.slack.com/archives/C04BTHLDL9Y/p1674721827031499) regarding visitor context assets related to this ticket.
[MOB-1822]: https://glia.atlassian.net/browse/MOB-1822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Auto accept Call Visualizer engagement

---

app/build.gradle

When opening a project for the first time Android Gradle might create a default 'local.properties' file. Gradle will attempt to read multiple properties once it detects that this file exists but will fail to find them later.
**P.S:** I have failed to extract this VERY repetitive logic to separate methods but it does its thing. If you know how to do that feel free to add to this solution.

Fix unknown property error when syncing Gradle

---

build.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

Fixed the bug with duplicate messages.
There was a bug in the chat screen, after the engagement is started the history messages were duplicated. It happened because the filter had worked incorrectly.

Fixed the bug with duplicate messages

---

app/src/main/res/values/themes.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/GliaScreenSharingCallback.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/data/GliaScreenSharingRepository.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/header/AppBarView.kt
widgetssdk/src/main/res/drawable/ic_screensharing_off.xml
widgetssdk/src/main/res/layout/app_bar.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/main/res/values/themes.xml

Development criteria summary by developer
* Button for screen sharing only on the toolbar that stops screen sharing session but keeps engagement going
* Button is configurable host app theme(icon and tint)
* ADA compliance

MOB-1682 Implemented button on toolbar with configurability and ADA compliance

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerCallback.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerRepository.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/domain/IsCallOrChatScreenActiveUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/ActivityWatcherForDialogs.kt
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/domain/IsCallOrChatScreenActiveUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/helper/ActivityWatcherForDialogsTest.kt

[MOB-1824](https://glia.atlassian.net/browse/MOB-1824)
[MOB-1824]: https://glia.atlassian.net/browse/MOB-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- Created and registered `ActivityWatcherForDialogs` for showing dialogs on top of any Activity except `CallActivity` and `ChatActivity`. `ActivityWatcherForDialogs` contains the logic to register/unregister dialog callback and dialogs implementation inside dialog callback
- Subscribe to `Media.Events.MEDIA_UPGRADE_OFFER` in `CallVisualizerRepository`, trigger appropriate dialogs on incoming event 
- Created `CallVisualizerController` with `CallVisualizerRepository`
- Made media request dialogs support runtime theme mechanism (see `MaterialThemeOverlay.wrap` and default …

MOB-1824 Display alert dialog for Call Visualizer media engagement request

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingActivity.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingView.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/RemoteConfiguration.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/base/HeaderRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/endscreenshare/EndScreenShareRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ViewExstensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/UnifiedTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/endscreenshare/EndScreenSharingTheme.kt
widgetssdk/src/main/res/layout/end_screen_sharing_activity.xml
widgetssdk/src/main/res/layout/end_screen_sharing_view.xml
widgetssdk/src/main/res/values/dimens.xml
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/EndScreenSharingControllerTest.kt

Button atm crashes the application due to TODO. Functionality will be added in MOB-1825

Created end screen sharing view

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/mediaupgradeoffer/MediaUpgradeOfferRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/mediaupgradeoffer/domain/AddMediaUpgradeOfferCallbackUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/mediaupgradeoffer/domain/RemoveMediaUpgradeOfferCallbackUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

This will avoid AlertDialog extra creation when switching between Chat and Call and avoid memory leak on Call/Chat screen closing
[MOB-1880](https://glia.atlassian.net/browse/MOB-1880)
**Steps to reproduce the issue:**
- visitor starts a chat engagement
- operator upgrades to One-Way video
- visitor accepts
- visitor goes back to Chat screen
- operator upgrades to Two-Way video
- visitor accepts
- visitor goes back to Chat screen
**Expected result:** AlertDialog is closed
**Actual result:** Two-Way video upgrade dialog is still displayed and cannot be dismissed
Video recording of the bug can be found in [SSD-33295](https://glia.atlassian.net/browse/SSD-33295)
**Reason:** ChatView and CallView stay alive and MediaUpgradeOfferRepositoryCallback is registered for both screens' controllers. …

Add/remove MediaUpgradeOfferRepositoryCallback in onResume()/onPauseof ChatView and CallView

---

app/src/main/res/values/themes.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/NewMessagesDividerViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/queue/GliaQueueRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/GetUnreadMessagesCountWithTimeoutUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/res/layout/chat_new_messages_divider_layout.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/main/res/values/themes.xml
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/GetUnreadMessagesCountWithTimeoutUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-1735
When fetching chat transcript, there is a field called delivered_at which can have a date, or can be nil. If it’s nil, it means that the message hasn’t been read yet. Above the oldest unread message, there should be a new message divider that looks like the document in Figma. This component has to be fully translatable and accessible.
https://user-images.githubusercontent.com/19994238/220933523-63988f41-a6b9-4eea-9af9-1c5b49be4f7b.mp4

Show a new messages divider in secure conversations chat transcript

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/mediaupgradeoffer/MediaUpgradeOfferRepository.java

[MOB-1880](https://glia.atlassian.net/browse/MOB-1880) broke the "start new Audio/Video engagement" flow . That's why acceptance tests are failing now (example app crashes on 'Start new audio call' menu item tap).
What this pull request does:
1. Adds media upgrade offer callback for a new Audio/Video engagement flow  -  callback still need to be added from the `init()` function.
2. Changing collection type to `Set` to prevent callback duplication.
[MOB-1880]: https://glia.atlassian.net/browse/MOB-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add media upgrade offer callback for a new call

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallState.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/res/layout/call_buttons_layout.xml

MOB-1817
Implemented Call visualizer engagement disables CallView audio controls
https://salemove.slack.com/archives/C04BTHLDL9Y/p1677679060595919 decision to not show disabled buttons.

Added hide audio buttons when callvisualizer session is active

---

widgetssdk/src/main/java/com/glia/widgets/view/CharCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ResourceExtensions.kt
widgetssdk/src/main/res/layout/visitor_code_view.xml
widgetssdk/src/main/res/values/strings.xml

MOB-1819
This was the best I was able to do, minor imperfections keep happening, but I think the current version is good enough.
TalkBack will talk to finish the sentence and depending on the loading time might skip some elements. For this reason I disabled contentDescription for close and glia image because those kept coming up in undesired ways. Close button description is added back in a way that won't be read out automatically

Improved ADA compatibility

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerTest.kt

This is a small PR aimed to rename 
`ActivityWatcherForDialogs` to `ActivityWatcherForCallVisualizer`.
The main idea is that `ActivityWatcherForDialogs` is currently not only for dialogs but for bubble also. That's why I think the new name can reflect what's class purpuse better.

Rename ActivityWatcherForDialogs to ActivityWatcherForCallVisualizer

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerRepository.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/domain/GliaOnCallVisualizerEndUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/domain/GliaOnCallVisualizerUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/domain/IsCallVisualizerUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/ResolveChatHeadNavigationUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/notification/domain/ShowVideoCallNotificationUseCase.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerTest.kt

[Hide bubble on call visualizer end](https://glia.atlassian.net/browse/MOB-1957)
[Skip survey on Call Visualizer engagement end](https://glia.atlassian.net/browse/MOB-1959)
Besides, moved several classes from `engagement` to `callvisualizer` package.

Hide screen sharing bubble on call visualizer end

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt

Prevent to show the Screen Overlay permission on the Welcome to Message Center screen.
The crash cause: In case when the Welcome screen opens then the Chat screen opens:
- Chat controller during initialization asks to display the Screen Overlay dialog;
- Chat view is not ready for the handling of the dialogs;
- But the Welcome view is still ready to handle dialogues. However, it can't handle the Screen Overlay dialog. 
[MOB-1965](https://glia.atlassian.net/browse/MOB-1965)
[MOB-1965]: https://glia.atlassian.net/browse/MOB-1965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the Screen Overlay permission request

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/layout/main_fragment.xml

[MOB-1972](https://glia.atlassian.net/browse/MOB-1972)
Fix for [this bug](https://github.com/salemove/android-sdk-widgets/pull/496#discussion_r1135100808). 
Bug was introduced in the [Create a public interface for the integrator to show Visitor Code](https://github.com/salemove/android-sdk-widgets/commit/615290e86553b4c0eed351220748ae5545505371) commit. Chat head layout is added to root container. And in this commit, container height was changed from `android:layout_height=match_parent` to `android:layout_height=wrap_content`. Hence, instead of occupying the whole screen, it became shrunk.
The idea of the fix is to add FrameLayout to provide `match_parent` height for `ChatHeadLayout`.
[MOB-1972]: https://glia.atlassian.net/browse/MOB-1972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …

Set correct (match_parent) height for ChatHeadLayout in MainFragment

---

bitrise.yml

[Devs want to add build failure notifications for master Bitrise job in Android SDK Widgets](https://glia.atlassian.net/browse/MOB-1974)
As part of the recent acceptance tests issue on iOS, it was discovered that something similar can happen in Android. A Slack notification for failed jobs in the master workflow needs to be added, in order to know about failures for uploading to Browserstack.

Send Slack notification even if master build workflow fails

---

app/build.gradle
app/src/main/java/com/glia/exampleapp/ChatFragment.java
app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/values/setup.xml
app/src/main/res/xml/preferences.xml
app/src/master/res/values/setup.xml
bitrise.yml

After this change, the Queue ID can be provided using the argument GLIA_QUEUE_ID in the local.properties project file or as an environment variable.
Also added this variable in CI
Also, update the [guide for the CE](https://glia.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=3121020935&selectedPageVersions=12&selectedPageVersions=13)
Also removed 'master' build variant as it does not provide any benefits

Extract Glia Queue ID from project source code

---

build.gradle
widgetssdk/build.gradle
widgetssdk/src/androidTest/java/com/glia/widgets/CallActivityTest.java
widgetssdk/src/androidTest/java/com/glia/widgets/DownloadsFolderDataSourceTest.java
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/GetUnreadMessagesCountWithTimeoutUseCaseTest.kt

Fix GetUnreadMessagesCountWithTimeoutUseCase unit tests.
Also, downgrade the Mockito version for UI tests to be able to run them on API 24.
[MOB-1996](https://glia.atlassian.net/browse/MOB-1996)
[MOB-1996]: https://glia.atlassian.net/browse/MOB-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix unit tests

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/java/com/glia/widgets/view/button/BaseConfigurableButton.java
widgetssdk/src/main/java/com/glia/widgets/view/header/AppBarView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ViewExstensions.kt

https://glia.atlassian.net/browse/MOB-1991
Also updated a bit of code for all other dialogs as some of them missed font family in buttons and to overall make the code more consistent
Additionally, it seems that `BaseConfigurableButton.setTheme(UiTheme)` does not apply themes correctly. I marked it as deprecated and replaced it in `Dialogs.kt`.

Add runtime theme support for CV media upgrade dialogs

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherControllerTest.kt

https://glia.atlassian.net/browse/MOB-1978
- Fixed wrong media upgrade messages in Call Visualizer
- Added check for Call Visualizer not to request camera permission for a one-way video stream
- Fixed system mic/camera/screen-sharing permissions not being requested on API 28 and lower

Media upgrade bugfixing

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/FindNewMessagesDividerIndexUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaLoadHistoryUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/model/ChatHistoryResponse.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/domain/FindNewMessagesDividerIndexUseCaseTest.kt

Initially, the unread messages divider was placed incorrectly when there were visitor messages in the mix. 
[MOB 2029](https://glia.atlassian.net/browse/MOB-2030)

FIx new messages' divider didn’t place in the right place 

---

widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

[MOB-2057](https://glia.atlassian.net/browse/MOB-2057)
- Handle on hold state change for application bubble
- Remove `VisitorMediaStateListener` for global bubble from `onDestroy()` (is not related to bug, I just noticed that it was missing)
[MOB-2057]: https://glia.atlassian.net/browse/MOB-2057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle on hold state change for application bubble

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherControllerTest.kt

[MOB-2064](https://glia.atlassian.net/browse/MOB-2064)
- prevent asking camera permission for one-way video request in Call Visualizer
- fix unit tests (explicitly pass `mediaUpgradeOffer` mock)
[MOB-2064]: https://glia.atlassian.net/browse/MOB-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not request camera permission for one-way video request in Call Visualizer

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt

According to a chat with Karl, I think it makes sense to rename `ActivityWatcherController` to `ActivityWatcherForCallVisualizerController`.
Pros:
- corresponds to `ActivityWatcherForCallVisualizer`
- name will be aligned with `ActivityWatcherForChatHeadController`
Cons:
- longer name

Rename ActivityWatcherController for Call Visualiser

---

widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/IsDisplayChatHeadUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/ActivityWatcherForChatHead.kt

[MOB-2068](https://glia.atlassian.net/browse/MOB-2068)
It was decided to display chat bubble for this flow:
1. Start audio/video engagement
2. audio/video call view opens
3. tap on “chat” button
4. Chat view opens
Expected result: bubble is displayed and navigates the visitor to Call screen once it’s tapped.
[MOB-2068]: https://glia.atlassian.net/browse/MOB-2068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show chat bubble on Chat screen if visitor comes from Call screen

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/SurveyStateManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/HasPendingSurveyUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/ResolveChatHeadNavigationUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/SetPendingSurveyUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/SetPendingSurveyUsedUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

MOB-2007
The problematic flow was the following:
- Set engagement to not have a survey
- Start chat engagement with operator connected
- minimize the chat screen
- disconnect the operator
- click on bubble
Expected result:
- engagement ended dialog is shown
Actual result:
- app would show unexpected dialog
- when starting a new chat engagement, the engegement ended dialog is shown
Same for Call as well.

Fixed end screen sharing dialog anomalies

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/view/header/AppBarView.kt

[MOB-2075](https://glia.atlassian.net/browse/MOB-2075)
There was an End and X button for video, it should not be there for Call Visualizer engagement per the design.
[MOB-2075]: https://glia.atlassian.net/browse/MOB-2075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not display End button on Call screen for Call Visualizer

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/VisitorCodeController.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt

MOB-2063
Described issue no longer reproducible since core version was updated. Found one other issue where when dialog was dismissed by starting engagement, the timer was not reset. Added some logging to visitor code refresh timer for clarity.

Fixed unwanted behaiour on visitor code view, added logging

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

[MOB-2071](https://glia.atlassian.net/browse/MOB-2071)
Flow:
1. Start Call Visualizer engagement
2. From Main screen of example app tap “Start new chat flow”.
**Expected result is:** tap is ignored, nothing should happen.
**Actual result is:** Chat screen is opened, visitor can send a message.
[MOB-2071]: https://glia.atlassian.net/browse/MOB-2071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not allow to open Chat screen in Call Visualizer flow

---

app/build.gradle
bitrise.yml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
scripts/publish-module.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/AttachmentPopup.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/UploadAttachmentAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/head/BadgeTextView.kt
widgetssdk/src/main/java/com/glia/widgets/view/textview/BaseConfigurableTextView.java

https://glia.atlassian.net/browse/MOB-2085
Here is migration guide and description of some changes - https://medium.com/androiddevelopers/5-ways-to-prepare-your-app-build-for-android-studio-flamingo-release-da34616bb946
- Upgrade Kotlin to latest(1.8.20) version
- Upgrade test-related dependencies
- Upgrade secure core_sdk url
- Migrate no non-transitive R class
- Migrate no non-final-resID
- Add the `set java version` step to bitrise, it will change Gradle Java version to 17 and fasten Android build up to 20%

Migrate agp to 8.0.0

---

app/src/main/java/com/glia/exampleapp/ChatFragment.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ActivityWatcherForChatHead.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ActivityWatcherForChatHeadContract.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ActivityWatcherForChatHeadController.kt
widgetssdk/src/test/java/com/glia/widgets/view/head/ActivityWatcherForChatHeadTest.kt

[MOB-2055](https://glia.atlassian.net/browse/MOB-2055)
Steps:
1. start audio engagement (Call screen is opened)
2. Tap "Chat" icon (Chat screen is opened)
3. Tap "back" icon from application (Call screen is opened)
4. Tap "back" icon from application
**Expected result:** Call screen is closed, Main screen is opened
**Actual result:** Chat screen is opened again (loops back several times)
PR fixes this.
Besides, there was (and still is) a difference between application "back" and device "back" behavior on the 3rd step.
Application "back" closes Chat screen and navigates to Call screen. I would say it's expected.
Device "back" closes Chat screen and navigates to Main screen. 
I haven't found a way to align the behaviors, unfortunately.
If you have an idea - I would appreciate it.
Anyway, …

Finish Chat screen when navigating back to Call screen

---

widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt

White label stands for overriding product branding. Defaoult value for white label should be 'false' as it is purchasable feature. And 'whiteLable=false' means that Glia logo should be visible by default.
MOB-2074

Fix white lable behavior

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/data/GliaChatRepository.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaOnMessageUseCase.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/UnengagementMessageUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

Replace an attachment for the visitor messages with an attachment from messages received from web sockets if a message was sent using the secure conversation endpoint.
[MOB-2046](https://glia.atlassian.net/browse/MOB-2046)
[MOB-2046]: https://glia.atlassian.net/browse/MOB-2046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle attachments from web sockets

---

widgetssdk/src/main/java/com/glia/widgets/chat/domain/UnengagementMessageUseCase.kt

After the [PR](https://github.com/salemove/android-sdk-widgets/pull/562) merged project has a build time error. This is a tiny fix for the UnengagementMessageUseCase visibility type.

Make UnengagementMessageUseCase internal

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt

MOB-2089
Created a new separation between dismissing dialog and dismissing dialog in backstack

Fixed persisting dialog

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingActivity.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingView.kt
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/CallVisualizerManager.java
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/domain/CallVisualizer.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaEngagementRepository.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

[MOB-2048](https://glia.atlassian.net/browse/MOB-2048)
1. Implemented the "end Call Visualizer engagement event" listening.
2. Implemented `EndScreenSharingActivity` finishing.
3. [Handled](https://github.com/salemove/android-sdk-widgets/pull/563/commits/e8dcbe28d1aa4092e75056a59e72cd0b16c3b0ce) survey absence for Call Visualizer
[MOB-2048]: https://glia.atlassian.net/browse/MOB-2048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Finish end screen-sharing screen on engagement end by operator

---

app/build.gradle
widgetssdk/src/main/java/com/glia/widgets/view/head/ActivityWatcherForChatHead.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

MOB-2115
**Steps to reproduce:**
Start Call Visualizer engagement with screen sharing ongoing and bubble on screen
Open EndScreenSharingView by clicking on the bubble
Make quick subsequent configuration changes
**Expected result:**
Application lives through the configuration changes and restores view
**Actual result:**
Application crashes with a NPE

Added additional null check to serviceChatHeadController

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingView.kt

[MOB-2117](https://glia.atlassian.net/browse/MOB-2117)
I noticed the Android Studio warning for EndScreenSharingView: `applyRuntimeTheme()` is never used.
As far as I understand, it should be used.
Based on my investigation, it happened after resolving merge conflicts in [this commit](https://github.com/salemove/android-sdk-widgets/commit/3deef415e501ee959aa65d2b1aa88c63c1671731).
[MOB-2117]: https://glia.atlassian.net/browse/MOB-2117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Apply runtime theme to EndScreenSharingView

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerSupportActivity.kt
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/GliaScreenSharingCallback.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.kt
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/data/GliaScreenSharingRepository.java
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt

- Dismiss screen sharing notification if visitor rejects system permission
- Fix broken mechanism of requesting permissions through CallVisualizerSupportActivity
- Expand this mechanism to be able to use for requesting screen-sharing permission for a non ComponentActivity

Dismiss screen sharing notification if visitor rejects system permission

---

app/src/main/java/com/glia/exampleapp/RemoteThemeSettingsFragment.kt
app/src/main/java/com/glia/exampleapp/RuntimeThemeSettingsFragment.kt
app/src/main/java/com/glia/exampleapp/SdkBasicSettingsFragment.kt
app/src/main/java/com/glia/exampleapp/SettingsFragment.java
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/xml/all_prefs.xml
app/src/main/res/xml/remote_theme_prefs.xml
app/src/main/res/xml/runtime_theme_prefs.xml
app/src/main/res/xml/sdk_basic_prefs.xml

https://glia.atlassian.net/browse/MOB-2135
The testing app settings screen became too long and had to navigate. Additionally, there is a need for more settings as part of the https://glia.atlassian.net/browse/MOB-2135 task.
In this PR I have not changed or added any settings just moved them around
SettingsFragment
SdkBasicSettingsFragment
RuntimeThemeSettingsFragment
RemoteThemeSettingsFragment

Refactor testing app settings screen

---

widgetssdk/src/main/java/com/glia/widgets/core/screensharing/data/GliaScreenSharingRepository.java

https://glia.atlassian.net/browse/MOB-2102
Declining system permission for screen recording breaks new screen recording requests

Fix screen recording system permission decline issue

---

app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.kt
app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/remote_theme_prefs.xml
app/src/main/res/xml/runtime_theme_prefs.xml

https://glia.atlassian.net/browse/MOB-2174
Before the runtime theme settings were not applied on the SDK `init` but only when launching ChatActivity or CallActivity. Also added a simple toggle to runtime theme settings to easily enable/disable the runtime theme settings without having to clear app data.

Update runtime theme settings to be applied to Call Visualizer

---

widgetssdk/src/main/java/com/glia/widgets/chat/data/GliaChatRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/SecureFileAttachmentRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/SendSecureMessageUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

Use live chat endpoints for message sending when an engagement started for the Welcome to Message Center screen
[MOB-2159](https://glia.atlassian.net/browse/MOB-2159)
[MOB-2159]: https://glia.atlassian.net/browse/MOB-2159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Messages with attachments are not delivered if an engagement starts

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt

https://glia.atlassian.net/browse/MOB-2171
The issue was caused by the DialogController addCallback() method, which always fired the current dialog state. 
CallActivity and ChatActivity always add/remove the callback on Activity onResume/onPause to prevent the same dialog from appearing on both Activities. But as a result, because of this, a duplicate second dialog was being with Activity having no callbacks attached to it.
Ideally, need the full refactoring of the Alert dialogs logic in Widgets SDK. Asked this refactoring request to be added to the Android tech depts.

Fix Activity onPause/onResume breaking the permission dialog

---

widgetssdk/src/main/java/com/glia/widgets/helper/Files.kt

Fixed the function that return a file name for an attached file.
[MOB-2184](https://glia.atlassian.net/browse/MOB-2184)
[MOB-2184]: https://glia.atlassian.net/browse/MOB-2184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix file name generating

---

widgetssdk/src/main/java/com/glia/widgets/base/BaseActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/ActivityWatcherForChatHead.kt

https://glia.atlassian.net/browse/MOB-2179
https://glia.atlassian.net/browse/MOB-2180
ActivityWatchers are losing reference to current activity on screen rotation when multiple activities are being recreated and for some reason, activity from the back gets 'resumed' for a short moment (probably it was partially visible) and then again paused. As a result, ActivityWhatcher thought that all activities are paused.

Fix ActivityWatchers loosing refference to current Activity

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/PreEngagementMessageUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

Since we decided not to merge the changes for the order of the welcome message fix, I prepared the commit for the relevant renaming that we decided to do there.
`PreEngagementMessage` way better describes the situation there they use instead of `UnengagementMessage`. Thank @andrews-moc for that advice!

Renaming UnengagementMessage to PreEngagementMessage

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatViewCallback.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/ImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/data/GliaFileRepository.kt
widgetssdk/src/main/java/com/glia/widgets/filepreview/data/GliaFileRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/filepreview/data/source/local/DownloadsFolderDataSource.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/domain/usecase/IsFileReadyForPreviewUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/helper/Files.kt
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

Fixed wrong image preview.
Prevent opening an image unless it is ready for preview (same behavior as on iOS).
Also, refactored work with files.
[MOB-2190](https://glia.atlassian.net/browse/MOB-2190)
[MOB-2190]: https://glia.atlassian.net/browse/MOB-2190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix wrong image preview

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/domain/GliaOnCallVisualizerEndUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/ToggleChatHeadServiceUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

[MOB-2186](https://glia.atlassian.net/browse/MOB-2186)
- reset survey from `clearVisitorSession()`
- close bubble when `clearVisitorSession()` is called
- unsubscribe engagement end listeners for a bubble when `clearVisitorSession()` is called
- do not destroy bubble controllers on chat closing
- rename `engagementEnded()` to `callVisualizerEngagementEnded()` for Call Visualizer to have separate handling
- amend `onSurveyLoaded()` logic in `ChatController`
Check list for manual testing is [here](https://glia.atlassian.net/wiki/spaces/ENG/pages/3360489599/End+engagement+and+clear+visitor+session+flows).
[MOB-2186]: https://glia.atlassian.net/browse/MOB-2186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Clear survey and engagement state when clearing visitor session

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt

https://glia.atlassian.net/browse/MOB-2181
ActivityWhatcherForCallVIsualizer was failing to unregister the callback for Glia Alerts because of race condition - it created a new callback and overrode the old one before unregistering the old one from DialogController

Fix ActivityWatcher getting registered for Dialog events multiple times

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt

MOB-2214
With no notification permission, the dialog was called on background thread, fixed it

Fixed dialog being called from background thread

---

app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.java

[MOB-2154](https://glia.atlassian.net/browse/MOB-2154)
The whole scope of changes includes:
- Changes in acceptance tests: [pull request](https://github.com/salemove/acceptance_tests/pull/3284)
- Changes in Android Widgets SDK: [pull request](https://github.com/salemove/android-sdk-widgets/pull/596)
- Changes in Android Core SDK: [pull request](https://github.com/salemove/android-sdk/pull/459)
Also, removed `@Nullable` from a primitive type (Lint warning).
[MOB-2154]: https://glia.atlassian.net/browse/MOB-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Parse base domain from deep link and pass to Core SDK

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfigurationManager.java

[Screen sharing bubble is not displayed until the app passes chat engagement flow](https://glia.atlassian.net/browse/MOB-2216)
What problems do these changes solve?
- If `GliaWidgetsConfig.setUseOverlay()` is not set on Glia init, bubble is not displayed for CallVisualizer screen sharing (wrong)  but is displayed for regular engagements (correct)
- If `GliaWidgetsConfig.setUseOverlay(false)` is set, bubble is not displayed for CallVisualizer screen sharing (correct) but is still displayed for regular engagements (wrong)
The reason for that was the inconsistent usage of default values.

Apply SDK default configs consistently for Call Visualizer and Chat/Call screens

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt

`AudioManager` from the application context works without stuck.
[MOB-2234](https://glia.atlassian.net/browse/MOB-2234)
[MOB-2234]: https://glia.atlassian.net/browse/MOB-2234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Speaker mode gets stuck in the ON state

---

app/src/main/java/com/glia/exampleapp/MainFragment.java

During exploratory testing, some differences in the behavior of the Call Visualizer in the testing app caused small confusion. To prevent that from happening in the future I have removed the Toast message from appearing on CV engagement start and made the Visitor Code view to be hidden on CV engagement start

Update CV in Test App to behave same as in iOS

---

widgetssdk/src/main/java/com/glia/widgets/view/CharCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/res/layout/visitor_code_view.xml

[Bad accessibility compatibility for when text is set too big](https://glia.atlassian.net/browse/MOB-2252)
- set `CharCodeView` width to `0` and weight to `1` to fit available width
- set start and end insets of the visitor code dialog to 0
- set `textAlignment` instead of `gravity` to align have number centered inside the box
- set start and end padding for the first and last digit box

Make visitor code number boxes fit screen width

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/glia/exampleapp/UnifiedUiConfigurationLoader.kt
widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/res/layout/options_dialog.xml
widgetssdk/src/main/res/layout/options_dialog_reversed.xml
widgetssdk/src/main/res/layout/options_dialog_vertical.xml
widgetssdk/src/main/res/layout/options_dialog_vertical_reversed.xml

Fixed some minor bugs I found during work on big tasks. These are not critical, and not so big to make different PRs for each.
- Moved `android.permission.POST_NOTIFICATIONS` permission declaration from testing app `Manifest` to widget module `Manifest`. After this change, integrators will no longer need to manually declare this permission.
- Modified dialog title for some views to make it responsive. This fixes the bug when the title goes out of its paddings when a title text is long.
- Fixed UnifiedUiConfigurationLoader to make it not block the main thread when loading remote configurations.
Will merge after release, that’s the only reason I made it draft

Fix Dialog Ttitle and Push Notification Permission

---

bitrise.yml

[MOB-2022](https://glia.atlassian.net/browse/MOB-2022)
The aim of this PR is to get rid of the "You're using an outdated version of the "Deploy to bitrise.io" Step." warning to be able to check tests summary in Bitrise.
[MOB-2022]: https://glia.atlassian.net/browse/MOB-2022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update "Deploy to bitrise.io" step

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.java

[MOB-2226](https://glia.atlassian.net/browse/MOB-2226)
App token has been deprecated for over a year. A recent investigation into Datadog and Kibana logs showed that none of our clients are using app token anymore in their integration of our SDK.
[MOB-2226]: https://glia.atlassian.net/browse/MOB-2226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove App Token support

---

app/src/main/java/com/glia/exampleapp/ExampleCustomCardAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/CustomCardAdapter.java

The method `CustomCardAdapter.isInteractable()` had the wrong description.

Fixed the documentation for the CustomCardAdapter class

---

widgetssdk/src/main/java/com/glia/widgets/core/survey/GliaSurveyRepository.java

Sometimes the survey was loaded multiple times because the onEngagementEnded called multiple times with delay. So when try to request an engagement again, the survey screen was launched.

Fix the survey fetching logic

---

widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/main/res/values/dimens.xml

Made the chat text field expandable for long text. The max lines are 4.
[MOB-2335](https://glia.atlassian.net/browse/MOB-2335)
[MOB-2335]: https://glia.atlassian.net/browse/MOB-2335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Made the text entry field expand in the presence of long text

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt

Close the keyboard when the chat is scrolled.
To align platforms, scrolling needs to close the keyboard for better visibility of the transcript.
[MOB-2449](https://glia.atlassian.net/browse/MOB-2449)
[MOB-2449]: https://glia.atlassian.net/browse/MOB-2449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Close keyboard when chat is scrolled

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/data/GliaChatRepository.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaSendMessageUseCase.kt

Used the `sendMessage` method with `SingleChoiceAttachment` for sending the custom message response instead of the deprecated method.
Also refactored the sending custom card response methods.
This PR needs the additional release of the Core SDK, because it uses a method that is currently not available.
[MOB-2289](https://glia.atlassian.net/browse/MOB-2289)
[MOB-2289]: https://glia.atlassian.net/browse/MOB-2289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix sending custom card response

---

widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaEngagementRepository.java

https://glia.atlassian.net/browse/MOB-2455
This crash started happening after upgrade of the Core SDK. The cause of the crash is annotation on method argument (@NotNull) for the callback.

Fix crash on restoring CV video engagement from bubble

---

build.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/gva/DetermineGvaButtonTypeUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/gva/DetermineGvaUrlTypeUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/GvaBaseTypes.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/gva/DetermineGvaButtonTypeUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/gva/DetermineGvaUrlTypeUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-2379
The following types should be supported:
- `PostBack` - when `button.url` is not defined. 
- `Broadcast Event`(Not related to Android `BradcastEvents`) - when `button.destinationPbBroadcastEvent` is defined
-  `Phone` - when `url` scheme is `tel:`
-  `Email` - when `url` scheme is `mailto:`
-  `Url` - for the remaining cases, when `url` is defined

Create logic to differentiate various persistent button actions

---

settings.gradle

I think that since both Android and Widgets are names they should start with capital letters.
Also in consistency with https://github.com/salemove/android-sdk/pull/501

Update project name

---

widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt

Reversed dialog button changes were overridden.

MOB-2498 fixed reversed button dialog

---

app/build.gradle
app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.kt
app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/sdk_basic_prefs.xml

The region was added to the testing app settings.
Region value can be used in the `local.properties`. 
```
GLIA_REGION=us
```
Also, the value can be changed in the application settings.

Extend project setting with region value

---

app/build.gradle

Decided to make LeakCanary disabled by default. It is a great library, but it annoys me when I'm working on day-to-day tasks, so I think it is better to keep it disabled by default and enable it only when needed to check memory leaks.

Remove LeakCanary for default builds

---

bitrise.yml

The previous change made it so that it would merge the PR into the development branch however the branch itself was created from the master and not development. As a result, there were some strange additional commits that should not be there.

Make CI PR script to create new branch from development

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/core/notification/NotificationRemovalService.kt
widgetssdk/src/main/java/com/glia/widgets/core/notification/device/NotificationManager.kt

Remove the notification about audio/video engagement starts if an application is killed.
[MOB-2481](https://glia.atlassian.net/browse/MOB-2481)
[MOB-2481]: https://glia.atlassian.net/browse/MOB-2481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NotificationRemovalService

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/GvaButtonsAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaGalleryItemViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaPersistentButtonsViewHolder.kt
widgetssdk/src/main/res/layout/chat_gva_persistent_buttons_content.xml

The `ButtonAdapter` from the `GvaGalleryItemViewHolder` was extracted to a separate file. Now it is used for both `GvaGalleryItemViewHolder` and `GvaPersistentButtonsViewHolder`.
[MOB-2520](https://glia.atlassian.net/browse/MOB-2520)
[MOB-2520]: https://glia.atlassian.net/browse/MOB-2520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GVA: Use RecyclerView for the Persistent button options

---

widgetssdk/src/androidTest/java/com/glia/widgets/CallActivityTest.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorStatusViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/main/res/layout/survey_boolean_question_item.xml
widgetssdk/src/main/res/layout/survey_input_question_item.xml
widgetssdk/src/main/res/layout/survey_scale_question_item.xml
widgetssdk/src/main/res/layout/survey_single_question_item.xml
widgetssdk/src/main/res/values/donottranslate.xml
widgetssdk/src/main/res/values/strings.xml

MOB-2346
Created and unified new string keys in a backwards compatible manner. The only exception was made for the plurals key, where the override should be for the individual values, not the plural itself.
In minor places, trimmed down reference links in string values, still some TODO-s left in the strings.xml file but vast majority of them is about ADA witch is yet to be unified and will be done in MOB-2280
Decided it is probably be for the best to go with a feature branch approach for this, because we will probably start breaking things otherwise until main functionality is there. Should not cause many conflicts by the end though.

Implemented new unified strings

---

widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.java

[Input field is disabled after transfer from Bot to Queue](https://glia.atlassian.net/browse/MOB-2493)
Steps to reproduce:
Use “Bot only” queue to start with bot, then post the message “Transfer to Queueu {queue_id}”
Backport PR: https://github.com/salemove/android-sdk-widgets/pull/699

Enable chat input after engagement transfer (operator connected) (master hotfix)

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerSupportActivity.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt

This prevents the `java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant)` crash even if integrator's activity style is not Material.
ℹ️ I have not found a straightforward way to detect if Activity style is Material, so decided to use this solution regardless of Activity style.
ℹ️ This pull request is based on the [feature/fix_dialogs_crash](https://github.com/salemove/android-sdk-widgets/compare/development...feature/fix_dialogs_crash?expand=1) branch developed by Alexander. I created a separate branch because I came to the conclusion that additional ActivityWatcher `SupportActivityWatcher` is not needed. Instead, the code should be organized a bit differently.
ℹ️ I commented in the code the most …

Open dialogs on top of CallVisualizerSupportActivity instead of integrator's Activity (master hotfix)

---

widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.kt

[Input field is disabled after transfer from Bot to Queue](https://glia.atlassian.net/browse/MOB-2493)
Steps to reproduce:
Use “Bot only” queue to start with bot, then post the message “Transfer to Queueu {queue_id}”
This PR is a backport for hotfix: https://github.com/salemove/android-sdk-widgets/pull/700

Enable chat input after engagement transfer (operator connected) (development)

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaGalleryViewHolder.kt

The purpose of `SnapHelper` is to snap gallery items to the center. `PagerSnapHelper` scrolls one by one, which is not desired. We replaced it with `LinearSnapHelper` for center snapping only.

Replace PagerSnapHelper to LinearSnapHelper for Gallery list

---

widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt

Improved according to [suggested](https://github.com/salemove/android-sdk-widgets/pull/719#discussion_r1299156114) by @AndriiHorishniiMOC regex.
Here is a detailed explanation of the characters:
- `\r\n` is a line break in Windows.
- `\n` is a line break in Unix (macOS, Linux, etc.).
The regular expression (`\r\n|\n`) is saying that it should match either a Windows line break `\r\n` OR a Unix line break `\n`. Therefore, this is a way of matching a line break in a text file regardless of the operating system where the file was created.

Improve line break replacement logic

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt

You can check ticket description to find the scenarios, which these changes are to solving:
[Integrators want to use Android Widgets SDK without a need to use Material Theme in their projects](https://glia.atlassian.net/browse/MOB-2515)
There are two scenarios that are not solved yet, but their reason is different and I'm working on them separately.
@DavDo FYI, I decided not to move the logic from `ActivityWatcherForCallVisualizer` to `CallVisualizerSupportActivity` because:
- I'm not completely sure that this logic is only needed for `CallVisualizerSupportActivity`
- I've spent a good deal of time already, on this solution and don't want to spend more
- this change is, actually, refactoring and it doesn't solve the initial bugs

Improve solution for opening dialogs on top of CallVisualizerSupportActivity instead of integrator's Activity

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/di/ManagerFactory.kt
widgetssdk/src/test/java/com/glia/widgets/chat/ChatManagerTest.kt

I forgot to add the chat history reload step during chat flow optimization when a new engagement is established.
So here I added those steps and tests.
https://glia.atlassian.net/browse/MOB-2585

Fix The chat history is empty after restoring the chat.

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java

Some listeners subscribe only once in Call Visualizer, so we shouldn't unsubscribe
[SDK should receive and handle subsequent 2-way video and screen-sharing requests](https://glia.atlassian.net/browse/MOB-2556)

Do not unsubscribe from engagement events for Call Visualizer

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaResponseTextViewHolder.kt
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_GvaResponseTextViewHolderSnapshotTest_withChatHead.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_GvaResponseTextViewHolderSnapshotTest_withChatHeadWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_GvaResponseTextViewHolderSnapshotTest_withChatHeadWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_GvaResponseTextViewHolderSnapshotTest_withChatHeadWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_GvaResponseTextViewHolderSnapshotTest_withoutChatHead.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_GvaResponseTextViewHolderSnapshotTest_withoutChatHeadWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_GvaResponseTextViewHolderSnapshotTest_withoutChatHeadWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_GvaResponseTextViewHolderSnapshotTest_withoutChatHeadWithUnifiedTheme.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/adapter/holder/GvaResponseTextViewHolderSnapshotTest.kt

Added snapshot tests for GVA Response text.
[MOB-2601](https://glia.atlassian.net/browse/MOB-2601)
[MOB-2601]: https://glia.atlassian.net/browse/MOB-2601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cover Response text with snapshot tests

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapterDiffCallback.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/VisitorMessageViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/VisitorFileAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/VisitorImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/AppendHistoryChatItemUseCases.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/AppendNewChatItemUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/SendUnsentMessagesUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatItems.kt
widgetssdk/src/test/java/com/glia/widgets/chat/ChatManagerTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/AppendHistoryCustomCardItemUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/AppendHistoryVisitorChatItemUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/AppendNewOperatorMessageUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/AppendNewVisitorMessageUseCaseTest.kt

Previously, the chat flow only rendered visitor messages from the chat messages socket and ignored responses from the send message endpoint. However, these messages were not rendered during socket reconnection, leading to user confusion.
***Changes:***
- Add functions to handle send message response
- Remove redundant sealed classes from the Visitor message
- Optimize ChatAdapter for delivered status update
MOB 2603

Improve chat flow to handle sent message responses

---

widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ActivityWatcherForChatHeadController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

[Bubble is not displayed after Glia is initialized and engagement is restored](https://glia.atlassian.net/browse/MOB-2626)
**Steps to reproduce:**
Prerequisites: There is ongoing chat engagement.
1. Close the app
3. Open the app
5. Init Glia
**Expected result:** bubble is displayed for both cases: when screen overlay permission is/isn’t granted. Bubble displays operator avatar (if any). Bubble displays person icon if there is no avatar. Bubble tap navigates to chat screen.
**Actual result:** 
1) If overlay permission isn’t granted - bubble is not displayed. Although if visitor minimizes the app and maximizes again, bubble is displayed as per expected result. 
2) If if overlay permission is granted - bubble is not displayed. If visitor minimizes the app, bubble is displayed but person icon …

Display bubble right after Glia init if engagement is present

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/screensharing/ScreenSharingControllerTest.java

Made changes to dialog logic to solve race conditions and fix the dialogs queue.
In a nutshell, a dialog should be dismissed once, using the `Dialog.MODE_NONE` state. SupportActivity also should be destroyed by the `Dialog.MODE_NONE` state. The dialog `stateDeque` should be changed and all actions should be done before destroying the SupportActivity if it is used.
Demonstration:
1. The operator asks for screen-sharing
2. The user answers NO
3. The operator asks one-way video
4. The operator asks for screen-sharing
5. The user answers NO to screen-sharing
6. The user ACCEPTS one-way video
7. The operator asks two-way video
8. The operator asks for screen-sharing
9. The user answers YES to screen-sharing but does not allow notifications in the settings screen
10. The user answers NO to …

Fix the dialog display logic

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/screensharing/ScreenSharingControllerTest.java

Start screen sharing using the `ActivityWatcherForCallVisualizer` if it is not the Call or Chat Activity
[MOB-2627](https://glia.atlassian.net/browse/MOB-2627)
[MOB-2627]: https://glia.atlassian.net/browse/MOB-2627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix screen sharing request

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.kt

This case has been detected by the 'Screensharing on the audio engagement' acceptance [test](https://app-automate.browserstack.com/dashboard/v2/builds/d3f1c67c149f01d8238d3d62108cf74d67bfc825/sessions/cea0ec953faab749948a4a62ebfda137ea5d145e?overallStatus=error&projectIds=250430).
I've tested scenarios from the [Dialogs doc](https://glia.atlassian.net/wiki/spaces/ENG/pages/3486842894/Dialogs) and [Fix the dialog display logic PR](https://github.com/salemove/android-sdk-widgets/pull/754#issue-1884404350) (which basically fails acceptance tests) - they are working fine.

Fix screen sharing dialog displaying on a Chat Screen although screen-sharing request was accepted from Call screen

---

widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaOperatorRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/MapOperatorUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/UpdateOperatorDefaultImageUrlUseCase.kt
widgetssdk/src/test/java/com/glia/widgets/core/engagement/GliaOperatorRepositoryTest.kt

[Operator avatar image does not respect the "Always Use the Default Operator Picture" Glia Hub setting](https://glia.atlassian.net/browse/MOB-2690)
[Test scenarios](https://glia.atlassian.net/wiki/spaces/ENG/pages/3504668722/Operator+image)
R (release notes) - Changes that the integrator may be interested in.

Account for the "Always Use the Default Operator Picture" Glia Hub setting

---

app/src/main/java/com/glia/exampleapp/Activity.java
app/src/main/java/com/glia/exampleapp/Application.java
app/src/main/java/com/glia/exampleapp/ExampleAppConfigManager.kt
app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallIntentBuilder.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfigurationManager.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.kt

[Implement Company name from custom locales](https://glia.atlassian.net/browse/MOB-2685)
**Changes overview**
- Company name can now be taken from a single source of truth: `Dependencies.getSdkConfigurationManager().companyName`
- Dropped a way to specify company name through `Intent` (see migration guide)
- Company name priority setup for Android is going to be: custom locales (highest priority) => SDK configuration => default value, which is "Company Name".
- Renamed GliaWidgetsConfigManager to ExampleAppConfigManager to cross it out from the number of classes related to configuration.
[Additional details](https://salemove.slack.com/archives/C04JS5GH6AD/p1695891888361899) on taken decisions.
**Migration guide:** _If you were specifying the company name by …

Apply company name from custom locales

---

widgetssdk/src/androidTest/java/com/glia/widgets/CallActivityTest.java
widgetssdk/src/main/res/values/new_strings.xml

[Verify/improve ADA compliance string use in Android SDK](https://glia.atlassian.net/browse/MOB-2726)
- Checked if we need any of the unused accessibility strings
- Moved strings that are used from NEW REFERENCES section

Remove unused accessibility and other strings

---

widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfigurationManager.java
widgetssdk/src/test/java/com/glia/widgets/core/configuration/GliaSdkConfigurationManagerTest.kt

[Company name local fallback is ignored when Sdk config value is null](https://glia.atlassian.net/browse/MOB-2782)
Company name local fallback was ignored when SDK config value was null. This issue should be fixed now.

Apply company name local fallback when SDK config value is null

---

widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.kt

MOB-2681
https://glia.atlassian.net/browse/MOB-2681
Fixed unread message indicator being shown on the bubble during Call Visualiser engagement

Prevented unread indicator to be shown during call visualizer engagement

---

.github/actions/deployment-action/action.yml
.github/actions/deployment-action/deployment-action.ts
.github/actions/deployment-action/package-lock.json
.github/actions/deployment-action/package.json
.github/actions/deployment-action/tsconfig.json
.github/workflows/deployment.yml

A new GitHub Action validates the branch name from where it has been run and fails if the branch name is not 'master' or 'release/'.
Contains 2 commits:
- GitHub Action source in ts. Be aware that js files are generated by es2016 https://github.com/salemove/android-sdk-widgets/pull/807/commits/3d48b77959f1e9525d02aedd3a4b75ae8c427f28
- Contains node_modules required for running Action https://github.com/salemove/android-sdk-widgets/pull/807/commits/ee047a6b941cc09fc6c46ba021c0fdcac7b2a020

GitHub Action for validation branch name during deployment workflow

---

widgetssdk/src/main/java/com/glia/widgets/helper/Logger.kt
widgetssdk/src/test/java/com/glia/widgets/helper/LoggerTest.kt

[Developers want the Logger functions to be non-static in Widgets and Core SDK](https://glia.atlassian.net/browse/MOB-2822)
1. Disallow integrators to use our Logger directly so that they should not be able to call `com.glia.widgets.helper.Logger.d("Integrator", "Hello, Glia developers ;)")`.
2. Add unit tests for `Logger class`.
I decided to go with a simple and reliable solution instead of initially planned (see TL;DR for the details).
TL;DR
The initial idea was to make logging functions non-static in `Logger`. Make the `Logger` constructor private. Inject Logger to the components using DI (e.g. ControllerFactory, etc).
However, it turned out that this approach has several disadvantages:
- it's not possible to inject to all type of components, in some places I had …

Hide Logger functionality from public usage, add unit tests for Logger class

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaOnMessageUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/test/java/com/glia/widgets/chat/ChatManagerTest.kt

https://glia.atlassian.net/browse/MOB-2835
I have included new verifications to ensure that the `ChatMessage` is valid, before emitting it to the ChatManager. 
The issue of broken flow in the **image/file** sending feature of Secure Conversations Chat has been resolved.
Copied `ChatmanagerTest`.`initialize subscribes to state and quick replies` test case improvement from LO branch, because it was flaky, and was failing the first time when there were changes related to that test.

Fix - Sending image/file in SC is broken

---

widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/alert/AlertDialogViewBinding.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/alert/AlertDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogDelegate.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogPayload.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogService.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogType.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewBinding.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewFactory.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/operatorendedengagement/OperatorEndedEngagementDialogViewBinding.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/operatorendedengagement/OperatorEndedEngagementDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/option/OptionDialogViewBinding.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/option/OptionDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/screensharing/ScreenSharingDialogViewBinding.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/screensharing/ScreenSharingDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/update/UpgradeDialogViewBinding.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/update/UpgradeDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/ThemeWrapper.kt

MOB 2814
https://glia.atlassian.net/browse/MOB-2814
- Created a mechanism to create GlobalColors from UiTheme. This helped to create AlertTheme from UiTheme and then merge it with provided by UnifiedUi, so now all the Dialog Views are configured with AlertTheme
- Created a mechanism to inflate all the Dialog Views independently and before Dialog is created. This will make all the Views(fully configured with themes) available outside of Alertdialogs and Dialog builders so that these views can be easily tested in snapshot tests.
All these changes will make it easy to change any of these views independently, without affecting other dialogs.
2nd part of improvements are here - https://github.com/salemove/android-sdk-widgets/pull/834 …

Refactor Dialogs to inflate views independently

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt

MOB 2847
https://glia.atlassian.net/browse/MOB-2847
Add Screen sharing callback only when the `CallVisualizer` engagement is started.
This way we will not brake showing screen sharing dialog from `ActivityWatcherForCallVisualizer` only for CV flows and it will also be safe for configuration changes

Fix The dialog for screen sharing in the CV flow is not appearing

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/ImageAttachmentViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/helper/Logger.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/test/java/com/glia/widgets/core/screensharing/data/GliaScreenSharingRepositoryTest.java
widgetssdk/src/test/java/com/glia/widgets/helper/LoggerTest.kt

[Developers want to be able to send logs from Widgets SDK](https://glia.atlassian.net/browse/MOB-2789)
These changes work based on the [Inject Core SDK Logger to Widgets SDK](https://github.com/salemove/android-sdk/pull/591) changes suggested for Core SDK.
So all logs will go through Core SDK `LoggingAdapters` and as a result will be sent to ~LogCat (via `StdoutAdapter`) and to the backend(via `ClientLoggerAdapter`)~ the same `LoggingAdapters` as attached to Core SDK.
**Mechanism explanation**
1. Added the `Logger.addAdapter(LoggingAdapter)` private method. It will be used by Core SDK through reflection. All added adapters are saved in a private `loggingAdapters` list.
2. When logging event happens, `Logger` will iterate through `loggingAdapters` list …

Send logs through Core SDK logger

---

app/src/main/res/raw/sample_unified_config.json
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogPayload.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogType.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewFactory.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/confirmation/ConfirmationDialogViewBinding.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/confirmation/ConfirmationDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/UnifiedUiExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/alert/AlertRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/alert/AlertTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Alert.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Button.kt
widgetssdk/src/main/res/layout/confirmation_dialog.xml
widgetssdk/src/main/res/layout/confirmation_dialog_vertical.xml
widgetssdk/src/main/res/values/new_strings.xml

https://glia.atlassian.net/browse/MOB-2862
Added the ability for integrators to add links to their “terms and conditions” or/and “privacy policies” to the live observation confirmation dialog.

Add links to confirmation dialog

---

widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorMediaRepository.java

https://glia.atlassian.net/browse/MOB-2909
Separated audio and video onHold listeners. Now, an audio and a video state are saving separately during onHold.
Fixed resume audio and video after resuming from onHold.

Fix onHold handling

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaEngagementStateRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/ManagerFactory.kt
widgetssdk/src/test/java/com/glia/widgets/chat/ChatManagerTest.kt

MOB 2926
- I have optimized the chat history loading process to prevent unnecessary history requests.
- Prevent `ChatController.viewInitPreQueueing()` for ongoing engagements, this will prevent queuing state addition
- `private final ReplayProcessor<EngagementStateEvent> engagementStateEventProcessor = ReplayProcessor.createWithSize(20);` this is a really stupid solution, but I didn't find anything better, because we're starting to push states way before subscribing to them in the chat screen so `Operator Connected` state is getting lost for restored engagements. This part is already refactored in #849 so this is temp. solution.

Remove queuing animation when current engagement is restored

---

app/src/main/java/com/glia/exampleapp/ExampleAppConfigManager.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt

MOB-2945
https://glia.atlassian.net/browse/MOB-2945
Default screen sharing mode is changed from `UNBOUNDED` to `APP_BOUNDED`. To have the same screen sharing capabilities the screen sharing modes need to be specified during initialisation.
```
GliaWidgetsConfig widgetsConfig = new GliaWidgetsConfig.Builder()
...
.setScreenSharingMode(screenSharingMode)
...                
.build();
```

Changed default screen sharing mode

---

app/src/main/java/com/glia/exampleapp/ChatFragment.java
app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallController.java

[Developers want to clean-up internal usages of deprecated functions](https://glia.atlassian.net/browse/MOB-2888)
Most of the deprecated functions in Widgets are related to the deprecated customization approach which we will remove someday. So, there is not much we can do now in Widgets, it seems.

Clean-up internal usages of deprecated functions

---

build.gradle

Nullpoint error fix related to screen-sharing have been solved in the latest Core SDK build

Update Core SDK dependency to latest development build

---

widgetssdk/src/main/java/com/glia/widgets/core/notification/device/INotificationManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/notification/device/NotificationManager.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java

[MOB-2837](https://glia.atlassian.net/browse/MOB-2837)
**Crash details:**
```
java.lang.IllegalStateException: Not allowed to start service Intent { com.glia.widgets.core.notification.NotificationRemovalService }: app is in background
```
Example from Sentry is [here](https://glia.sentry.io/issues/4766376086/?alert_rule_id=967509&alert_timestamp=1703689998756&alert_type=email&environment=prod-us&notification_uuid=097e6631-f490-4032-8f8f-622acb0a80d3&project=1887832&referrer=alert_email).
This happens if an app is in the background for 60+ seconds and `NotificationRemovalService` is attempted to be started.
Lets start `NotificationRemovalService` when app goes to 'OnStop' to make sure the service is not attempted to start after app being in background for over than 60 …

Fix IllegalStateException: for NotificationRemovalService

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatViewCallback.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterContract.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt

MOB-2858
https://glia.atlassian.net/browse/MOB-2858
During camera capture attachment, the created file was left in the application file structure visible to anyone. Implemented a way to cleanup after file is used to ensure no residual files left over after engagement.

Temporary file cleanup after use during camera capture

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/java/com/glia/exampleapp/VisitorInfoFragment.kt
app/src/main/res/layout/custom_attribute_item.xml
app/src/main/res/layout/main_fragment.xml
app/src/main/res/layout/visitor_info_fragment.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/values/strings.xml

https://glia.atlassian.net/browse/MOB-MOB-2433
The new screen allows viewing, editing, and saving visitor info and custom attributes.
It is the test app feature. It doesn't affect the SDK.

Added Visitor Info screen

---

widgetssdk/src/main/java/com/glia/widgets/core/chathead/ChatHeadManager.java

These changes will prevent the `IllegalStateException: Not allowed to start service ChatHeadService: app is in background` crash. A crash example is [here](https://glia.sentry.io/issues/4599728998/events/2fddaf124e8140beb2bcf286d8efcdea/?project=1887832).
[MOB-2974](https://glia.atlassian.net/browse/MOB-2974)
Crash details are described in the comments to the code. The reason is the same as for [IllegalStateException: for NotificationRemovalService](https://github.com/salemove/android-sdk-widgets/pull/874). However, the fix that I came up with is different. Taking into account two peculiarities:
1. We cannot start `ChatHeadService` before engagement is started or it's not straightforward to do this
2. `ChatHeadService` is attempted to be started once the app is …

Fix IllegalStateException: for ChatHeadService

---

widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java

https://glia.atlassian.net/browse/MOB-2985
Currently, If the Overlay dialog is shown, the Confirmation dialog replaces the Overlay dialog, and that looks not so user-friendly. It’s better to put the Confirmation dialog into a queue until the OverlayDialog is dismissed.

Fix Confirmation Dialog overlaps with Overlay Dialog

---

widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorMediaRepository.java

[MOB-2988](https://glia.atlassian.net/browse/MOB-2988)
**Steps to reproduce:**
1) Start a video session using an Android device
2) Have the agent place the session on hold
3) Have the agent take the session off hold
4) The member will see that audio and video are muted on the device
5) The member clicks to unmute the audio and video on the device
6) The member tries to talk to the agent, the agent will not be able to hear
7) The issue can be fixed by the agent placing the call on hold and then taking the call off of hold again or the member can fix the issue by muting audio and video and then unmuting audio and video
The issue is not reproduced in Davit's [refactoring branch](https://github.com/salemove/android-sdk-widgets/tree/end_engagement_refactoring).
I think the …

Do not mute visitor audio when operator puts engagement on Hold

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt

MOB-2836
https://glia.atlassian.net/browse/MOB-2836
Improved start timer conditions during chat to match the implementation during a video call to prevent IllegalStateException: Task already scheduled or cancelled.

Improved chat start timer conditions to match call controller

---

build.gradle
version.properties
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/LiveObservationPopupUseCase.kt
widgetssdk/src/test/java/com/glia/widgets/view/snackbar/LiveObservationPopupUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-2987
Before LO indication pop-up would show even if LO is disabled in site configurations

Improve LO popup feature flags

---

widgetssdk/src/main/java/com/glia/widgets/view/CharCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_error.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_errorWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_errorWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_errorWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_errorWithUnifiedThemeWithoutVisitorCode.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_loading.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_visitorCode.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_visitorCodeWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_visitorCodeWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_visitorCodeWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_VisitorCodeDialogTest_visitorCodeWithUnifiedThemeWithoutVisitorCode.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/dialog/VisitorCodeDialogTest.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

[MOB-2953](https://glia.atlassian.net/browse/MOB-2953)
Added snapshot tests for visitor code dialog.
Unfortunately, the progress bar is not displayed on the screenshots. Because of this, the Loading state tests do not make a lot of sense. I skiped to add them.
[MOB-2953]: https://glia.atlassian.net/browse/MOB-2953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added snapshot tests for visitor code dialog

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/java/com/glia/exampleapp/VisitorInfoFragment.kt
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.kt
widgetssdk/src/main/java/com/glia/widgets/helper/SimpleTextWatcher.kt

https://glia.atlassian.net/browse/GR-553
Two classes were public and even used in the TestApp even though they are not supposed to be public
Unless integrators were using those undocumented classes this should not affect them

Make SimpleTextWatcher and GliaSdkConfigurations internal

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt

This was referenced during caretaking in this issue https://glia.atlassian.net/browse/SSD-42186
Calling GliaWidgetsConfig from Java classes some values were not able to set due to ambiguous reference error originating from an incomplete Java to Kotlin conversion of a builder class.

Fixed java ambiguous reference error for GliaWidgetsConfig

---

widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/SetEngagementConfigUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

https://glia.atlassian.net/browse/MOB-3035
Will fix cases 3 and 4 from the `Exploratory Testing Session`.
Currently, there is no chance to have a `pending` survey at the point we're trying to reset the `EngagementRepository`.

Remove resetting EngagementRepository from SetEngagementConfigUseCase

---

widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_operatorImageHeader.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_operatorImageHeaderWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_operatorImageHeaderWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_operatorImageHeaderWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_operatorImageHeaderWithUnifiedThemeWithoutOperatorMessage.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withHeader.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withHeaderWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withHeaderWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withHeaderWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withHeaderWithUnifiedThemeWithoutOperatorMessage.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withoutHeader.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withoutHeaderWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withoutHeaderWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withoutHeaderWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_OperatorFileAttachmentViewHolderSnapshotTest_withoutHeaderWithUnifiedThemeWithoutOperatorMessage.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/adapter/holder/OperatorFileAttachmentViewHolderSnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/snapshotutils/SnapshotAttachment.kt

https://glia.atlassian.net/browse/MOB-3023
Added snapshot tests for the Operator File Attachment chat item

Added snapshot tests for the Operator File Attachment chat item

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/helper/ContextExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt

- Fix VisitorCodeView to apply the default XML theme
- Fix getting a runtime theme for non-glia activities

Fix Widgets SDK does not apply the XML theme to the Call Visualizer dialogs

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/helper/ContextExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt

- Fix VisitorCodeView to apply default XML theme
- Fix getting runtime theme for non-glia activities

[Backport] Fix Widgets SDK does not apply the XML theme to the CV dialogs

---

widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/alert/AlertDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewFactory.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/confirmation/ConfirmationDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/operatorendedengagement/OperatorEndedEngagementDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/option/OptionDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/screensharing/ScreenSharingDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/update/UpgradeDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/ThemeWrapper.kt
widgetssdk/src/main/res/layout/screensharing_dialog.xml
widgetssdk/src/main/res/layout/screensharing_dialog_vertical.xml
widgetssdk/src/main/res/values/themes.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withUnifiedTheme.png
widgetssdk/src/testSnapshot/res/values/themes_material.xml

https://glia.atlassian.net/browse/MOB-3067
Fix - Defining `gliaIconScreenSharingDialog` did not affect the screen-sharing dialog icon.

Fix Dialogs don't apply custom icons

---

app/src/main/res/values/themes.xml
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/helper/ContextExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/configuration/ChatHeadConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.kt
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/themes.xml
widgetssdk/src/testSnapshot/java/com/glia/widgets/view/head/ChatHeadViewSnapshotTest.kt

https://glia.atlassian.net/browse/MOB-3038
Fixed the missed support for configurable screen sharing bubble icoon 

Added missing configurability to chathead screen sharing icon

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerActivityWatcher.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/CallVisualizerActivityWatcherTest.kt

https://glia.atlassian.net/browse/MOB-3140

Fix CV confirmation dialog absence when returning from WebBrowser

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/IsAuthenticatedUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

[Save Authentication object with a specified behavior](https://glia.atlassian.net/browse/MOB-3153)
Since we have more than one behavior, it's not okay to hardcode behavior in IsAuthenticatedUseCase now. Let's save `Authentication` object with a specified behavior when an integrator creates it.

Do not hardcode the FORBIDDEN_DURING_ENGAGEMENT behavior in IsAuthenticatedUseCase

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/base/BaseActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/helper/ContextExtensions.kt
widgetssdk/src/test/java/com/glia/widgets/base/BaseSingleActivityWatcherTest.kt

https://glia.atlassian.net/browse/MOB-MOB 3171
There were two issues
- I removed the `noHistory` because it was destroying activity when the application went to the background.
- And added the dismissing dialog logic in case the activity that holds the dialog is destroyed to not leak the `window` and crash the application.

Fix DialogHolder Activity crashes when the app is in the background

---

widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt

Fix screen sharing state doesn’t change after an engagement end

---

widgetssdk/src/main/java/com/glia/widgets/helper/ContextExtensions.kt

https://glia.atlassian.net/browse/MOB-3216
Fixes issue with the Flutter example app which had a similar package name.

Make check for weather activity is part of Widgets SDK stricter

---

widgetssdk/src/main/java/com/glia/widgets/Constants.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatContract.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/FileProviderUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/FixCapturedPictureRotationUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/TakePictureUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/UriToFileAttachmentUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/Files.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterContract.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/messagecenter/MessageCenterControllerTest.kt

https://glia.atlassian.net/browse/MOB-3220
Migrated all the image capture and got content/open document requests to the new activity result api.
- Moved some functions from the Files.kt file to the use cases to make them testable.
- Aligned functionality between Chat and MessageCenter layers.

Migrate all capture image and get content actions to activity result api

---

app/build.gradle
build.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatContract.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/permissions/domain/WithCameraPermissionUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/permissions/domain/WithReadWritePermissionsUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/permissions/domain/WithCameraPermissionUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/permissions/domain/WithReadWritePermissionsUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-3210
Migrate all permission requests in the Chat screen to the activity result API

Migrate all permission requests in Chat screen to activity result api

---

widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/UnifiedUiExtensions.kt

https://glia.atlassian.net/browse/MOB-2843
Fixed narrow font styling on API 24 and lower devices

Fixed narrow font on older devices

---

build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/dialog/PermissionDialogManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/dialog/domain/IsShowEnableCallNotificationChannelDialogUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/permissions/PermissionManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/permissions/domain/HasCallNotificationChannelEnabledUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/permissions/domain/HasScreenSharingNotificationChannelEnabledUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/permissions/domain/NotificationPermissions.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/permissions/domain/IsNotificationPermissionGrantedUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/permissions/domain/RequestNotificationPermissionIfPushNotificationsSetUpUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/messagecenter/MessageCenterControllerTest.kt

https://glia.atlassian.net/browse/MOB-3212
Request notification permission in chat and messaging screens when push notifications are set up
- Chat screen — right before the first engagement request
- Secure messaging — before sending the first message
- Fix warning — Consider using 'tasks.register' to avoid unnecessary configuration

Request notification permission in chat and messaging screens

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/EngagementTypeUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.kt

MOB 3236
https://glia.atlassian.net/browse/MOB-3236
Fix the screen-sharing bubble does not disappear when ending screen-sharing during the Call Visualizer
Steps to reproduce:
1. Start CV
2. Request screen-sharing
3. Accept the screen-sharing request 
4. End screen sharing from the notification
**Expected result:** Bubble should disappear
**Actual result:** Bubble stays on screen until the new screen is shown. 
Fix the screen-sharing bubble does not disappear when ending screen-sharing during the Call Visualizer

Fix CV Screen-sharing bubble stays after end screen-sharing

---

catalog-info.yaml

Backstage now requires the name to be without 'tm-' prefix

Fix catalog-info.yaml owner name

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/core/notification/NotificationFactory.kt
widgetssdk/src/main/java/com/glia/widgets/core/notification/device/NotificationManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/MediaProjectionService.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/MediaProjectionServiceUseCases.kt
widgetssdk/src/main/java/com/glia/widgets/operator/OperatorRequestController.kt
widgetssdk/src/test/java/com/glia/widgets/operator/OperatorRequestControllerTest.kt

https://glia.atlassian.net/browse/MOB-3240
After notification improvements, screen sharing started to be initiated with a huge ~15-second delay.
https://github.com/salemove/android-sdk-widgets/assets/19994238/fd3c1643-6217-48d9-82f5-b8a66cd8d816
As my investigation showed, that was related to the notification channel importance, which was set to a LOW level to prevent the notification from disturbing the user.
**Solution:**
- I returned the notification channel importance to the HIGH level for both call and screen-sharing notification channels.
- Put the `silent` flag to true for those notifications
> If {@code true}, silences this instance of the notification, regardless of the sounds or vibrations set on the notification or notification channel
So …

Fix Screen sharing starts with delay

---

widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/IsDisplayChatHeadUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/helper/DialogHolderActivity.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/ActivityWatcherForChatHead.kt
widgetssdk/src/main/res/values/ids.xml

https://glia.atlassian.net/browse/MOB-3256
I know this is not the best solution for this problem, but to do it more beautifully, a lot of refactoring is needed. So I decided to pick the most straightforward solution.

Fix Bubble pops up in call screen during configuration changes

---

widgetssdk/src/test/java/com/glia/widgets/engagement/completion/EngagementCompletionActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/completion/EngagementCompletionControllerTest.kt

https://glia.atlassian.net/browse/MOB-2990

Add tests for engagement completion layer

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/layout/main_fragment.xml
app/src/main/res/values/strings.xml

[Devs want to update Widgets Testing App with refresh DirectID token possibility](https://glia.atlassian.net/browse/MOB-3274)

Add refresh DirectID token possibility to Widgets Example App

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt

https://glia.atlassian.net/browse/MOB-3294
During the refactoring of dialogs logic, many dialogs are now handled by global watchers and do not require to be handled by views separately. However, the views were still throwing error/debug logs which are confusing.

Fix dialog case handling error in logs

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/ImageAttachmentViewHolder.kt

https://glia.atlassian.net/browse/MOB-3294
ImageAttachmentViewHolder#bind() method tries to
1) load image from cache
1.1) log error if failed
2) if not found load image from local storage
2.1) log error if failed
3) if still not found load image from network link 
3.1) log error if failed
4) log error if all of above attempts failed
I have change 1.1, 2.1 and 3.1 to debug logs instead of errors since error should be throws only if all 3 steps should fail.

Fix expected behavior being sent as an error

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/VisitorMediaUseCase.kt

https://glia.atlassian.net/browse/MOB-3327
It seems that the startWithItem does not work well when called after some map functions. The combined visitor and operator media events can never occur in that case. Added dummy initial state that solves the issue.

Fix: Video views do not appear during a video call

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoView.kt
widgetssdk/src/main/res/layout/visitor_video_floating_view.xml
widgetssdk/src/main/res/values/new_strings.xml

https://glia.atlassian.net/browse/MOB-3293
Added ADA support for the flip camera button

Added ADA support for the flip camera button

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java

Jira issue:
[Improve observations for test case #1 from exploratory testing](https://glia.atlassian.net/browse/MOB-3317)
Since fetch visitor request [can receive an error now](https://github.com/salemove/android-sdk/pull/706), Widgets SDK can clear the state on Chat screen if visitor authentication has changed. Otherwise, Chat screen state is invalid.

Clear the state on Chat screen if visitor authentication has changed

---

widgetssdk/src/main/java/com/glia/widgets/engagement/domain/FlipVisitorCameraUseCase.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt

1. Added logging for an extra case when it isn’t possible to flip the camera in an ordinary way.
2. Updated unit tests according to the new functionality.

Flip camera minor improvements

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/layout/main_fragment.xml
app/src/main/res/values/strings.xml
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/authentication/AuthenticationManager.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

[MOB-3204](https://glia.atlassian.net/browse/MOB-3204)
Build fails because [Core SDK changes](https://github.com/salemove/android-sdk/pull/670) should be released first.
- Add an interface for refreshing visitor access token using direct ID token
- Example App: update Authenticate/De-authenticate button state each time onResume() is called
Add an interface for refreshing visitor access token using direct ID token
[MOB-3204]: https://glia.atlassian.net/browse/MOB-3204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add an interface for refreshing visitor access token using direct ID token

---

widgetssdk/src/main/java/com/glia/widgets/view/head/ActivityWatcherForChatHead.kt

https://glia.atlassian.net/browse/MOB-3387
Fixed the crash on de-authentication.
Made removing the chat head from the UI thread to avoid issues when the removeChatHeadLayoutIfPresent() called from the not UI thread.

Fix thread for remove chat header

---

widgetssdk/src/main/java/com/glia/widgets/core/notification/device/NotificationManager.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java

[Crashes in Glia Android SDK (Monument)](https://glia.atlassian.net/browse/MOB-3358)
In my opinion, call notifications are not needed on Android APIs 31+ (Android 12+) because of the built-in Android [privacy indicators](https://source.android.com/docs/core/permissions/privacy-indicators). 
As a result, there is no need to start `NotificationRemovalService` on 31+ APIs. 
So the following crash should not happen: `Not allowed to start service Intent ... NotificationRemovalService ... app is in background` anymore.
See more details in [Slack](https://salemove.slack.com/archives/CHN6UB7UH/p1718174711873439?thread_ts=1717669165.207099&cid=CHN6UB7UH).
Fix `Not allowed to start service Intent ... NotificationRemovalService ... app is in …

Show call notification only on Android APIs prior to 31

---

build.gradle

This reverts commit 3cc5e3d420165b3217a13c75e2b926f4b2d713c4.
Removes a link to a temporary maven repository added for running acceptance tests before release.

Revert "Add a Maven link for staging Core SDK"

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/DecideOnQueueingUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.kt
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfigurationManager.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/domain/DecideOnQueueingUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-3416
https://glia.atlassian.net/browse/MOB-3405
**The Problem:**
In certain environments, particularly cross-platform ones, the UI can become stuck in the engagement-request state while actually no request is being made.
**The Reason:**
We had different default values for `useOverlays` property, so it was returning different values during initialization steps, as a result to start a queuing we were waiting for the overlay dialog, but in call or chat screen we were receiving `false` and skipping the overlay dialog.
**The Solution**
I left only one default value for the `useOverlays` property inside `GliaSdkConfigurationManager` and move the overlay check from the `DecideOnQueuingUseCase` init block to avoid …

Fix useOverlays property having different values during configuration

---

app/src/main/res/values/strings.xml
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/IsDisplayApplicationChatHeadUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/IsDisplayChatHeadUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/ToggleChatHeadServiceUseCase.kt

This reverts commit 365c7166b409724dc00cc0a4126eae7d46acf055.
[[Android] Fix bubble behavior when overlay flag is disabled](https://glia.atlassian.net/browse/MOB-3281)
There are two reasons to revert:
1. These changes would affect bubble behavior for current integrators
2. These changes are not completely synced between platforms
We decided to step back and think through the changes more thoroughly.
See more in [this](https://salemove.slack.com/archives/CHN6UB7UH/p1713515423754129) thread.

Revert "Change bubble behavior to display it inside client’s mobile application even if bubble overlay flag is disabled"

---

app/src/main/java/com/glia/exampleapp/ChatFragment.java
app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallActivityIntentHelper.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallContract.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallController.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallState.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatContract.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.kt
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaEngagementConfigRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/SetEngagementConfigUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/IsMessageCenterAvailableUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/IsMessagingAvailableUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/SendSecureMessageUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/EnqueueForEngagementUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/domain/EngagementDomainTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/call/SnapshotCallView.kt

https://glia.atlassian.net/browse/MOB-3419
Added the ability to create requests for several queues.
`QUEUE_ID` was deprecated. Added `QUEUE_IDS` parameter, which allows passing a list of queue IDs.

Multiple queues

---

widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/CallVisualizerManager.kt

https://glia.atlassian.net/browse/MOB-1060
Before PR#1060 the company name was not allowed to be null for Call Visualizer engagements. Now, the default company name is "" and setting it up from SDK side is optional since it is expected to be setup in Glia Hub custom locales settings.

Remove company name requirement for CV engagements

---

widgetssdk/src/androidTest/java/com/glia/widgets/CallActivityTest.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/locale/LocaleProvider.kt
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/snapshotutils/SnapshotProviders.kt

There was a problem that the company name specified in SDK configs on `init` was ignored even when no remote was loaded.

Fix hardcoded company name

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepository.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/OnIncomingEngagementRequestTimeoutUseCase.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/CallVisualizerActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/controller/CallVisualizerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt

https://glia.atlassian.net/browse/MOB-3456
The incoming engagement request dialog is dismissed if the request is timeout.

Dismiss CV dialog on timeout

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/CallVisualizerActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/controller/CallVisualizerControllerTest.kt

MOB 3504
https://glia.atlassian.net/browse/MOB-3504
Removed the finish DialogHolderActivity call inside DismissDialog.

Upgrading to video in Call Visualizer does not work

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/ActivityWatcherForLiveObservation.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/SnackBarDelegate.kt
widgetssdk/src/main/res/values/new_strings.xml
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/CallVisualizerActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/controller/CallVisualizerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/view/snackbar/SnackBarDelegateTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/snapshotutils/SnapshotSnackBar.kt

MOB-3495
The Snackbar is displayed to inform visitors if an engagement request is timed out.

Show Snackbar if an engagement request is timed out

---

widgetssdk/src/main/AndroidManifest.xml

https://glia.atlassian.net/browse/MOB-3528
With this noHistory flag, the FilePreview screen will be closed when the app is returned from the background.

Remove no history flag for file preview activity

---

widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/IsDisplayBubbleInsideAppUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/IsDisplayBubbleOutsideAppUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/IsDisplayBubbleUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/DialogHolderActivity.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.kt

[[Android] Fix bubble behavior when overlay flag is disabled](https://glia.atlassian.net/browse/MOB-3281)
- Renamed 3 classes, nothing else

Rename bubble use cases to align the terminology

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatContract.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt

https://glia.atlassian.net/browse/MOB-3524
There was a race condition where sometimes the old instance of ChatView was accessing and destroying the ChatController *after* a newer instance of ChatView had just set up the ChatController (same instance) causing the broken state of ChatController.

Fix chat back button listener race condition

---

widgetssdk/src/main/java/com/glia/widgets/core/notification/domain/CallNotificationUseCase.kt

https://glia.atlassian.net/browse/MOB-3583
This problame consists of multiple parts:
- At the moment it should be impossible to start one-way audio
- Visitor and Operator media states are received from different APIs and are async
- ChatController does not care about visitor media state
As a result, this error is 'expected' so I decided to downgrade it to an info log

Downgrade 'one-way audio calls' error to info

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetFragment.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetView.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetErrorStateViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetMediaTypeItemViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/RemoteConfiguration.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/alert/AlertRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/ChatRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/entrywidget/EntryWidgetRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/entrywidget/MediaTypeItemRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/entrywidget/MediaTypeItemsRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/secureconversations/SecureConversationsRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/webbrowser/WebBrowserRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/UnifiedTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/alert/AlertTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/ChatTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Base.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/EntryWidget.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/WebBrowser.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/entrywidget/EntryWidgetTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/entrywidget/MediaTypeItemTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/entrywidget/MediaTypeItemsTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/secureconversations/SecureConversationsTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/webbrowser/WebBrowserTheme.kt
widgetssdk/src/main/res/layout/entry_widget_error_item.xml

https://glia.atlassian.net/browse/MOB-3591
https://glia.atlassian.net/browse/MOB-3593
Added Unified UI customization support for Entry Widget and Secure Conversations v2

Unified UI customization for Entry Widget and SCv2

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/core/queue/QueueMonitor.kt
widgetssdk/src/main/java/com/glia/widgets/core/queue/domain/FetchQueuesUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/queue/domain/SubscribeToQueueUpdatesUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/queue/domain/UnsubscribeFromQueueUpdatesUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidget.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetContract.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetView.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetItemDecoration.kt

[[Android] Devs want to implement the logic for showing available engagement types](https://glia.atlassian.net/browse/MOB-3411)
- Passing queues specified by integrator OR default queues to QueueMonitoring component
- Queue monitoring component subscribes to queue updates
- Each time queue is updated, the Queue monitoring component notifies the subscriber(s)
- Entry Widget Controller refreshes the available engagement types
**What has to be done?**
- Maybe extract standalone MonitorAvailableEngagementTypes component - separate PR
- Add unit tests - separate PR
- Add logs and align them with iOS (in "Devs want to add logging and telemetry" tickets)
**Screen recording:**
https://github.com/user-attachments/assets/c7031e6f-564a-4d34 …

Devs want to implement the logic for showing available engagement types

---

widgetssdk/src/main/res/values/new_strings.xml

https://glia.atlassian.net/browse/MOB-3615
Texts have changed, updating according to [the Figma designs](https://www.figma.com/design/x5BLxm2UWpm3TuerdqmYi8/Glia-Mobile-App-Pages?node-id=12574-7393&node-type=frame&t=orLGIl8J9voTjKrd-0).

Update Entry Widget texts

---

gradle/libs.versions.toml

https://glia.atlassian.net/browse/MOB-3617
In new version of dokka changes of note:
- Support for @author, @since and @return tags in javadocs
- Significantly improve the mobile layout and overall responsiveness There are other changes also. For details see:
https://github.com/Kotlin/dokka/releases
< - Left side is the old version ===================== Right side is the new version -> 
In most cases however nothing changed and things are still rendered incorrectly
P.S: Most things however haven't changed and it seems that @Depricated tag is still rendered incorrectly or not rendered at all

Upgrade Dokka to latest version

---

widgetssdk/src/main/java/com/glia/widgets/view/header/AppBarView.kt

https://glia.atlassian.net/browse/MOB-3619
For some reason, AppBar.backgroundTintList doesn't work properly for custom XML themes, so I replaced it with `AppBar.setBackground`.

Fix ToolBar disappears when using custom XML theme

---

widgetssdk/src/main/res/layout/entry_widget_media_type_item.xml

Add gliaBrandPrimaryColor tint to entry widget icon tint.

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java

[MOB-3408](https://glia.atlassian.net/browse/MOB-3408)
According to requirements:
> Integrators can launch the Entry Widget view after the SDK setup. If SDK hasn’t been initialized or was initialized with an error - Widgets SDK should not crash, it should show an Entry Widget with an error state.
- Send an error event if Glia is not initialized before getting an Entry Widget
- Setup queues each time get Entry Widget is called
[MOB-3408]: https://glia.atlassian.net/browse/MOB-3408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Send error event if Glia is not initialized before getting an Entry Widget

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetView.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetAdapter.kt

https://glia.atlassian.net/browse/MOB-3642
Enabled scrolling for the Entry Widget bottom sheet content.
https://github.com/user-attachments/assets/a0b936ef-1267-4507-aaf0-8f01c067496f

Entry Widget bottom sheet scrolling

---

widgetssdk/src/main/res/layout/entry_widget_error_item.xml

[MOB-3478](https://glia.atlassian.net/browse/MOB-3478)
- Change 'Try again' button style for Entry Widget error state according to design
[MOB-3478]: https://glia.atlassian.net/browse/MOB-3478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change 'Try again' button style for Entry Widget error state according to design

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/ConfigurationManager.kt

[MOB-3657](https://glia.atlassian.net/browse/MOB-3657)
1. Fixed the issue: enabled "Default Queues" toggle in Example App ends up with an empty Entry Widget state instead of a list of engagement types for default queues
2. Work with default queues if an integrator passes an empty queue list (the same as if null is passed)
[MOB-3657]: https://glia.atlassian.net/browse/MOB-3657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pass null instead of an empty list if "Default Queues" toggle is enabled in Example App settings

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt

[MOB-3659](https://glia.atlassian.net/browse/MOB-3659)
- Hide 'Secure Messaging' engagement type from Entry Widget if visitor is not authenticated
https://github.com/user-attachments/assets/b7aeba7c-8ca1-4283-9e05-9a336622ce61
[MOB-3659]: https://glia.atlassian.net/browse/MOB-3659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hide 'Secure Messaging' engagement type from Entry Widget if visitor is not authenticated

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java

[MOB-3657](https://glia.atlassian.net/browse/MOB-3657)
Based on the [discussion](https://salemove.slack.com/archives/C07DM3JD8R1/p1728642904648499).
- Make queueIds list non-nullable, so only empty list means that default queues should be used
[MOB-3657]: https://glia.atlassian.net/browse/MOB-3657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make queueIds list non-nullable, so only empty list means that default queues should be used

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetMediaTypeItemViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/entrywidget/MediaTypeItemRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/EntryWidget.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/entrywidget/MediaTypeItemTheme.kt
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetViewBottomSheetTypeTest_contactsWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetViewBottomSheetTypeTest_contactsWithUnifiedThemeWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetViewBottomSheetTypeTest_loadingWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetViewBottomSheetTypeTest_loadingWithUnifiedThemeWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetViewEmbeddedViewTypeTest_contactsWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetViewEmbeddedViewTypeTest_contactsWithUnifiedThemeWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetViewEmbeddedViewTypeTest_loadingWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetViewEmbeddedViewTypeTest_loadingWithUnifiedThemeWithGlobalColors.png
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

https://glia.atlassian.net/browse/MOB-3591
Added loading tint color customization for the Entry Widget

Added loading tint color customization

---

gradle/libs.versions.toml

https://glia.atlassian.net/browse/MOB-3661
This change is directly related to changes in Core SDK regarding OkHttp version. 
See https://github.com/salemove/android-sdk/pull/763

Update Kotlin version to match Core SDK

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/core/queue/QueueRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/IsMessagingAvailableUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/ConfigurationManager.kt
widgetssdk/src/test/java/com/glia/widgets/core/queue/QueueRepositoryTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/IsMessagingAvailableUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-3673
- Always fallback to default queues when integrator queues are empty or don't match
- Fix tests
- Add additional Logs.

Devs want to always fallback to default queues

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaSendMessageUseCase.kt

https://glia.atlassian.net/browse/MOB-3664
https://github.com/user-attachments/assets/cc791fef-0324-4b41-a68c-58e8071e9a69
https://github.com/user-attachments/assets/b3da1f36-2e9a-4303-93b5-231094efa8c4
Visitor messages will appear immediately after the send button is clicked.

Fix! Messages are not added to the chat immediately after input

---

app/src/main/res/values/themes.xml
widgetssdk/src/main/java/com/glia/widgets/chat/data/GliaChatRepository.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaLoadHistoryUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/queue/QueueRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepository.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/States.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/EnqueueForEngagementUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/queue/QueueRepositoryTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/completion/EngagementCompletionControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/domain/EngagementDomainTest.kt
widgetssdk/src/test/java/com/glia/widgets/view/head/ActivityWatcherForChatHeadTest.kt

https://glia.atlassian.net/browse/MOB-3698
In my previous change, I didn't consider that, in some circumstances, we're requesting relevant queues before we receive the site queues from the server. Therefore, I made everything reactive, improved readability and added an initialization check in EntryWidgetController to show an `Error` state immediately if the SDK is not initialized.

Refactor queue management to avoid race conditions

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidget.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetContract.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetView.kt

- [Implement Entry Widget item click navigation](https://glia.atlassian.net/browse/MOB-3702)
- [Make changes to the getView() interface based on the discussions](https://glia.atlassian.net/browse/MOB-3694)
https://github.com/user-attachments/assets/005915c1-ab30-414b-b4fc-200b65c15335

Implement Entry Widget item click navigation

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidget.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetActivity.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetFragment.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetHideController.kt

[[Android] Devs want to add interfaces to show/hide the Entry Widget](https://glia.atlassian.net/browse/MOB-3408)
Implemented the `hide()` interface. To avoid asking for an Activity from the integrator, `ActivityWatcher` solution is used.

Implement the hide() interface

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidget.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetContract.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetFragment.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetErrorStateViewHolder.kt
widgetssdk/src/test/java/com/glia/widgets/entrywidget/EntryWidgetControllerTest.kt
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetBottomSheetTest_errorDefaultThemeGliaNotInitialized.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetBottomSheetTest_sdkNotInitializedItemsDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetBottomSheetTest_sdkNotInitializedItemsWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetBottomSheetTest_sdkNotInitializedItemsWithUnifiedThemeWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetBottomSheetTest_sdkNotInitializedItemsWithUnifiedThemeWithoutEntryWidget.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetEmbeddedViewTest_errorDefaultThemeGliaNotInitialized.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetEmbeddedViewTest_sdkNotInitializedItemsDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetEmbeddedViewTest_sdkNotInitializedItemsWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetEmbeddedViewTest_sdkNotInitializedItemsWithUnifiedThemeWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetEmbeddedViewTest_sdkNotInitializedItemsWithUnifiedThemeWithoutEntryWidget.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/entrywidget/EntryWidgetEmbeddedViewTest.kt

- [Entry Widget should show an empty state if only 'messaging' engagement is available but visitor is not authenticated](https://glia.atlassian.net/browse/MOB-3712)
- [Hide the 'Try Again' button if SDK is not initialized](https://glia.atlassian.net/browse/MOB-3728)
- Added snapshot tests for the case when Glia is not initialized and we should hide the 'Try again' button
https://github.com/user-attachments/assets/1b9e9b02-a0c6-49ac-897c-b09f91a0b73a

Handle edge cases

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/main/res/values/new_strings.xml
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessaging.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithUnifiedThemeWithoutChat.png
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

https://glia.atlassian.net/browse/MOB-3633

Implement bottom banner for secure conversation

---

widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidget.kt

https://glia.atlassian.net/browse/MOB-3650
Add secure conversation business logic into the entry widget public functions

Add SC business logic into Entry Widget public functions

---

widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/EngagementLauncher.kt

https://glia.atlassian.net/browse/MOB-3758

Add business logic into EngagementLauncher.startSecureMessaging

---

widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/GetUnreadMessagesCountWithTimeoutUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/HasPendingSecureConversationsWithTimeoutUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidget.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/GetUnreadMessagesCountWithTimeoutUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/HasPendingSecureConversationsWithTimeoutUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-3761
Added initialization and authentication checks for the SC `getUnreadMessagesCound()` and `hasSecureConversations()` inside their use cases to prevent crashes in the Entry Widget.

Make SC APIs work seamlessly when sdk is not initialized

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/UnifiedUiExtensions.kt
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/main/res/values/new_strings.xml
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingUnavailable.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingUnavailableWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingUnavailableWithUnifiedTheme.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/ChatViewSnapshotTest.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

https://glia.atlassian.net/browse/MOB-3635
Previously, we showed an Alert Dialog that said that secure messaging was unavailable, but now it should be a label above the chat EditText view.
- There have been slight differences in chat view snapshots because of the height of the visitor message edit text view. But that is related to constrained layout rules changes when implementing secure conversations unavailable label. Was not able to fix it...
- Will implement the 'disabled' color state to the message EditText view and attachment/send buttons in separate PR

Add secure messaging unavailable label

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/CallVisualizerManager.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/ConfigurationManager.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/EngagementLauncher.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt
widgetssdk/src/test/java/com/glia/widgets/launcher/EngagementLauncherTest.kt

[MOB-3752](https://glia.atlassian.net/browse/MOB-3752)
- Add ability to pass visitor context id through Engagement Launcher
[MOB-3752]: https://glia.atlassian.net/browse/MOB-3752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ability to pass visitor context id through Engagement Launcher

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt

https://glia.atlassian.net/browse/MOB-3784
Show the Entry Widget items in order according to the design

Show the Entry Widget items in correct order

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetContract.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetView.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetLiveItemViewHolder.kt
widgetssdk/src/main/res/drawable/bg_entry_widget_divider.xml
widgetssdk/src/main/res/layout/entry_widget_live_item.xml
widgetssdk/src/test/java/com/glia/widgets/entrywidget/EntryWidgetControllerTest.kt

https://glia.atlassian.net/browse/MOB-3639
Made UI changes for EntryWidgetsView to correctly render as secure messaging top banner options:
- smaller padding between media items
- removed white label
- made divider match screen width
Currently, the new view type is not used anywhere but here is how it would look:
Here are screenshots for the old view type (in this case it is BOTTOM_SHEET).
Posting it to show that it is unchanged

Update EntryWidgetsView to support MESSAGING_LIVE_SUPPORT flag

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/VisitorMessageViewHolder.kt
widgetssdk/src/main/res/layout/chat_visitor_message_layout.xml

https://glia.atlassian.net/browse/MOB-3797

Fix Click on visitor message works from 2nd attempt during tap to retry

---

build.gradle
version.properties
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/test/java/com/glia/widgets/entrywidget/EntryWidgetControllerTest.kt

[MOB-3810](https://glia.atlassian.net/browse/MOB-3810)
Scenario:
- show embedded view before Glia is initialized (error state is shown)
- init Glia
**Actual result:** Entry Widget still shows an error state
**Expected result:** error state is replaced with loading state and data state afterwards
[MOB-3810]: https://glia.atlassian.net/browse/MOB-3810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refresh Entry Widget on Glia init

---

build.gradle

- no ticket -
The old staging version of Core SDK got automatically deleted for some reason.
Discussion in slack:
https://salemove.slack.com/archives/C01F9K88SQZ/p1732545132319779?thread_ts=1732527166.629109&cid=C01F9K88SQZ

Update Core SDK staging repo url

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetFragment.kt

[[Android] SDK crashes on Entry Widget item tap](https://glia.atlassian.net/browse/MOB-3845)
Crash reason is [here](https://github.com/salemove/android-sdk-widgets/pull/1169/files#diff-4f29a0397380e2017630aae072bd897cc65374955c607c104dfddcff4bfb6cadR63-R69).
`dismiss()` was called recursively.

Prevent recursive dismiss() call

---

build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/AttachmentPopup.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/SnackBarDelegate.kt
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/test/java/com/glia/widgets/view/snackbar/SnackBarDelegateTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/AttachmentPopupSnapshotTest.kt

https://glia.atlassian.net/browse/MOB-3844
Fix the send and attachment buttons overlaping.
A side effect of making the layout flat is that now those buttons have slight animation.
[Screen_recording_20241202_131317.webm](https://github.com/user-attachments/assets/a974c86b-c4fe-48be-a4a8-7ccdbb81550c)

Fix send and attachment buttons overlap

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/EngagementLauncher.kt

1. [[Android] Developers want to log the 'Canceling ongoing queue ticket to create a new one' event](https://glia.atlassian.net/browse/MOB-3910)
2. [[Android] Developers want to log the 'Preparing items based on ongoing engagement' event for Entry Widget](https://glia.atlassian.net/browse/MOB-3911)

Log additional events for an Entry Widget and Engagement Launcher

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepository.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/IsQueueingOrLiveEngagementUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/EngagementLauncher.kt
widgetssdk/src/test/java/com/glia/widgets/launcher/EngagementLauncherTest.kt

[[Android] Do not cancel queue ticket if visitor selects engagement of the same type during queueing](https://glia.atlassian.net/browse/MOB-3930)
1. Do not cancel queue ticket if visitor selects engagement of the same type during queueing
2. Prevent showing multiple "queueing' items with animation if Chat screen is launched through `EngagementLauncher` during queueing

Do not cancel queue ticket if visitor selects engagement of the same type during queueing

---

build.gradle
widgetssdk/src/main/java/com/glia/widgets/call/CallController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/VisitorCodeController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.kt
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/MediaProjectionService.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/States.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/completion/EngagementCompletionActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/completion/EngagementCompletionController.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/completion/EngagementCompletionState.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ActivityWatcherForChatHeadController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/ActivityWatcherForLiveObservationController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/controller/CallVisualizerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/controller/VisitorCodeControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/HasOngoingSecureConversationUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/completion/EngagementCompletionActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/completion/EngagementCompletionControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/entrywidget/EntryWidgetControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/view/head/ActivityWatcherForChatHeadTest.kt

https://glia.atlassian.net/browse/MOB-3942

MOB 3942: Implement engagement 'on_end' functionality

---

widgetssdk/src/main/java/com/glia/widgets/engagement/completion/EngagementCompletionActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/completion/EngagementCompletionController.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/completion/EngagementCompletionState.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/completion/EngagementCompletionActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/completion/EngagementCompletionControllerTest.kt

https://glia.atlassian.net/browse/MOB-3975

Fix chat screen is getting stuck after Visitor ends engagement

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/MarkMessagesReadWithDelayUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/ShouldMarkMessagesReadUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ManagerFactory.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepository.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/test/java/com/glia/widgets/chat/ChatManagerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/ShouldMarkMessagesReadUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt

https://glia.atlassian.net/browse/MOB-3954
New messages should be marked as read when:
- We have new messages when the history loaded after a visitor opened the chat (transcript) screen or a visitor gets a new SC or Live Engagement message from an Operator; and
- There are no ongoing engagements or an ongoing engagement on_end equals retain; and
- The visitor has stayed on the chat (transcript) screen for at least 6 seconds after the new message; and
- The leave current SC dialog has not shown for at least 6 seconds after the new message.

Improve the mark messages as read logic

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/core/queue/QueueRepository.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/DeviceMonitor.kt
widgetssdk/src/test/java/com/glia/widgets/core/queue/QueueRepositoryTest.kt

https://glia.atlassian.net/browse/MOB-4052
Added monitoring for internet connection and device unlock.
The queue repository will re-fetch queues each time the device is unlocked or the internet connection is restored.

Fix the auto updating entry widget fails after being on background

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/test/java/com/glia/widgets/entrywidget/EntryWidgetControllerTest.kt

https://glia.atlassian.net/browse/MOB-4057

Fix Empty State Screen is shown instead of Error State Screen

---

widgetssdk/src/main/java/com/glia/widgets/view/MessagesNotSeenHandler.java
widgetssdk/src/test/java/com/glia/widgets/view/MessagesNotSeenHandlerTest.kt

[[Android] Unread message count is NOT displayed on bubble in a specific test case](https://glia.atlassian.net/browse/MOB-4055)
Test case:
1. Authenticate
2. Open secure conversations and send a message
3. Close Glia SDK, return to integrator app and authenticate
4. Operator picks up (bubble is shown)
5. Operator sends a message
Actual result without these changes: unread message badge IS NOT SHOWN on bubble
Actual result with the changes: unread message badge IS SHOWN on bubble

Show unread message badge if visitor is on non-Glia screen, engagement starts and bubble is shown

---

widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt

https://glia.atlassian.net/browse/MOB-4060

Operator typing status remains after engagement ended

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt

- [MOB-3003](https://glia.atlassian.net/browse/MOB-3003)
- [MOB-3281](https://glia.atlassian.net/browse/MOB-3281)
- Remove deprecated setUseOverlay interface. We have it mentioned in Widgets SDK 3.0.0 migration guide
It's already there. But I'll ask tech the writer to add to the table a new interface that should be used instead.
[MOB-3003]: https://glia.atlassian.net/browse/MOB-3003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-3281]: https://glia.atlassian.net/browse/MOB-3281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove deprecated setUseOverlay interface

---

widgetssdk/src/main/java/com/glia/widgets/core/notification/device/NotificationManager.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt

https://glia.atlassian.net/browse/MOB-4011
We were not able to reproduce the issue which was reported by the client. However, theoretically Lifecycle.Event.ON_STOP might be called when the app is in the background causing the error 'IllegalStateException: Not allowed to start service app is in the background' but in case of Lifecycle.Event.ON_PAUSE app can't be in the background state.

Fix IllegalStateException when starting NotificationRemovalService

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt

- A tiny thing that I noticed - there's an extra `Authentication` creation right below the same code in the example. I believe it's a mistake.

Remove duplicate Authentication creation from the example app

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/glia/exampleapp/Application.java
app/src/main/java/com/glia/exampleapp/InitializationProvider.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt
widgetssdk/src/main/java/com/glia/widgets/InitializationProvider.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsTest.kt

https://glia.atlassian.net/browse/MOB-4198
Widgets SDK doesn't call Core SDK `.onAppCreate()` method.
Added the `InitializationProvider`. The provider can be used to call `GliaWidgets.onAppCreate()`. A custom application class in the application or library is not necessary anymore.
- [?] Ignore
- [?] Release notes (Is it clear from the description here?)
- [?] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

Do not call Core SDK onAppCreate() method

---

app/src/main/java/com/glia/exampleapp/VisitorInfoFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/VisitorInfo.kt
widgetssdk/src/main/java/com/glia/widgets/core/visitor/VisitorInfoUpdateRequest.kt

[Add getVisitorInfo() to Android Widgets SDK](https://glia.atlassian.net/browse/MOB-4203)
[Add updateVisitorInfo() to Android Widgets SDK](https://glia.atlassian.net/browse/MOB-4204)
1. Added public `GliaWidgets.getVisitorInfo(callback)`
2. Added public `GliaWidgets.updateVisitorInfo(visitorInfo)`
3. Added public `VisitorInfo` class
4. Added public `VisitorInfoUpdateRequest` class
5. Integrators who use `Glia.getVisitorInfo()` and `Glia.updateVisitorInfo()` Core SDK interfaces can still use them and do not need to change anything until we hide Core SDK.
Something general once [MOB-4169](https://glia.atlassian.net/browse/MOB-4169) is done.
[MOB-4169]: https://glia.atlassian.net/browse/MOB-4169?atlOrigin=eyJpIjoiNWR …

Add getVisitorInfo() and updateVisitorInfo() to Android Widgets SDK

---

app/src/main/java/com/glia/exampleapp/Application.java

Just revert the quick fix changes.

Revert "Quick fix for onAppCreate()"

---

scripts/direct-core.gradle

https://glia.atlassian.net/browse/MOB-4275
Do not log in if the Quiet mode is on for Gradle tasks.

Fix Gradle script logging in the Quiet mode

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/java/com/glia/exampleapp/Utils.java
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/core/authentication/AuthenticationManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/visitor/Authentication.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsExceptionTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/authentication/AuthenticationManagerTest.kt

[Add Authentication class to Android Widgets SDK](https://glia.atlassian.net/browse/MOB-4206)
- Added own Authentication class to Widgets SDK
- Added own Behavior enum Widgets SDK
- Made sure the current approach through Core SDK classes is working without any changes
Something general once [MOB-4169](https://glia.atlassian.net/browse/MOB-4169) is done.
[MOB-4169]: https://glia.atlassian.net/browse/MOB-4169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Authentication class to Android Widgets SDK

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsTest.kt
widgetssdk/src/test/java/com/glia/widgets/di/DependenciesTest.kt

- [Add callback to GliaWidgets.init() so that integrators could know when SDK init finishes](https://glia.atlassian.net/browse/MOB-4273)
- [Add GliaWidgets.isInitialized() to Android Widgets SDK](https://glia.atlassian.net/browse/MOB-4211)
- [In progress] I will review the unit tests
These changes rely on [this Core SDK PR](https://github.com/salemove/android-sdk/pull/813).
Add callback to GliaWidgets.init() so that integrators could know when SDK init finishes

Add callback to GliaWidgets.init() so that integrators could know when SDK init finishes

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt

[MOB-4268](https://glia.atlassian.net/browse/MOB-4268)
Annotate GliaWidgets functions and params with JvmStatic
[MOB-4268]: https://glia.atlassian.net/browse/MOB-4268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Annotate GliaWidgets functions and params with JvmStatic

---

app/src/main/AndroidManifest.xml
scripts/publish-module.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/fcm/GliaFcmService.kt

https://glia.atlassian.net/browse/MOB-4207
GliaFcmService was added to Android Widgets SDK

Add GliaFcmService to Android Widgets SDK

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversations.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt

[MOB-4214](https://glia.atlassian.net/browse/MOB-4214), [MOB-4215](https://glia.atlassian.net/browse/MOB-4215), [MOB-4216](https://glia.atlassian.net/browse/MOB-4216)
- Add Secure Conversations interfaces for unread message count
Something general once [MOB-4169](https://glia.atlassian.net/browse/MOB-4169) is done.
[MOB-4214]: https://glia.atlassian.net/browse/MOB-4214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-4215]: https://glia.atlassian.net/browse/MOB-4215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-4216]: https://glia.atlassian.net/browse/MOB-4216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

Add Secure Conversations interfaces for unread message count

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/fcm/GliaPushMessage.kt
widgetssdk/src/main/java/com/glia/widgets/fcm/PushNotifications.kt
widgetssdk/src/test/java/com/glia/widgets/fcm/GliaPushMessageTest.kt

https://glia.atlassian.net/browse/MOB-4232
Add GliaWidgets.getPushNotifications().handleOnMainActivityCreate() method.

Add getPushNotifications().handleOnMainActivityCreate()

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/core/liveobservation/LiveObservation.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt

[Add getLiveObservation().pause() and getLiveObservation().resume() to Android Widgets SDK](https://glia.atlassian.net/browse/MOB-4210)
Something general once [MOB-4169](https://glia.atlassian.net/browse/MOB-4169) is done.
[MOB-4169]: https://glia.atlassian.net/browse/MOB-4169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add LiveObservation interfaces

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/layout/main_fragment.xml
app/src/main/res/menu/menu_main_fragment.xml
app/src/main/res/values/strings.xml

https://glia.atlassian.net/browse/MOB-4321
https://github.com/user-attachments/assets/02b257ef-1df0-4e65-8849-4a4e1dc3fe3f
For the API versions that not require PN permission, the subtitle will show that the PN is not required.
https://github.com/user-attachments/assets/02a2eaf5-1dc3-413d-8bef-805fea3e3c68

Add button to request PN permission in testing app

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt
widgetssdk/src/main/java/com/glia/widgets/SiteApiKey.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsTest.kt
widgetssdk/src/test/java/com/glia/widgets/SiteApiKeyTest.kt

https://glia.atlassian.net/browse/MOB-4212
Add public class for SiteApiKey to Android Widgets SDK

Add public class for SiteApiKey to Android Widgets SDK

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/authentication/Authentication.kt
widgetssdk/src/main/java/com/glia/widgets/internal/authentication/AuthenticationManager.kt
widgetssdk/src/test/java/com/glia/widgets/internal/authentication/AuthenticationManagerTest.kt

https://glia.atlassian.net/browse/MOB-4331
Use the Widgets type of `Authentication.Behavior` for the Widgets `Authentication.setBehavior()`.
Returns the Core type of `Authentication` for the deprecated `GliaWidgets.getAuthentication.getAuthentication()` method.

Fix Authentication interfaces

---

widgetssdk/src/main/java/com/glia/widgets/fcm/PushNotifications.kt

It no longer needs to call the `GliaWidgets.getPushNotifications().handleOnMainActivityCreate(bundle)`. Handling will be implemented on the `ActivityWatcher`.
The method will not be introduced for integrators to simplify SDK usage.

Remove handleOnMainActivityCreate from Widgets

---

widgetssdk/src/main/java/com/glia/widgets/visitor/VisitorInfoUpdateRequest.kt

https://glia.atlassian.net/browse/MOB-4343
Add default values,
Make the ability to use setters.
Now it is possible to use it like this:
```java
VisitorInfoUpdateRequest visitorInfoUpdateRequest = new VisitorInfoUpdateRequest();
visitorInfoUpdateRequest.setName("John Smith");
visitorInfoUpdateRequest.setEmail("john.smith@example.com");
```
instead of this:
```java
VisitorInfoUpdateRequest visitorInformation = new VisitorInfoUpdateRequest(
"John Smith",
"john.smith@example.com",
null, // phone
null, // note
null, // noteUpdateMethod
null, // customAttributes
null // customAttrsUpdateMethod
);
```
For Kotlin, there are also improvements. No need to pass all parameters to the constructor.
```kotlin
val visitorInformation = VisitorInfoUpdateRequest(
name = …
```

Improve VisitorInfoUpdateRequest

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsException.kt
widgetssdk/src/main/java/com/glia/widgets/authentication/Authentication.kt
widgetssdk/src/main/java/com/glia/widgets/callbacks/OnComplete.kt
widgetssdk/src/main/java/com/glia/widgets/callbacks/OnError.kt
widgetssdk/src/main/java/com/glia/widgets/callbacks/OnSuccess.kt
widgetssdk/src/main/java/com/glia/widgets/internal/authentication/AuthenticationManager.kt
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsExceptionTest.kt
widgetssdk/src/test/java/com/glia/widgets/internal/authentication/AuthenticationManagerTest.kt

https://glia.atlassian.net/browse/MOB-4344
Made `OnSuccess`, `OnError` and `GliaWidgetsException` not optional.
Result always returns value.

Improve OnSuccess, OnError and GliaWidgetsException

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsException.kt
widgetssdk/src/main/java/com/glia/widgets/secureconversations/SecureConversations.kt
widgetssdk/src/test/java/com/glia/widgets/secureconversations/SecureConversationsImplTest.kt

[MOB-4346](https://glia.atlassian.net/browse/MOB-4346)
- Replace RequestCallback with Widgets callbacks in Secure Conversation interfaces
[MOB-4346]: https://glia.atlassian.net/browse/MOB-4346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Replace RequestCallback with Widgets callbacks in Secure Conversation interfaces

---

app/src/main/java/com/glia/exampleapp/VisitorInfoFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/callbacks/OnResult.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/States.kt
widgetssdk/src/main/java/com/glia/widgets/secureconversations/SecureConversations.kt
widgetssdk/src/test/java/com/glia/widgets/secureconversations/SecureConversationsImplTest.kt

[Add public classes for Core SDK GliaException and RequestCallback to Android Widgets SDK](https://glia.atlassian.net/browse/MOB-4213)
It's a result of [this discussion](https://github.com/salemove/android-sdk-widgets/pull/1300#discussion_r2086525822).

Rename OnSuccess callback to OnResult

---

app/src/main/res/raw/sample_unified_config.json
widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/alert/AlertDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewFactory.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/confirmation/ConfirmationDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/operatorendedengagement/OperatorEndedEngagementDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/option/OptionDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/screensharing/ScreenSharingDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/update/UpgradeDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/UnifiedUiExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/RemoteConfiguration.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/ThemeWrapper.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/UnifiedTheme.kt

https://glia.atlassian.net/browse/MOB-4333
Add `isWhiteLabel` property to the `UnifiedUI`

Add isWhiteLabel property to the UnifiedUI

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt

Deprecate Screen Sharing.
Mark the GliaWidgetsConfig.Builder.setScreenSharingMode() as deprecated.

Deprecate Screen Sharing

---

app/src/main/java/com/glia/exampleapp/VisitorInfoFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/authentication/Authentication.kt
widgetssdk/src/main/java/com/glia/widgets/callbacks/OnComplete.kt
widgetssdk/src/main/java/com/glia/widgets/callbacks/OnError.kt
widgetssdk/src/main/java/com/glia/widgets/internal/authentication/AuthenticationManager.kt
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsTest.kt
widgetssdk/src/test/java/com/glia/widgets/internal/authentication/AuthenticationManagerTest.kt

https://glia.atlassian.net/browse/MOB-4355
The idea is to make the interface more convenient for integrators. Callbacks are divided into 3 types:
- Result callbacks not nullable (OnComplete, OnResult). Integrators will always have result.
- OnError callbacks nullable for getters (getQueues, getVisitorInfo, getUnreadMessageCount, etc). In case integrators need the result, but don't want to handle the errors.
- make the OnError callback not nullable for methods that update something or perform some action (init, updateVisitorInfo, etc). Important actions should always be handled.

Refactor callbacks

---

app/src/main/AndroidManifest.xml
widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/InitializationProvider.kt

https://glia.atlassian.net/browse/MOB-4363
- Add the InitializationProvider to the SDK manifest.
- Check if RxJava error handler is already set.
**What was solved? (Ignore Release notes)**
- Make onAppCreate as JvmStatic.

Deprecate onAppCreate method

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ActivityWatcherForChatHeadController.kt
widgetssdk/src/test/java/com/glia/widgets/GliaWidgetsTest.kt

[MOB-4359](https://glia.atlassian.net/browse/MOB-4359)
**One of the affected scenarios:**
1. Open the app, don’t initialize the SDK yet
2. Show embedded Entry Widget, error state is shown
3. Initialize the SDK 
**Expected result:** Entry Widget switches to the loading state and after queues are loaded, shows available types.
**Actual result:** error state is still shown
**The reason:**
`fun init(gliaWidgetsConfig: GliaWidgetsConfig)` calls `onSdkInit(gliaWidgetsConfig)` and after that sets `glia().isInitialized` to `true`. However, `onSdkInit` calls `repositoryFactory.initialize()` which initializes `QueueRepository`. `QueueRepository` has `forceFetchQueues()` function that relies on `gliaCore.isInitializedvalue`. So, the sequence of actions is broken. …

Introduce a separate isInitialized Boolean to GliaWidgets instead of glia().isInitialized

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidget.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetFragment.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetView.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/entrywidget/EntryWidgetBottomSheetTest.kt

https://glia.atlassian.net/browse/MOB-4377
Use the UnifiedTheme whiteLabel for the EntryWidget

Use the UnifiedTheme whiteLabel for the EntryWidget

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/secureconversations/SecureConversations.kt
widgetssdk/src/test/java/com/glia/widgets/secureconversations/SecureConversationsImplTest.kt

[MOB-4373](https://glia.atlassian.net/browse/MOB-4373)
1. Remove `getUnreadMessageCount()` from `SecureConversations`, see [this message](https://salemove.slack.com/archives/C08H43U2DAB/p1747749067843349).
2. Explain that SecureConversations.getUnreadMessageCount() counts only SC messages and doesn't count unread live chat messages
3. Handle the SDK not initialized case in the example app for the case when EngagementLauncher is called without visitor context
[MOB-4373]: https://glia.atlassian.net/browse/MOB-4373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove getUnreadMessageCount() from SecureConversations

---

app/src/main/java/com/glia/exampleapp/VisitorInfoFragment.kt
widgetssdk/src/main/java/com/glia/widgets/visitor/VisitorInfo.kt

[MOB-4169](https://glia.atlassian.net/browse/MOB-4169)
- Rename 'customAttributesMap' to 'customAttributes' in VisitorInfo to align with VisitorInfoUpdateRequest
[MOB-4169]: https://glia.atlassian.net/browse/MOB-4169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rename 'customAttributesMap' to 'customAttributes' in VisitorInfo to align with VisitorInfoUpdateRequest

---

widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/internal/secureconversations/domain/IsMessagingAvailableUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/queue/Queue.kt
widgetssdk/src/test/java/com/glia/widgets/helper/SupportedMediaTypesTest.kt
widgetssdk/src/test/java/com/glia/widgets/internal/secureconversations/domain/IsMessagingAvailableUseCaseTest.kt

Rename `medias` to `media`.
"Media" is a correct form for plural.

Rename medias to media

---

app/src/main/java/com/glia/exampleapp/VisitorInfoFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt

[Avoid receiving crash reports for non SDK issues in Sentry](https://glia.atlassian.net/browse/MOB-4406
- Show an error Toast in VisitorInfoFragment from UI thread to avoid a crash: java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
- [Just an improvement] Surround the gliaCore().getVisitorInfo(callback) call in GliaWidgets with try-catch similar to the other calls

Show an error Toast in VisitorInfoFragment from UI thread to avoid a crash

---

widgetssdk/src/main/res/values/donottranslate.xml
widgetssdk/src/main/res/values/strings.xml

After discussing this topic during a meeting, we agreed that channels should not have the  words 'notification' or 'channel' in them since it is already clear from context, and that it should be in the plural form
Last screenshot from the discussion:
How it looks now:

Update push notification channel names

---

widgetssdk/src/main/res/values/attrs.xml

Following up the [Add WhiteLabel property to the UnifiedUI](https://glia.atlassian.net/browse/MOB-4333)
- Deprecation notice will be shown in an info pop-up to the `whiteLabel` attribute (see screenshot).

Deprecate 'whiteLabel' attribute in xml theme

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.kt
widgetssdk/src/main/java/com/glia/widgets/authentication/Authentication.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/internal/authentication/AuthenticationManager.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/PushClickHandlerController.kt
widgetssdk/src/test/java/android/TestExtensions.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt
widgetssdk/src/test/java/com/glia/widgets/internal/authentication/AuthenticationManagerTest.kt
widgetssdk/src/test/java/com/glia/widgets/internal/authentication/AuthenticationManagerToCoreTypeTest.kt
widgetssdk/src/test/java/com/glia/widgets/push/notifications/PushClickHandlerControllerTest.kt

https://glia.atlassian.net/browse/MOB-4431
According to [documentation](https://docs.glia.com/glia-mobile/docs/ios-authentication#end-ongoing-engagement) for authentication, when the authentication behavior is `ALLOWED_DURING_ENGAGEMENT`, the engagement ends after the visitor becomes deauthenticated.
But widgets ends engagement regardless of behvaior type.
❗ Will add test for AuthManager in next commit.

Fix engagement end during de-authentication

---

widgetssdk/src/main/java/com/glia/widgets/helper/IntentHelper.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/PushClickHandlerActivity.kt

https://glia.atlassian.net/browse/MOB-4440
Remove flags for the Secure Push Notifications to not clear an application activity stack or state when a notification is clicked.

Fix: Secure Push Notification flags

---

.github/PULL_REQUEST_TEMPLATE.md

https://glia.atlassian.net/browse/MOB-4469
We have agreed that release notes are going to be generated based on Jira tickets

Remove release notes from PR template

---

build.gradle

[Migrate Android Widgets SDK to Dokka Gradle plugin V2](https://glia.atlassian.net/browse/MOB-4459)
- Override the com.fasterxml.jackson.core version for all configurations (mainly for Dokka) to use a version without a 'Stack-based Buffer Overflow' vulnerability

Override the com.fasterxml.jackson.core version

---

app/src/main/res/raw/sample_unified_config.json
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/BooleanQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/InputQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/ScaleQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/SingleQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/SurveyViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/UnifiedUiExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/survey/SurveyBooleanQuestionRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/survey/SurveyInputQuestionRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/survey/SurveyOptionRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/survey/SurveyScaleQuestionRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/survey/SurveySingleQuestionRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Survey.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyBooleanQuestionTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyInputQuestionTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyOptionTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyScaleQuestionTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveySingleQuestionTheme.kt
widgetssdk/src/main/res/drawable/shadow_down_bg.xml
widgetssdk/src/main/res/layout/survey_view.xml

[[Android] The survey input field applies styles differently](https://glia.atlassian.net/browse/MOB-4610)
Improve survey UI customization
- apply more Unified UI styles (based on https://github.com/salemove/mobile-sdk-unified/pull/44)
- align survey styles between Android and iOS SDKs
https://github.com/user-attachments/assets/6cc35399-3aeb-4f32-b11f-25387f2699fb

Improve survey UI customization

---

widgetssdk/src/main/java/com/glia/widgets/base/FadeTransitionActivity.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.kt

https://glia.atlassian.net/browse/MOB-4657

Remove unnecessary finishAfterTransition calls and improve survey animation

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt

https://glia.atlassian.net/browse/MOB-4595
This PR resolves a `RecyclerView` crash `(IllegalArgumentException: Tmp detached view)`. The crash occurred due to a race condition between item animations and data updates. The fix disables the `ItemAnimator` by setting it to `null`, which prevents the conflicting state and stabilizes the view.
**Disabled Animation**
[Screen_recording_20250916_095703.webm](https://github.com/user-attachments/assets/b44bf417-ba49-47e8-ac31-b01116390a75)
**Enabled Animation**
[Screen_recording_20250916_095938.webm](https://github.com/user-attachments/assets/edaf9c4e-d720-4500-b01e-5be00d900269)

Disable item animator for chat RecyclerView to avoid crashes.

---

widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt

https://glia.atlassian.net/browse/MOB-4648
The Idea is to save the new operator before updating the engagement state to `EngagementStarted` because the logic for many states(e.g. `hasOngiongEngagement`) checks for operator availability, and produces false positive states mid transition from one to another state.

Refactor engagement handling to improve state management

---

scripts/version-updater.gradle
version.properties
widgetssdk/build.gradle

https://glia.atlassian.net/browse/MOB-4754
Add Telemetry lib version to the `version.properties` configuration file.
Add Gradle task for updating the Telemetry lib version.

Add Telemetry lib version to the configuration file
