salemove/android-sdk-widgets

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java

Temporary fix
Need to decouple
visitorMediaState and operatorMediaState at some point

MUIC-363: [Android] Mute button doesn't work when starting audiocall

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/chat/ChatRecyclerView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/ImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/helper/FileHelper.java
widgetssdk/src/main/java/com/glia/widgets/glia/GliaSendMessageUseCase.java
widgetssdk/src/main/java/com/glia/widgets/model/GliaChatRepository.java
widgetssdk/src/main/res/layout/chat_operator_image_attachment_layout.xml
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/main/res/layout/visitor_image_attachment_layout.xml
widgetssdk/src/main/res/values/styles.xml

MUIC-423: [Android] Chat - In chat profile picture is missing when engagement is ongoing
MUIC-402: [Android] Chat - On chat view if the key board is opened the user is not able to scroll up
MUIC-403: [Android] Chat - User is not able to scroll in chat up
MUIC-420: [Android] Chat – Taking a photo and uploading it from the Visitor’s side in an additional message titled “option”

MUIC-402: [Android] Chat fixes

---

app/src/main/res/values/themes.xml
widgetssdk/build.gradle
widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/res/values/themes.xml

MUIC-415: [Android] Hybrid theme for call view

MUIC-414: [Android] Multiple action bars in chat view

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/colors.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorMessageViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/VisitorMessageViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/SingleChoiceCardView.java
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/themes.xml

visitorMessageBackgroundColor
visitorMessageTextColor
operatorMessageBackgroundColor
operatorMessageTextColor
botActionButtonBackgroundColor
botActionButtonTextColor

MUIC-558: [Android] Extend color palette -

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java

App crashes when try to turn off the video during a video call

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/Configuration.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfigurationManager.java
widgetssdk/src/main/java/com/glia/widgets/core/dialog/domain/IsShowOverlayPermissionRequestDialogUseCase.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

https://glia.atlassian.net/browse/MUIC-565
**Additional info**
Will use `GliaConfigurationManager` for Configuration holder (will need to move whitelabel stuff there too)
At some point would love to introduce some sort of public interface with all the non-ui related configurations (or maybe add some to `GliaConfig` class - some will come from the core-sdk "purchased package" anyway in the future.

MUIC-565: [Android] Disable overlay permission dialog (if bubble disabled)

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/layout/main_fragment.xml
app/src/main/res/values/strings.xml
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java

Added "Clear Session" button on UI that removes visitor and cleans up chat history.
MUIC-587

Introduce interface for clearing visitor session

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java

https://glia.atlassian.net/browse/MUIC-573
**Additional info**
Needs QA - didn't try this fix with bot

MUIC-573: [Android] - User unable to send message after answer Response Card

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java

MUIC-573: [Android] - User unable to send message after answer Response Card

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/themes.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.java
widgetssdk/src/main/java/com/glia/widgets/view/button/BaseConfigurableButton.java
widgetssdk/src/main/java/com/glia/widgets/view/button/GliaNegativeButton.java
widgetssdk/src/main/java/com/glia/widgets/view/button/GliaNeutralButton.java
widgetssdk/src/main/java/com/glia/widgets/view/button/GliaPositiveButton.java
widgetssdk/src/main/java/com/glia/widgets/view/header/button/GliaEndButton.java
widgetssdk/src/main/res/layout/operator_ended_engagement_dialog.xml
widgetssdk/src/main/res/layout/options_dialog.xml
widgetssdk/src/main/res/layout/screensharing_dialog.xml
widgetssdk/src/main/res/layout/upgrade_dialog.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/themes.xml

Notes:
Examples added for runtime and buildtime configuration

MUIC-610: [Android] - Make Positive button and Negative button styles configurable

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
app/src/main/res/xml/preferences.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.java
widgetssdk/src/main/res/layout/options_dialog_vertical.xml
widgetssdk/src/main/res/layout/screensharing_dialog_vertical.xml
widgetssdk/src/main/res/layout/upgrade_dialog_vertical.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/themes.xml

Note: 
Rough implementation of Vertical Alignment support
Can test with enabling toggle in settings screen

MUIC-601: [Android] Vertical CTA button position

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
app/src/main/res/xml/preferences.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.java
widgetssdk/src/main/res/layout/options_dialog_vertical.xml
widgetssdk/src/main/res/layout/screensharing_dialog_vertical.xml
widgetssdk/src/main/res/layout/upgrade_dialog.xml
widgetssdk/src/main/res/layout/upgrade_dialog_vertical.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/main/res/values/themes.xml

Keys that can be overrided for dialogs - might missed something :) but end_dialog was the most important one
```
<string name="glia_dialog_leave_queue_title">Are you sure you want to leave?</string>
<string name="glia_dialog_leave_queue_message">You will lose your place in the queue.</string>
<string name="glia_dialog_leave_queue_yes">@string/glia_dialog_yes</string>
<string name="glia_dialog_leave_queue_no">@string/glia_dialog_no</string>
<string name="glia_dialog_screen_sharing_offer_enable_notifications_title">Share your screen?</string>
<string name="glia_dialog_screen_sharing_offer_enable_notifications_message">The operator has requested you share your screen. However this requires the app\'s notifications be switched on. Do this now?</string>
<string …
```

MUIC-611: [Android] Create new keys for android CTA buttons

---

widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/core/queue/GliaQueueRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorInfo.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaWidgetException.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/VisitorInfoUpdate.java

Update Visitor Information

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/ui/FilePreviewView.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/urlwebview/OperatorLinksView.java
widgetssdk/src/main/java/com/glia/widgets/view/header/AppBarView.java
widgetssdk/src/main/res/layout-land/call_view.xml
widgetssdk/src/main/res/layout/app_bar.xml
widgetssdk/src/main/res/layout/call_view.xml
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/main/res/layout/file_preview_view.xml
widgetssdk/src/main/res/layout/operator_links_view.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/themes.xml

Includes
https://glia.atlassian.net/browse/MUIC-618

MUIC-619: [Android] Customize Exit Queue Button

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorStatusViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/themes.xml

https://glia.atlassian.net/browse/MUIC-620

MUIC-620: [Android] Customise Operator status Heading and Caption

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore

https://glia.atlassian.net/browse/MUIC-621
Github template for PR-s

MUIC-621: [Android] Add github template

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
app/src/main/res/xml/preferences.xml
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/themes.xml

Add separate attribute for changing send button color
https://glia.atlassian.net/browse/MOB-1030

MOB-1030: Add separate attribute for changing send button color

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java

https://glia.atlassian.net/browse/MUIC-598
- there seems to be a race condition where multiple threads access a variable. Added synchronisation to few places.

MUIC-598 Audio/Video - Application may crash if visitor minimizes a call

---

widgetssdk/src/main/res/layout/chat_receive_message_content.xml

https://glia.atlassian.net/browse/MUIC-546

MUIC-546 Make chat text selectable

---

app/src/main/java/com/glia/exampleapp/Application.java
app/src/main/java/com/glia/exampleapp/SettingsFragment.java
app/src/main/java/com/glia/exampleapp/auth/AuthorizationFragment.java
app/src/main/java/com/glia/exampleapp/auth/AuthorizationPageFragment.java
app/src/main/java/com/glia/exampleapp/auth/AuthorizationType.java
app/src/main/java/com/glia/exampleapp/auth/adapter/AuthorizationPagerAdapter.java
app/src/main/res/layout/authorization_fragment.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/auth_site_api_key.xml
app/src/main/res/xml/auth_token.xml
app/src/main/res/xml/preferences.xml
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.java

https://glia.atlassian.net/browse/MUIC-638
Updated dependency of core sdk to 0.23.0
Introduced additional Authorization method for Glia Core SDK

MUIC-638: [Android] Update Glia Android SDK dependency to 0.23.0

---

widgetssdk/src/main/res/layout/chat_visitor_message_layout.xml

https://glia.atlassian.net/browse/MUIC-546

MUIC-546 Make visitor message text selectable

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/FileAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/OperatorFileAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/VisitorFileAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/ImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/OperatorImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/VisitorImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/OperatorAttachmentItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/OperatorMessageItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/VisitorAttachmentItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/VisitorMessageItem.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/res/layout/chat_attachment_visitor_file_layout.xml
widgetssdk/src/main/res/layout/chat_attachment_visitor_image_layout.xml

https://glia.atlassian.net/browse/MUIC-594

MUIC-594 Add "delivered" message to image and file messages

---

widgetssdk/build.gradle

https://glia.atlassian.net/browse/MUIC-645
Version update

Release 1.7.0

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java

https://glia.atlassian.net/browse/MUIC-643

Chat input mode should change to enabled if operator sends message first

---

widgetssdk/build.gradle

https://glia.atlassian.net/browse/MUIC-649

Version update

---

widgetssdk/src/main/res/values/strings.xml

https://glia.atlassian.net/browse/MUIC-585
More fixes to the string after QA session

MUIC-585: [Android] Fix strings

---

widgetssdk/build.gradle

https://glia.atlassian.net/browse/MUIC-657
Version update pre release

Update Version to 1.7.4

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.java
widgetssdk/src/main/res/layout/chat_view.xml

https://glia.atlassian.net/browse/MUIC-494
- remove unnecessary callback that caused infinite loop when typing fast
- minor code cleanup

MUIC-494 - Chat - Keyboard may freeze when visitor is typing fast in the message text box

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java

Fix noteUpdateMethod on updateVisitorInfo

Fix noteUpdateMethod on updateVisitorInfo

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/layout/main_fragment.xml
app/src/main/res/values/strings.xml
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/call/CallViewCallback.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadsController.java

Stop ChatHeadService on clearVisitorSession

Fix clearVisitorSession and introduced endEngagement functions

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java

https://glia.atlassian.net/browse/MUIC-575

Disable start new engagement on orientation change if engagement ended

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/view/header/AppBarView.java
widgetssdk/src/main/res/layout-land/call_view.xml
widgetssdk/src/main/res/layout/app_bar.xml
widgetssdk/src/main/res/layout/call_buttons_layout.xml
widgetssdk/src/main/res/layout/call_view.xml
widgetssdk/src/main/res/layout/operator_status_view.xml
widgetssdk/src/main/res/values/donottranslate.xml
widgetssdk/src/main/res/values/strings.xml

Add VoiceOver support to CallView screen
https://glia.atlassian.net/browse/MOB-1143

Add VoiceOver support to CallView screen

---

app/build.gradle
app/src/main/java/com/glia/exampleapp/ChatFragment.java
app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/values/setup.xml
app/src/main/res/xml/preferences.xml
app/src/master/res/values/setup.xml

https://glia.atlassian.net/browse/MUIC-666

Remove keys from repository

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/FileAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/OperatorFileAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/VisitorFileAttachmentViewHolder.java

https://glia.atlassian.net/browse/MUIC-647

MUIC-647 Disable attachment download when already started

---

app/build.gradle
app/src/main/AndroidManifest.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
widgetssdk/build.gradle
widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/res/layout/alert_dialog.xml
widgetssdk/src/main/res/layout/chat_attachment_uploaded_item.xml
widgetssdk/src/main/res/layout/chat_view.xml

https://glia.atlassian.net/browse/MUIC-492
- As regression testing is needed anyway, I updated the libraries as well.

MUIC-492 Add support for Android 12

---

app/src/main/java/com/glia/exampleapp/SettingsFragment.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/xml/preferences.xml
build.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java

https://glia.atlassian.net/browse/MUIC-668

Add core sdk version and widgets sdk version to settings

---

widgetssdk/src/main/java/com/glia/widgets/view/ViewHelpers.java

https://glia.atlassian.net/browse/MUIC-664

[Android] Service bubble and Layout bubble drag events sometimes registred as click events

---

widgetssdk/src/main/java/com/glia/widgets/view/ViewHelpers.java

https://glia.atlassian.net/browse/MUIC-664
Previous solution worked well on emulator but not on real devices sadly :)

Click handles diff with Math.abs, action solution removed

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/core/notification/NotificationActionReceiver.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java

https://glia.atlassian.net/browse/MUIC-457

MUIC-457 Fix screensharing dialog not displayed in chat

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/core/chathead/ChatHeadService.java
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/IsDisplayApplicationChatHeadUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/ResolveChatHeadNavigationUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/ToggleChatHeadServiceUseCase.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadContract.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadLayout.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadPosition.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

https://glia.atlassian.net/browse/MUIC-663
Location holder for bubble

Service bubble needs to maintain the location

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/UploadAttachmentAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorMessageViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorStatusViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/VisitorMessageViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/OperatorFileAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/VisitorFileAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/ImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/OperatorImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/VisitorImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/OperatorMessageItem.java
widgetssdk/src/main/java/com/glia/widgets/view/SingleChoiceCardView.java
widgetssdk/src/main/res/layout/chat_attachment_operator_file_layout.xml
widgetssdk/src/main/res/layout/chat_attachment_uploaded_item.xml
widgetssdk/src/main/res/layout/chat_attachment_visitor_file_layout.xml
widgetssdk/src/main/res/layout/chat_attachment_visitor_image_layout.xml
widgetssdk/src/main/res/layout/chat_operator_message_layout.xml
widgetssdk/src/main/res/layout/chat_operator_status_layout.xml
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/main/res/layout/chat_visitor_message_layout.xml
widgetssdk/src/main/res/values/donottranslate.xml
widgetssdk/src/main/res/values/strings.xml

Add accessibility labels to the Chat screen
https://glia.atlassian.net/browse/MOB-1157

Add voiceover support on chat screen

---

widgetssdk/src/main/res/layout/file_preview_view.xml
widgetssdk/src/main/res/menu/menu_file_preview.xml
widgetssdk/src/main/res/values/strings.xml

Add accessibility labels to the file preview screen
https://glia.atlassian.net/browse/MOB-1159

Add accessibility labels to the file preview screen

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogsState.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.java
widgetssdk/src/main/res/values/strings.xml

https://glia.atlassian.net/browse/MUIC-658

Remove "End screen sharing" dialog

---

widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/colors.xml
widgetssdk/src/main/res/values/themes.xml

https://glia.atlassian.net/browse/MOB-1210
To test the customization with example app:
1.  Open /android-sdk-widgets/app/src/main/res/values/themes.xml
2. Uncomment the code `<item name="gliaChatStyle">@style/Theme.GliaAndroidSdkWidgetsExample.Chat</item>`
3. Scroll a bit down to the `ThemeOverlay.GliaAndroidSDKWidgetsExample.Chat` items and add `<item name="gliaChatBackgroundColor">@color/color_grey</item>
`

Add possibility to customize chat background.

---

app/src/main/java/com/glia/exampleapp/ChatFragment.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java

https://glia.atlassian.net/browse/MUIC-457

Fix screen sharing dialog not shown bug

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.java

https://glia.atlassian.net/browse/MUIC-562

MUIC-562-1 Add screen sharing mode to sample app settings

---

build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/SiteInfoUseCase.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaEngagementRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

https://glia.atlassian.net/browse/MOB-1191?atlOrigin=eyJpIjoiOTZlOTE1YjFmMjAxNDhiOThiMDY0NmZhZTI2MDc2OGEiLCJwIjoiaiJ9
MOB-1191

Devs want to show/hide attachment button depends on site configuration

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfigurationManager.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/data/GliaScreenSharingRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java

https://glia.atlassian.net/browse/MUIC-562

Implement screen sharing mode setting

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfigurationManager.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/data/GliaScreenSharingRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java

https://glia.atlassian.net/browse/MUIC-562
- feature branch merge to develop - this code is already reviewed

MUIC-562 Add screen sharing mode setting

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.java
widgetssdk/src/main/res/layout/options_dialog.xml
widgetssdk/src/main/res/layout/options_dialog_reversed.xml
widgetssdk/src/main/res/layout/options_dialog_vertical.xml
widgetssdk/src/main/res/layout/options_dialog_vertical_reversed.xml
widgetssdk/src/main/res/layout/screensharing_dialog.xml
widgetssdk/src/main/res/layout/screensharing_dialog_vertical.xml
widgetssdk/src/main/res/layout/upgrade_dialog.xml

https://glia.atlassian.net/browse/MUIC-704
Dialogs will get refactored in separate task, this should do for now

End engagement Positive and Negative button style should be reversed

---

widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/configuration/ChatHeadConfiguration.java
widgetssdk/src/main/res/drawable/ic_pause_circle.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/themes.xml

Configuration and theme updates

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java

https://glia.atlassian.net/browse/MUIC-705

Exit queue dialog buttons style should be reversed

---

widgetssdk/src/main/java/com/glia/widgets/call/CallState.java

Call State update

---

widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.java

Chat state update

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/GliaOnEngagementEndUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/GliaOnEngagementUseCase.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

Call controller updates

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadContract.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadLayout.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadLayoutContract.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

ChatHead Updates for On Hold feature

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.java
widgetssdk/src/main/res/drawable/bg_survey.xml
widgetssdk/src/main/res/layout/survey_activity.xml
widgetssdk/src/main/res/layout/survey_view.xml
widgetssdk/src/main/res/values-land-v29/themes.xml
widgetssdk/src/main/res/values-land/themes.xml
widgetssdk/src/main/res/values-v29/themes.xml
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/main/res/values/themes.xml

Create the survey container
[MOB-1179](https://glia.atlassian.net/browse/MOB-1179)

Survey container

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyAdapter.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyController.java
widgetssdk/src/main/java/com/glia/widgets/view/button/GliaSurveyOptionButton.java
widgetssdk/src/main/res/layout/survey_open_text_item.xml
widgetssdk/src/main/res/layout/survey_scale_item.xml
widgetssdk/src/main/res/layout/survey_single_choice_item.xml
widgetssdk/src/main/res/layout/survey_yes_no_item.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/dimens.xml
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/main/res/values/styles.xml
widgetssdk/src/main/res/values/themes.xml

Made the survey scale view according to the design
https://glia.atlassian.net/browse/MOB-1180

Survey: scale item

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyAdapter.java
widgetssdk/src/main/java/com/glia/widgets/view/button/GliaSurveyOptionButton.java
widgetssdk/src/main/res/layout/survey_yes_no_item.xml

Made the survey Yes/No view according to the design
https://glia.atlassian.net/browse/MOB-1181

Survey: yes/no item

---

widgetssdk/src/main/java/com/glia/widgets/survey/SingleChoiceAdapter.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyAdapter.java
widgetssdk/src/main/res/drawable/bg_survey_gray.xml
widgetssdk/src/main/res/layout/survey_open_text_item.xml

Make open text survey view according to the design
https://glia.atlassian.net/browse/MOB-1183

Survey open text item

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyAdapter.java
widgetssdk/src/main/res/drawable/bg_survey_radio_button.xml

Made the survey radio button according to the design
[MOB-1182](https://glia.atlassian.net/browse/MOB-1182)

Survey: single choice radio button

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallState.java

https://glia.atlassian.net/browse/MUIC-605
Controls are automatically shown when the screen is rotated to landscape in video call.

Show controls in video call when screen is rotated to landscape

---

widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/ToggleChatHeadServiceUseCase.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

https://glia.atlassian.net/browse/MUIC-715
I added a null check to avoid the crash. There might be a deeper problem but I'm hesitant to change the logic and break something.

Fix crash caused by build time theme being null in chat head controller.

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorMediaRepository.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoConstraintLayout.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoContract.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoCoordinatorLayout.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoView.java
widgetssdk/src/main/res/layout-land/call_view.xml
widgetssdk/src/main/res/layout/call_view.xml
widgetssdk/src/main/res/layout/visitor_video_floating_view.xml
widgetssdk/src/main/res/layout/visitor_video_layout_view.xml
widgetssdk/src/main/res/values/colors.xml
widgetssdk/src/main/res/values/strings.xml

https://glia.atlassian.net/browse/MUIC-714

On Hold indicator for Popup Visitor Video View

---

widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

https://glia.atlassian.net/browse/MUIC-710

Fix NPE in ServiceChatHeadController.java

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java

Fix: Show the End Engagement pop up if engagement doesn't have a survey
https://glia.atlassian.net/browse/MUIC-728
This fix also fixes the issue https://glia.atlassian.net/browse/MUIC-727

Fix end engagement popup

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyAdapter.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyController.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyState.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.java
widgetssdk/src/main/res/layout/survey_view.xml
widgetssdk/src/main/res/values/strings.xml

Make dynamic the survey screen title.

Dynamic the survey title

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyAdapter.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.java
widgetssdk/src/main/res/layout/survey_input_question_item.xml
widgetssdk/src/main/res/values/dimens.xml
widgetssdk/src/main/res/values/strings.xml

ADA complient survey view
[MOB-1268](https://glia.atlassian.net/browse/MOB-1268)

ADA complient survey view

---

widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorMediaRepository.java

https://glia.atlassian.net/browse/MUIC-729

On hold not getting initial onhold event

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoContainer.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoContract.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoView.java

https://glia.atlassian.net/browse/MUIC-751

Fix on hold videocrash

---

widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

https://glia.atlassian.net/browse/MUIC-757

Fixes issue when operator doesnt have image operator icon not shown

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyController.java
widgetssdk/src/test/java/com/glia/widgets/survey/SurveyControllerTest.java

Fix orientation change
[MUIC-763](https://glia.atlassian.net/browse/MUIC-763)

Fix orientation change

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/view/OperatorStatusView.java

https://glia.atlassian.net/browse/MUIC-769
Also fixes issue when during image loading operator status is showing only brand primary and icon is gone
Needs validating:
https://glia.atlassian.net/browse/MUIC-733

[Android] Chat/Audio/Video – Operator status fixes

---

widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java

https://glia.atlassian.net/browse/MUIC-770

Audio/Video – Operator bubble is not turned to default one after finishing engagement with “On hold”

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallState.java
widgetssdk/src/main/java/com/glia/widgets/call/domain/ToggleVisitorAudioMediaMuteUseCase.java
widgetssdk/src/main/java/com/glia/widgets/call/domain/ToggleVisitorVideoUseCase.java
widgetssdk/src/main/java/com/glia/widgets/call/domain/exception/UnexpectedAudioStatusException.java
widgetssdk/src/main/java/com/glia/widgets/call/domain/exception/UnexpectedVideoStatusException.java
widgetssdk/src/main/java/com/glia/widgets/call/domain/exception/VisitorAudioMissingException.java
widgetssdk/src/main/java/com/glia/widgets/call/domain/exception/VisitorVideoMissingException.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorMediaRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/rx/GliaWidgetsSchedulers.java
widgetssdk/src/main/java/com/glia/widgets/helper/rx/Schedulers.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoContainer.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoController.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/domain/IsShowOnHoldUseCase.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/domain/IsShowVideoUseCase.java

https://glia.atlassian.net/browse/MUIC-718
https://glia.atlassian.net/browse/MUIC-719

Mute on hold (+button update) Pause Video on hold (+button update)

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/domain/ToggleVisitorAudioMediaMuteUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorMediaRepository.java

https://glia.atlassian.net/browse/MUIC-718

Fix mute and visitor video buttons not working

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.java

Fix keyboard overlay
[MUIC-766](https://glia.atlassian.net/browse/MUIC-766)

Fix keyboard overlay

---

widgetssdk/src/main/java/com/glia/widgets/core/survey/domain/GliaSurveyAnswerUseCase.java

https://glia.atlassian.net/browse/MUIC-777
Related to https://glia.atlassian.net/browse/MOB-1283

Survey - do not send empty answers

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/ui/FilePreviewActivity.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.java

Accessible screen titles
https://glia.atlassian.net/browse/MOB-1278

Accessible screen titles

---

widgetssdk/src/main/res/layout/chat_attachment_popup.xml
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/main/res/values/dimens.xml

Make Chat screen according ADA
https://glia.atlassian.net/browse/MOB-1160

Make Chat screen according ADA

---

widgetssdk/src/main/java/com/glia/widgets/core/survey/domain/GliaSurveyAnswerUseCase.java
widgetssdk/src/test/java/android/text/TextUtils.java
widgetssdk/src/test/java/com/glia/widgets/core/survey/domain/GliaSurveyAnswerUseCaseTest.java

**Related Jira issue:**
[Survey - Operator doesn't get survey report if Visitor answers only for required question](https://glia.atlassian.net/browse/MOB-1283)
The reason for the issue was in invalid answers to the survey.
Backend returns error if any answer is incorrect.
It was decided to write tests to make sure the business logic is correct.

Tests for survey answers validation logic

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorInfo.java
widgetssdk/src/main/java/com/glia/widgets/core/visitor/VisitorInfoUpdate.java

https://glia.atlassian.net/jira/software/projects/MOB/boards/142?assignee=61b1d4ac744c4d00698aab72&selectedIssue=MOB-1299
**Additional info:** https://salemove.slack.com/archives/CHN6UB7UH/p1653029445502119
MOB-1299

Change LinkedTreeMap to Map in VisitorInfoUpdate.java

---

widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.java
widgetssdk/src/main/res/layout/chat_head_view.xml
widgetssdk/src/main/res/values/strings.xml

Added content description to the ChatHeadView

ADA floating button

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/MediaUpgradeStartedViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.java
widgetssdk/src/main/res/layout/chat_media_upgrade_layout.xml
widgetssdk/src/main/res/values/donottranslate.xml
widgetssdk/src/main/res/values/strings.xml

Small fixes for ADA:
- fixed bug with buttons contend descriptions on the CallView.
- moved content description labels from `donottranslate.xml` to `string.xml`

Small fixes for ADA

---

widgetssdk/src/main/java/com/glia/widgets/core/survey/domain/GliaSurveyAnswerUseCase.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyContract.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyController.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.java
widgetssdk/src/main/res/values/strings.xml

[Show error on sending survey if networks is not available](https://glia.atlassian.net/browse/MOB-1335)

Show error toast on Survey submit if network unavailable

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/glia/exampleapp/Activity.java
app/src/main/java/com/glia/exampleapp/Application.java
app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.java

https://glia.atlassian.net/jira/software/projects/MOB/boards/142?assignee=61b1d4ac744c4d00698aab72&selectedIssue=MOB-1341
open app with app token - `glia://widgets/token?site_id={site_id}&app_token={app_token}&queue_id={queue_id}`
open app with site api key - `glia://widgets/secret?site_id={site_id}&api_key_secret={api_key_secret}&api_key_id={api_key_id}&queue_id={queue_id}`

Devs want to implement deep link navigation to widgets sdk

---

widgetssdk/src/androidTest/java/com/glia/widgets/CallActivityTest.java
widgetssdk/src/androidTest/java/com/glia/widgets/DownloadsFolderDataSourceTest.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/ImageAttachmentViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/helper/FileHelper.java
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/data/GliaFileRepositoryImpl.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/data/source/local/DownloadsFolderDataSource.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/domain/usecase/DownloadFileUseCase.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/domain/usecase/GetImageFileFromCacheUseCase.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/domain/usecase/GetImageFileFromDownloadsUseCase.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/domain/usecase/GetImageFileFromNetworkUseCase.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/domain/usecase/PutImageFileToDownloadsUseCase.java
widgetssdk/src/main/java/com/glia/widgets/filepreview/ui/FilePreviewController.java
widgetssdk/src/test/java/com/glia/widgets/filepreview/data/GliaFileRepositoryTest.java
widgetssdk/src/test/java/com/glia/widgets/filepreview/data/source/local/InAppBitmapCacheTest.java
widgetssdk/src/test/java/com/glia/widgets/filepreview/domain/DownloadFileUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/filepreview/domain/GetImageFileFromCacheUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/filepreview/domain/GetImageFileFromDownloadsUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/filepreview/domain/GetImageFileFromNetworkUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/filepreview/domain/PutImageFileToDownloadsUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/filepreview/ui/FilePreviewControllerTest.java

https://glia.atlassian.net/browse/MUIC-831

MUIC-831 Unit tests for FilePreview feature

---

widgetssdk/src/androidTest/java/com/glia/widgets/CallActivityTest.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java

https://glia.atlassian.net/browse/MUIC-834

Fix CallActivityTest

---

widgetssdk/src/androidTest/java/com/glia/widgets/DownloadsFolderDataSourceTest.java
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/FileAttachmentRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/domain/AddFileToAttachmentAndUploadUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/domain/SupportedFileCountCheckUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/model/FileAttachment.java
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/test/java/com/glia/widgets/core/fileupload/FileAttachmentRepositoryTest.java
widgetssdk/src/test/java/com/glia/widgets/core/fileupload/domain/AddFileAttachmentsObserverUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/core/fileupload/domain/AddFileToAttachmentAndUploadUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/core/fileupload/domain/GetFileAttachmentsUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/core/fileupload/domain/RemoveFileAttachmentObserverUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/core/fileupload/domain/RemoveFileAttachmentUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/core/fileupload/domain/SupportedFileCountCheckUseCaseTest.java

https://glia.atlassian.net/browse/MUIC-833

Unit tests for file upload

---

app/src/main/java/com/glia/exampleapp/Activity.java
app/src/main/java/com/glia/exampleapp/Application.java
app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.java
app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/layout/main_fragment.xml

Deep link init

---

widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/data/GliaScreenSharingRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/test/java/com/glia/widgets/core/screensharing/ScreenSharingControllerTest.java
widgetssdk/src/test/java/com/glia/widgets/core/screensharing/data/GliaScreenSharingRepositoryTest.java

https://glia.atlassian.net/browse/MUIC-835
Clean up changes are in a separate commit - pls review commit-by-commit.

Add unit tests to Screen Sharing

---

widgetssdk/src/main/java/com/glia/widgets/core/queue/GliaQueueRepository.java

Fix: show engagement error alerts during the queue for engagement
[MOB-1432](https://glia.atlassian.net/browse/MOB-1432)

Fix: show engagement errors

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java

Fix: Animators may only be run on Looper threads
[MOB-1441](https://glia.atlassian.net/browse/MOB-1441)

Fix: Animators may only be run on Looper threads

---

widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java

https://glia.atlassian.net/browse/MOB-1444

Mob 1444 white screen when operator is not available and overlay is shown

---

widgetssdk/consumer-rules.pro
widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/GliaFileProvider.java

https://glia.atlassian.net/browse/MOB-1452

Introduce custom File provider for Widget SDK

---

app/src/main/java/com/glia/exampleapp/ChatFragment.java
app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.java
app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
build.gradle
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallIntentBuilder.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/core/queue/GliaQueueRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/queue/domain/GliaQueueForChatEngagementUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/queue/domain/GliaQueueForMediaEngagementUseCase.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.java
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.java

MOB-1446
• Remove VisitorContext related stuff
• Add visitor context asset Id support
• Delete implementation of deprecated methods from Glia class
https://glia.atlassian.net/browse/MOB-1446

Introduce VisitorContext support for Widgets SDK

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatInputMode.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.java

MOB-1456
https://glia.atlassian.net/browse/MOB-1456

Disable sending message during engagement transferring

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
widgetssdk/src/main/java/com/glia/widgets/call/Configuration.java

MOB-1473
https://glia.atlassian.net/browse/MOB-1473

Fix app crash when clicking on the bubble

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatViewCallback.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/data/ChatScreenRepository.java
widgetssdk/src/main/java/com/glia/widgets/chat/data/ChatScreenRepositoryImpl.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/IsFromCallScreenUseCase.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/UpdateFromCallScreenUseCase.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

MOB-1474
https://glia.atlassian.net/browse/MOB-1474

Fix the user can't return to the audio screen

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.java
widgetssdk/src/test/java/com/glia/widgets/core/screensharing/ScreenSharingControllerTest.java

MOB - 1477
https://glia.atlassian.net/browse/MOB-1477

Glia overlay issue in Android restricting to tap on back button

---

widgetssdk/src/main/java/com/glia/widgets/call/CallState.java

MOB - 1478
https://glia.atlassian.net/browse/MOB-1478

Fix upgrade from audio to one-way video works unexpectedly

---

bitrise.yml

In order to have changes to the `bitrise.yml` go through source
control, the file is added to the repository. No changes have been
done to this file, as it has just been downloaded directly from
Bitrise.
MOB-1510

Add `bitrise.yml` to repository

---

bitrise.yml

Fix typo in `bitrise.yml` file

---

build.gradle
scripts/version-updater.gradle
version.properties

Extracted the Core SDK version to a separate file version.properties and added gradle script that can edit this file.
https://glia.atlassian.net/browse/MOB-1503

Add support for CI/CD to update Core SDK dependency

---

widgetssdk/sample_unified_config.json
widgetssdk/src/main/java/com/glia/widgets/helper/ResourceProvider.java
widgetssdk/src/main/java/com/glia/widgets/view/button/GliaSurveyOptionButton.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/UiComponents.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/Button.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/ColorLayer.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/Font.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/Layer.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/RemoteConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/Text.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/base/Alignment.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/base/Color.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/base/Size.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/base/SizeImpl.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/base/TextStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/call/BarButtonStates.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/call/BarButtonStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/call/ButtonBar.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/call/CallScreenStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/chat/ChatScreenStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/chat/Header.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/chat/MessageBalloon.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/deserializer/AlignmentDeserializer.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/deserializer/ColorDeserializer.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/deserializer/ColorLayerDeserializer.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/deserializer/DpDeserializer.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/deserializer/SpDeserializer.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/deserializer/TextStyleDeserializer.java

MOB - 1547
https://glia.atlassian.net/browse/MOB-1549
Created
**Base Components:** Alignment, Color, Size, DpSize, SpSize, TextStyle, Font, Layer, Text, RemoteColor, RemoteButton
**Chat:** Chat, Header, MessageBaloon
Also created custom deserializers to be sure that base components like _Color_ and _Size_ are deserialized with valid values or passed _null_ instead.

Add Base components and Chat screen components

---

scripts/version-updater.gradle
version.properties
widgetssdk/build.gradle

https://glia.atlassian.net/browse/MOB-1564

Script for CI release flow to update Widgets version

---

app/src/main/java/com/glia/exampleapp/Application.java
app/src/main/java/com/glia/exampleapp/ExampleCustomCardAdapter.java
app/src/main/res/layout/native_view_item.xml
widgetssdk/build.gradle
widgetssdk/consumer-rules.pro
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/CustomCardAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/WebViewCardAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/CustomCardViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/WebViewViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/CustomCardTypeUseCase.java
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaSendMessageUseCase.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/ResponseAttachment.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/CustomCardItem.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/res/layout/web_view_layout.xml
widgetssdk/src/test/java/com/glia/widgets/chat/adapter/CustomCardAdapterTest.java
widgetssdk/src/test/java/com/glia/widgets/chat/domain/CustomCardTypeUseCaseTest.java

Added custom message renderer interface
[MOB-1246](https://glia.atlassian.net/browse/MOB-1246)

Custom messages renderer interface

---

version.properties

- Upgraded Core SDK version to 0.25.3

Glia Android Widgets SDK 1.8.5

---

.gitignore
bitrise.yml
scripts/version-updater.gradle

There's more info in each commit, but TL:DR there was work required in the Gradle scripts to have the jobs run correctly, and then some work in Bitrise was added so that both project version increase and Core SDK version increase are automated.
As always, copying bitrise.yml into our repository brings a plethora of unwanted changes, but I cannot do anything about it.

Add workflows to automate version increases

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/UiTheme.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/helper/ThemeUnits.java
widgetssdk/src/main/java/com/glia/widgets/view/configuration/call/CallStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/configuration/chat/ChatStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/Button.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/ColorLayer.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/Font.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/Layer.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/RemoteConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/Text.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/base/Alignment.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/base/Size.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/base/SizeImpl.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/base/TextStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/call/BarButtonStates.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/call/BarButtonStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/call/ButtonBar.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/call/CallScreenStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/chat/ChatScreenStyle.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/chat/Header.java
widgetssdk/src/main/java/com/glia/widgets/view/unifieduiconfig/component/chat/MessageBalloon.java

Create a base mechanism to use RemoteConfiguration in UiTheme
MOB-1571

Use RemoteConfiguration in UiTheme

---

app/src/main/java/com/glia/exampleapp/ExampleCustomCardAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/WebViewCardAdapter.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/WebViewViewHolder.java

Added a callback for an action that can be called from a WebView message
MOB-1576

WebView message action callback

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/layout/main_fragment.xml
app/src/main/res/values/strings.xml
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.java

[MOB-1533](https://glia.atlassian.net/browse/MOB-1533)
<p float="left">
</p>

Implement UI for setting Opaque Authentication in Widgets Testing App

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyAdapter.java
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.java
widgetssdk/src/main/res/layout/survey_boolean_question_item.xml
widgetssdk/src/main/res/layout/survey_scale_question_item.xml

MOB - 1586
https://glia.atlassian.net/browse/MOB-1586
I can't figure out how, but in some cases, Survey styles are requested before we set it, that's why I added the initial style to the constructor of SurveyAdapter.

Android App crashes when the visitor/operator ends the engagement call

---

widgetssdk/src/main/java/com/glia/widgets/core/authentication/Authentication.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.java

This will clear up the data related to previous visitor from controllers.
MOB-1583

Clear controllers after authentication or de-authentication was called

---

.github/workflows/increment-project-version.yml
bitrise.yml

Each commit has the description and what is solved.

Several fixes for Bitrise

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java

Prevent permission requests when upgrading to the one-way video
[MOB-1459](https://glia.atlassian.net/browse/MOB-1459)

Fix permission requests on upgrading to the one-way video

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/glia/exampleapp/Application.java
build.gradle

Add push notifications support

Add push notifications support

---

widgetssdk/src/main/java/com/glia/widgets/call/CallButtonLabelView.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallState.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/call/ThemedStateText.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorStatusViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/call/BarButtonStatesRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/call/CallRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/EngagementStateRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/MessageBalloonRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ResourceExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ViewExstensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/call/BarButtonStatesTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/call/CallTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/EngagementStateTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/MessageBalloonTheme.kt
widgetssdk/src/main/res/layout-land/call_view.xml
widgetssdk/src/main/res/layout/call_buttons_layout.xml
widgetssdk/src/main/res/layout/call_view.xml

- Implement `Remote Configuration` for buttons bar
- Remove `tintColor` from `EngagementStateTheme.kt`
- Add `EngagementStatesTheme` to `CallTheme.kt`
- Create` CallButtonLabelView.kt` custom view to ease `ButtonBar` `Button` label state's management
MOB-1648
https://glia.atlassian.net/browse/MOB-1648

Call Screen. Implement Remote Configuration for Buttons Bar

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/res/raw/remote_config.json
build.gradle
gradle/wrapper/gradle-wrapper.properties
widgetssdk/build.gradle
widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/view/OperatorStatusView.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/BadgeTextView.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/bubble/BubbleRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/bubble/OnHoldOverlayRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/call/ButtonBarRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/AttachmentSourceListRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/BadgeRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/ChatRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/OperatorRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/UnreadIndicatorRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ViewExstensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/base/BadgeTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/bubble/BubbleTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/call/ButtonBarTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/ChatTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/OnHoldOverlayTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/OperatorTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/UnreadIndicatorTheme.kt
widgetssdk/src/main/res/drawable/bg_separator_gray.xml
widgetssdk/src/main/res/layout/chat_attachment_popup.xml

https://glia.atlassian.net/browse/MOB-1684
Changes based on - https://github.com/salemove/mobile-sdk-unified/pull/19
MOB 1684

Fix Configuration regarding new changes

---

widgetssdk/src/main/java/com/glia/widgets/core/chathead/ChatHeadService.kt

Fix floating button default position
[MOB-1760](https://glia.atlassian.net/browse/MOB-1760)

Fix floating button default position

---

widgetssdk/src/main/java/com/glia/widgets/messagecenter/ConfirmationScreenView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterContract.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/res/drawable/ic_checkmark_message_center_confirmation_screen.xml
widgetssdk/src/main/res/layout/message_center_confirmation_view.xml
widgetssdk/src/main/res/layout/message_center_message_view.xml
widgetssdk/src/main/res/layout/message_center_view.xml
widgetssdk/src/main/res/values/strings.xml

MOB-1729
https://glia.atlassian.net/browse/MOB-1729
https://user-images.githubusercontent.com/19994238/211342123-d81f5be3-21e1-4693-827e-ee224791a7f5.mp4

Add confirmation screen to Secure Messaging

---

widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterContract.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterState.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/res/layout/message_center_message_view.xml
widgetssdk/src/main/res/values/colors.xml
widgetssdk/src/main/res/values/strings.xml

[MOB-1679](https://glia.atlassian.net/browse/MOB-1679)
- Update UI for the Welcome to Message Center screen
- Added changes according to the design.
- Added state class.
https://user-images.githubusercontent.com/79906470/211868718-52560361-5dc2-417e-90cd-0423b615311d.mp4
[MOB-1679]: https://glia.atlassian.net/browse/MOB-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update UI for the Welcome to Message Center screen

---

bitrise.yml

https://glia.atlassian.net/browse/MOB-1765

Added Slack message step to master workflow

---

build.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/UploadAttachmentAdapter.java
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/FileAttachmentRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/SecureFileAttachmentRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/domain/AddFileToAttachmentAndUploadUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversations.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/AddSecureFileAttachmentsObserverUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/AddSecureFileToAttachmentAndUploadUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/GetSecureFileAttachmentsUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/RemoveSecureFileAttachmentObserverUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/RemoveSecureFileAttachmentUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/SendSecureMessageUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterContract.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/res/drawable/bg_attachment.xml
widgetssdk/src/main/res/layout/message_center_attachment_uploaded_item.xml
widgetssdk/src/main/res/layout/message_center_message_view.xml
widgetssdk/src/test/java/com/glia/widgets/core/fileupload/domain/AddSecureFileAttachmentsObserverUseCaseTest.java
widgetssdk/src/test/java/com/glia/widgets/messagecenter/MessageCenterControllerTest.kt

Add file attachment functionality to secure conversations welcome screen.
[MOB-1723](https://glia.atlassian.net/browse/MOB-1723)
[MOB-1723]: https://glia.atlassian.net/browse/MOB-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Secure conversations welcome screen file attachment

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.java
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/IsSecureEngagementUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/header/AppBarView.kt
widgetssdk/src/main/res/values/strings.xml

Upgrade secure conversations to chat engagement when the operator accepts the queue ticket
[MOB-1739](https://glia.atlassian.net/browse/MOB-1739)
[MOB-1739]: https://glia.atlassian.net/browse/MOB-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade secure conversations to chat engagement

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaLoadHistoryUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaSendMessageUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/IsOngoingEngagementUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/IsQueueingEngagementUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/IsSecureEngagementUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterContract.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/view/header/AppBarView.kt

Remove the back button on all secure conversation screens
[MOB-1867](https://glia.atlassian.net/browse/MOB-1867)
[MOB-1867]: https://glia.atlassian.net/browse/MOB-1867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove back button on secure conversation

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorMessageViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/view/SingleChoiceCardView.kt

Improved the single choice card.
Fixed the inconsistency of the chat state.
[MOB-1879](https://glia.atlassian.net/browse/MOB-1879)
[MOB-1879]: https://glia.atlassian.net/browse/MOB-1879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix single choice card

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterState.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt

Show attachment button on Welcome and Transcript screens based on site configuration.
[MOB-1877](https://glia.atlassian.net/browse/MOB-1877)
[MOB-1877]: https://glia.atlassian.net/browse/MOB-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show attachment button based on site configuration

---

widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/RemoteConfiguration.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/secureconversations/SecureConversationsWelcomeScreenConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/UnifiedTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/secureconversations/SecureConversationsWelcomeScreenTheme.kt

https://glia.atlassian.net/browse/MOB-1894
MOB 1894

Create models/data classes for secure conversation welcome screen

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/domain/CallVisualizer.java
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt

https://glia.atlassian.net/browse/MOB-1896

Add API docs related to Call Visualizer

---

widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/ChatRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/ChatTheme.kt

https://glia.atlassian.net/browse/MOB-1900
MOB 1900

Add new messages divider config to widgets SDK's ChatRemoteConfig

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaLoadHistoryUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/model/ChatHistoryResponse.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-1901
MOB 1901

Improve new message addition logic to avoid race condition

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/VisitorCodeContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/VisitorCodeController.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/controller/VisitorCodeControllerTest.kt

MOB-1899
Created a timer based on VisitorCode.duration that makes a request for a new VisitorCode when it runs out
Updated tests
No Screenshot to show

Implemented automatic update to visitorCode on timer running out

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/CallVisualizerManager.java
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/domain/CallVisualizer.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java

MOB-1832
Added a way to add visitor context and have visitor code view use it
* Made minor adjustment to reading data from prefs to avoid empty data being passed on. 
* Added new access point in CallVisualizer for adding context
* Made accept call visualizer engagement use the visitor context value

Added Visitor Context adding access point

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/imageattachment/ImageAttachmentViewHolder.java

Fix the threads scheduler configuration for the image subscriber
[MOB-1926](https://glia.atlassian.net/browse/MOB-1926)
[MOB-1926]: https://glia.atlassian.net/browse/MOB-1926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the threads configuration for the image view holder

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingView.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/callvisualizer/CallVisualizerConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/callvisualizer/VisitorCodeRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ViewExstensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/callvisulaizer/VisitorCodeTheme.kt
widgetssdk/src/main/res/layout/end_screen_sharing_view.xml

https://glia.atlassian.net/browse/MOB-1827
- Update the Visitor Code refresh button to use remote configs
- Fix the label in 'end screen sharing' screen disappearing under the screen header
- Remote theme updates for 'end screen sharing' screen

Call Visualizer remote config update

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/VisitorCodeController.kt
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogManager.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaEngagementRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/controller/VisitorCodeControllerTest.kt

https://glia.atlassian.net/browse/MOB-1931

Auto close Visitor Code dialog on engagement start

---

widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/AttachmentSourceListRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/chat/AttachmentSourceRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/base/BadgeTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/bubble/BubbleTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/AttachmentItemTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/AttachmentsPopupTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/FilePreviewTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/FileUploadBarTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/InputTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/chat/UnreadIndicatorTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Bubble.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Chat.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/EngagementStates.kt
widgetssdk/src/main/res/layout/chat_view.xml

MOB 1936
https://glia.atlassian.net/browse/MOB-1936

Feature/unified UI enhancement/mob 1936 implement color pallet based default theme for chat non list attributes

---

widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/alert/AlertTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Alert.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Base.kt

MOB 1938
https://glia.atlassian.net/browse/MOB-1938

Feature/unified UI enhancement/mob 1938 implement color pallet based default theme for alert

---

widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/parse/Deserializers.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/call/BarButtonStatesTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/call/BarButtonStyleTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/call/ButtonBarTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Base.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Call.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/EngagementStates.kt

MOB-1937
https://glia.atlassian.net/browse/MOB-1937

Implement color pallet based default theme for Call screen

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/CallVisualizerManager.java
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/domain/CallVisualizer.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java

https://glia.atlassian.net/browse/MOB-1933

Add global listener for Call Visualizer engagement start event

---

app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.java
app/src/main/java/com/glia/exampleapp/MainFragment.java
widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.java
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/CallVisualizerManager.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.java
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfigurationManager.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java

MOB-1928
* Migrated some of the permanent values to GliaSdkConfiguration in a way that it would be as backwards compatible as possible. 
* Added some minor changes overall including ChatActivity.getIntent method
To be changed:
* Documentation changes
* Testing

Added permanent configuration variables into init

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Base.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Survey.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/OptionButtonTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyBooleanQuestionTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyInputQuestionTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyScaleQuestionTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveySingleQuestionTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyTheme.kt

MOB-1939
https://glia.atlassian.net/browse/MOB-1939

Implement color pallet based default theme for Survey

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/BooleanQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/InputQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/ScaleQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/SingleQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/SurveyViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/BadgeTextView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/survey/SurveyInputQuestionRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ViewExstensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/survey/SurveyInputQuestionTheme.kt
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/main/res/layout/survey_input_question_item.xml

https://glia.atlassian.net/browse/MOB-1945

Fix/mob 1945 unified UI incorrect background layer is applied for survey input

---

widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/RemoteConfiguration.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/Merge.kt
widgetssdk/src/test/java/com/glia/widgets/view/unifiedui/exstensions/MergeKtTest.kt

Need to change merge mechanisms to fit logic: if data class → deep merge otherwise → take value from the `right` if not null otherwise -> take the `left` value
MOB-1951
https://glia.atlassian.net/browse/MOB-1951

Fix a merge mechanism doesn't support Lists and maps

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/layout/main_fragment.xml
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/ToggleChatHeadServiceUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaEngagementRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaEngagementTypeRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/GliaOnCallVisualizerUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/GliaOnEngagementUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/IsCallVisualizerUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/MediaProjectionService.java
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/RepositoryFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/InputQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadView.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java
widgetssdk/src/main/res/layout/chat_head_view.xml
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerTest.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForDialogsTest.kt

[MOB-1929](https://glia.atlassian.net/browse/MOB-1929)
https://user-images.githubusercontent.com/57521863/224855920-0aa09fd2-1fb8-4688-a01e-f37710ef368b.mov
[MOB-1929]: https://glia.atlassian.net/browse/MOB-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Launch bubble that is shown on top of any app for Call Visualizer screen sharing

---

widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/CharCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/main/res/layout/visitor_code_view.xml

The previous solution didn't behave as expected. Tested it out and fixed issues.
https://glia.atlassian.net/browse/MOB-1952

Fix support for runtime theme in the Visitor Code view

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt

MOB 1977
https://glia.atlassian.net/browse/MOB-1977
**Current:**
**Expected:**

Chat Screen doesn't get closed when engagement ended from the Call 

---

app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingView.kt
widgetssdk/src/main/java/com/glia/widgets/helper/Utils.java
widgetssdk/src/main/java/com/glia/widgets/view/CharCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/Merge.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/exstensions/ViewExstensions.kt

https://glia.atlassian.net/browse/MOB-1969

Add runtime theme support for end screen sharing screen

---

app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.kt

Added default company name to prevent clean install crashes

Added default value for CompanyName

---

widgetssdk/src/main/res/values/strings.xml

No Jira ticket
This change has been requested in https://salemove.slack.com/archives/CHN6UB7UH/p1679990824059459?thread_ts=1679562241.816179&cid=CHN6UB7UH

Update overlay permission request message

---

app/src/main/java/com/glia/exampleapp/GliaWidgetsConfigManager.kt
widgetssdk/src/main/res/layout/visitor_code_view.xml

https://glia.atlassian.net/browse/MOB-1820
Did tiny improvements related to acceptance tests

Call Visualizer acceptance tests

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterContract.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.java
widgetssdk/src/test/java/com/glia/widgets/messagecenter/MessageCenterControllerTest.kt

Show the chat bubble on a secure conversation starts
[MOB-1993](https://glia.atlassian.net/browse/MOB-1993)
[MOB-1993]: https://glia.atlassian.net/browse/MOB-1993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show the chat bubble on a secure conversation starts

---

widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/extensions/ResourceExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/extensions/ViewExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/base/ColorTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Call.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Chat.kt
widgetssdk/src/main/res/color/call_fab_icon_color_states.xml

[MOB 2053](https://glia.atlassian.net/browse/MOB-2053)

NCR would not like to have inconsistencies between iOS and Android 

---

widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/ProgressButton.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/StatefulEditText.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/StatefulWidgetAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/extensions/Merge.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/base/ColorTheme.kt
widgetssdk/src/main/res/drawable/bg_edit_text.xml
widgetssdk/src/main/res/layout/message_center_message_view.xml
widgetssdk/src/main/res/layout/progress_button.xml
widgetssdk/src/main/res/values/colors.xml
widgetssdk/src/test/java/com/glia/widgets/messagecenter/SimpleStatefulWidgetAdapterTest.kt

https://glia.atlassian.net/browse/MOB-2029

Mob 2029 customize welcome screen input and progress button

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt

MOB-2060
CallVisualizer does not want record audio permission, but with CallActivity logic it was requested, added an exception to CallVisualizer

Added CV specific exception to the permission

---

build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt

Update secure maven url for `core_sdk` and fix `new core_sdk` related issues.

Update secure maven url

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java

MOB-2081
Fixed empty chat screen by setting in CallController the pending survey to used

Fixed empty chat sceen

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/MediaUpgradeStartedViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/NewMessagesDividerViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorMessageViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorStatusViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/SystemMessageViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/VisitorMessageViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/ChatItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/LinkedChatItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/SystemChatItem.kt

[MOB 2037](https://glia.atlassian.net/browse/MOB-2037)

Devs want to support `system` messages in chat[widgets_sdk]

---

widgetssdk/src/main/java/com/glia/widgets/messagecenter/ConfirmationScreenView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/RemoteConfiguration.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/secureconversations/SecureConversationsConfirmationScreenRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/parse/Deserializers.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/UnifiedTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Alert.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Attachments.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Base.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Call.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Chat.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/SecureConversations.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Survey.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Text.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/secureconversations/SecureConversationsConfirmationScreenTheme.kt
widgetssdk/src/main/res/layout/message_center_confirmation_view.xml

https://glia.atlassian.net/browse/MOB-1692

Mob 1692 integrators want to have customization mechanisms for confirmation screen

---

widgetssdk/src/main/java/com/glia/widgets/chat/helper/FileHelper.java

[MOB 2073
](https://glia.atlassian.net/browse/MOB-2073)

App crashes when tries to display the image on the chat screen

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/res/layout/message_center_message_view.xml
widgetssdk/src/main/res/values-land/dimens.xml
widgetssdk/src/main/res/values/dimens.xml

Update the welcome screen behaviour

---

widgetssdk/src/main/java/com/glia/widgets/core/screensharing/MediaProjectionService.java

MOB-2034
Added service cleanup on app destroy

Added service cleanup on app destroy

---

app/src/main/java/com/glia/exampleapp/MainFragment.java

Open the chat transcript screen by clicking on push notification
MOB-1749

Open the chat transcript screen by clicking on push notification

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingView.kt
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.kt
widgetssdk/src/main/java/com/glia/widgets/view/CharCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/extensions/ViewExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/callvisulaizer/CallVisualizerTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/callvisulaizer/EndScreenSharingTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/callvisulaizer/VisitorCodeTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Base.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Button.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/CallVisualizer.kt
widgetssdk/src/main/res/drawable/bg_char_slot.xml

Devs want global colors implementation for CV flow

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/ChatActivity.java

Open chat transcript screen from a secure conversation push notification.
[MOB-2130](https://glia.atlassian.net/browse/MOB-2130)
[MOB-2130]: https://glia.atlassian.net/browse/MOB-2130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle secure conversation push type

---

widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/res/layout/message_center_confirmation_view.xml
widgetssdk/src/main/res/layout/message_center_message_view.xml
widgetssdk/src/main/res/values-land/dimens.xml
widgetssdk/src/main/res/values/dimens.xml

Confirmation screen in landscape is clipped

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/AddNewMessagesDividerUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/FindNewMessagesDividerIndexUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/GliaLoadHistoryUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/CustomCardItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/OperatorChatItem.java
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/ServerChatItem.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/SystemChatItem.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/history/VisitorMessageItem.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/model/ChatHistoryResponse.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/GetUnreadMessagesCountWithTimeoutUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/AddNewMessagesDividerUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/FindNewMessagesDividerIndexUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/GetUnreadMessagesCountWithTimeoutUseCaseTest.kt

Previously the index was calculated a step earlier, without taking into account that one message could contain multiple attachments.
MOB 2139

The new message divider is placed at the wrong index

---

widgetssdk/src/main/java/com/glia/widgets/helper/Files.kt

- ExifInterface and BitmapFactory shouldn't use the same InputStream
MOB 2155

Take a photo doesn't work

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt

MOB-2145
Added finish EndScreenSharingActivity on upgrade

Added close EndScreenSharingView on upgrade to call in CV

---

widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterState.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/res/layout/message_center_message_view.xml

Welcome screen appearance is broken

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/SurveyStateManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/SetEngagementConfigUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/survey/GliaSurveyRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

Ignore engagement ended result when the chat transcript screen is opened
[MOB-2166](https://glia.atlassian.net/browse/MOB-2166)
[MOB-2166]: https://glia.atlassian.net/browse/MOB-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ignore engagement ended result when the chat transcript screen is opened

---

widgetssdk/src/main/res/layout/chat_head_view.xml

Fixed icon being smaller than chathead

Fixed chathead anomalie on OnePlus

---

widgetssdk/src/main/java/com/glia/widgets/helper/ContextExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/helper/Insets.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/res/values/dimens.xml

Send button should be visible when the keyboard is open

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java

Fix Unexpected "Message Center Unavailable"

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/authentication/AuthenticationManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/ResetSurveyUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/SetEngagementConfigUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

Fix The survey appears after a visitor was de-authorised

---

widgetssdk/src/main/java/com/glia/widgets/helper/Files.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt

[Android] Secure conversations clears session when camera is closed

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/res/values/strings.xml

Crash when opens PDF file

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/UploadAttachmentAdapter.kt

Attachment loader should become blue for "Ready to send" attachment

---

build.gradle
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt

Uploaded new version of COre SDK to Nexus staging repository

Upgrade Core SDK dependency

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/ScreenSharingController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ActivityWatcherForChatHeadController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/screensharing/ScreenSharingControllerTest.java

Fix Screen-sharing icon should be hidden when screen-sharing is ended

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt

MOB-2212
Added close any and all dialogs on engagement ended

Auto close dialogs on engagement end

---

app/src/main/java/com/glia/exampleapp/MainFragment.java
app/src/main/res/values/strings.xml
widgetssdk/src/main/java/com/glia/widgets/core/authentication/AuthenticationManager.kt

[Integrators want to pass "external_access_token" during DirectID authorization](https://glia.atlassian.net/browse/MOB-2233)
This PR depends on [Core SDK PR](https://github.com/salemove/android-sdk/pull/470)

Extend direct id authorization with external_access_token

---

bitrise.yml

Bitrise does commits sometimes for us, like for example updating dependencies. Bitrise's documentation recommends to introduce an envvar with the values. These are the same values used in other projects.
MOB-1696

Add correct commit author to Bitrise commits

---

app/src/main/java/com/glia/exampleapp/ExampleCustomCardAdapter.java

https://glia.atlassian.net/browse/MOB-2228
The issue does not stream from the SDK but from custom chat message rendering that has been created as an example and for testing purposes.

Hide metadata from TestApp custom card rendering

---

bitrise.yml

This is a backport commit from master to development for [Add correct commit author to Bitrise commits](https://github.com/salemove/android-sdk-widgets/pull/629#issuecomment-1586659328) pull request.
Otherwise, we won't have this [Add correct commit author to Bitrise commits](https://github.com/salemove/android-sdk-widgets/pull/629#issuecomment-1586659328) in `development`.

Add correct commit author to Bitrise commits (backport commit)

---

build.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/audio/AudioControlManager.kt
widgetssdk/src/main/java/com/glia/widgets/core/audio/domain/OnAudioStartedUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/audio/domain/TurnSpeakerphoneUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/callvisualizer/domain/GliaOnCallVisualizerEndUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/GliaOnEngagementEndUseCase.java
widgetssdk/src/main/java/com/glia/widgets/core/operator/GliaOperatorMediaRepository.java
widgetssdk/src/main/java/com/glia/widgets/core/operator/domain/RemoveOperatorMediaStateListenerUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorMediaRepository.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

Use AudioSwitch to handle audio setting during the call
MOB-2082

Use AudioSwitch to handle audio setting during the call

---

scripts/generate-changelog.sh

https://glia.atlassian.net/browse/MOB-1913
During [the previous PR](https://github.com/salemove/android-sdk-widgets/pull/635) once everything was approved I did some git rebases and force-pushed forgetting to clean some temp changes made during testing.

fixup! Create a custom script for changelog

---

bitrise.yml
scripts/generate-changelog.sh

https://glia.atlassian.net/browse/MOB-1913
Fixed git clone step depth setting
Removed script for fetching tags because that is already done by the git clone step
Fixed changelog content not being printed in the CI logs

Extra fixes for changelog CI step

---

.editorconfig

EditConfig improved for Java classes and XML files

Improve EditConfig

---

bitrise.yml

Also, bitrise workflow editor automatically moved the title property. And I also added couple of titles

Make post-release CI steps to use 'development' branch as base

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatViewCallback.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-2389
Show Toast message — “This action is not currently supported on mobile'.

- Handle Broadcast events

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatViewCallback.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-2381

Handle external or deep link when the button is clicked

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatViewCallback.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-2385
https://glia.atlassian.net/browse/MOB-2387

Handle phone and email events

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/GvaBaseTypes.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-2391

Handle sending utterance

---

build.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/GvaChip.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/styles.xml
widgetssdk/src/main/res/values/themes.xml

Create a Quick Reply button UI

Create a Quick Reply button UI.

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaResponseTextViewHolder.kt

Added Response Text view holder. Used the operator message view for the new view holder.
[MOB-2364](https://glia.atlassian.net/browse/MOB-2364)
[MOB-2364]: https://glia.atlassian.net/browse/MOB-2364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GVA: Response Text UI

---

app/src/main/res/raw/sample_unified_config.json
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaPersistentButtonsViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/gva/GvaPersistentButtonRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/gva/GvaRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/gva/GvaPersistentButtonTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/gva/GvaTheme.kt

Apply Unified Customization to the Persistent Button card
[MOB-2373](https://glia.atlassian.net/browse/MOB-2373)
[MOB-2373]: https://glia.atlassian.net/browse/MOB-2373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Persistent buttons unified UI

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/GvaGalleryAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaGalleryItemViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaGalleryViewHolder.kt
widgetssdk/src/main/res/layout/chat_gva_gallery_item.xml
widgetssdk/src/main/res/layout/chat_gva_gallery_layout.xml
widgetssdk/src/main/res/values/styles.xml

Added the Gallery container UI
[MOB-2404](https://glia.atlassian.net/browse/MOB-2404)
[MOB-2404]: https://glia.atlassian.net/browse/MOB-2404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GVA: Create a Gallery container UI

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatItemHeightManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/GvaGalleryAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaGalleryItemViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaGalleryViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaPersistentButtonsViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaResponseTextViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorBaseViewHolder.kt
widgetssdk/src/main/res/layout/chat_gva_gallery_item.xml
widgetssdk/src/main/res/layout/chat_gva_gallery_layout.xml
widgetssdk/src/main/res/values/dimens.xml

Created the Gallery list.
RecycleView was configured according to the design.
The RecyclerView scrolling was optimized by pre-calculating the gallery card item height.
[MOB-2408](https://glia.atlassian.net/browse/MOB-2408)
[MOB-2408]: https://glia.atlassian.net/browse/MOB-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Gallery card recycler view

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt

Added clear all dialogs to engagement ended logic

Added clear all dialogs to engagement ended logic

---

app/src/main/res/raw/sample_unified_config.json
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaGalleryItemViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/UnifiedUiExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/gva/GvaGalleryCardRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/gva/GvaRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Button.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Gva.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/gva/GvaGalleryCardTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/gva/GvaTheme.kt

Applied Unified Customization to Gallery.
Also extended color palette default theme with PersistentButtonTheme and GalleryCardTheme.
[MOB-2406](https://glia.atlassian.net/browse/MOB-2406)
[MOB-2406]: https://glia.atlassian.net/browse/MOB-2406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GVA: Gallery Unified UI

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/WebViewCardAdapter.java

Provided `WebViewCardAdapter` as a default value for `GliaWidgets.customCardAdapter` property.
[MOB-2513](https://glia.atlassian.net/browse/MOB-2513)
[MOB-2513]: https://glia.atlassian.net/browse/MOB-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Default CustomCardAdapter

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatItemHeightManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/GvaButtonsAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/GvaGalleryAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/GvaGalleryItemViewHolder.kt
widgetssdk/src/main/res/layout/chat_gva_gallery_item.xml
widgetssdk/src/main/res/values/strings.xml

Make Gallery ADA compliant
[MOB-2410](https://glia.atlassian.net/browse/MOB-2410)
[MOB-2410]: https://glia.atlassian.net/browse/MOB-2410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GVA: ADA for Gallery cards

---

version.properties

- Update Core SDK version
- Increment Widgets SDK version

Increment Core SDK version to 1.0.3 (hotfix)

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/GvaChip.kt

Move the focus back to the chat list after the quick button perform.
[MOB-2400](https://glia.atlassian.net/browse/MOB-2400)
[MOB-2400]: https://glia.atlassian.net/browse/MOB-2400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make Quick Reply Button ADA compliant

---

.github/workflows/increment-project-version.yml
.github/workflows/post-release.yml
bitrise.yml

This PR is complementing [the one made before](https://github.com/salemove/android-sdk-widgets/pull/667/files).

Make changes according to Team Mobile Code Management and Release process

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/GliaOperatorRepository.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/MapOperatorUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/UpdateOperatorDefaultImageUrlUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/engagement/GliaOperatorRepositoryTest.kt

Replace the absent operator image URL with default from the `SiteInfo`
MOB 2532

Fix Default Operator image is not displayed for chat transcript

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt

Scroll chat to the end after any type of visitor message sent

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt

Prevent Chat RecyclerView scroll call when the adapter is empty.

---

widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt

Fix 🤖Line breaks are not rendered in GVA content

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/glia/exampleapp/Activity.java
app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/navigation/nav_graph.xml

- `glia://widgets/settings` - should route to the settings page.
MOB 2551

Devs want deep link support in Widgets SDK

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt

[MOB-2515](https://glia.atlassian.net/browse/MOB-2515)
This is a back-port commit cherry-picked from commit 450254dde04f80ac1c3783bcf52521633e002a47.
[MOB-2515]: https://glia.atlassian.net/browse/MOB-2515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve solution for opening dialogs on top of CallVisualizerSupportActivity (development)

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/MessagesNotSeenHandler.java

https://glia.atlassian.net/browse/MOB-2579
This is backport commit for the #728

Fix Survey survives GliaWidgets.endEngagement event(development)

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/MessagesNotSeenHandler.java

https://glia.atlassian.net/browse/MOB-2579

Fix Survey survives GliaWidgets.endEngagement event

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorStatusViewHolder.kt

This is a backport commit for the fix #726

Fix After transferring call to new agent, User is not getting image of the new agent(Development)

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/OperatorStatusViewHolder.kt

https://glia.atlassian.net/browse/MOB-2576

Fix After transferring call to new agent, User is not getting image of the new agent.

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/test/java/com/glia/widgets/chat/ChatManagerTest.kt

Fix Quick Replies are hidden after restoring the engagement

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt

Fix an app crash when there is no application to open uri

---

build.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/UnifiedThemeManager.kt
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewQuickReplySnapshotTest_defaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewQuickReplySnapshotTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewQuickReplySnapshotTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewQuickReplySnapshotTest_withWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewQuickReplySnapshotTest_withWithUnifiedThemeWithoutGva.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_initialState.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/ChatViewQuickReplySnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/ChatViewSnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/snapshotutils/SnapshotChatView.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/snapshotutils/SnapshotStrings.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

Added snapshot tests for Quick Replies.
Added base classes/interfaces for ChatView snapshot tests.
[MOB-2602](https://glia.atlassian.net/browse/MOB-2602)
[MOB-2602]: https://glia.atlassian.net/browse/MOB-2602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cover Quick Replies with snapshot tests

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/BooleanQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/InputQuestionViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/survey/viewholder/SurveyViewHolder.kt
widgetssdk/src/main/res/layout/survey_boolean_question_item.xml
widgetssdk/src/main/res/layout/survey_input_question_item.xml
widgetssdk/src/main/res/layout/survey_scale_question_item.xml
widgetssdk/src/main/res/layout/survey_single_question_item.xml
widgetssdk/src/main/res/layout/survey_view.xml
widgetssdk/src/main/res/values/new_strings.xml
widgetssdk/src/main/res/values/strings.xml

[MOB-2565](https://glia.atlassian.net/browse/MOB-2565)
[MOB-2565]: https://glia.atlassian.net/browse/MOB-2565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement remote strings for survey

---

.github/PULL_REQUEST_TEMPLATE.md

https://glia.atlassian.net/browse/MUIC-xxx

Add FIRM for release notes support to the PR template

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ActivityWatcherForChatHeadController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/view/head/ActivityWatcherForChatHeadTest.kt

[MOB-2682](https://glia.atlassian.net/browse/MOB-2682)
More details [here](https://salemove.slack.com/archives/CHN6UB7UH/p1695630202332469).
We can skip this PR from the release notes, I think.
[MOB-2682]: https://glia.atlassian.net/browse/MOB-2682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show screen sharing requests for any screen (not only Chat and Call) for Call Visualizer only.

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerCallback.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerRepository.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt

MOB 2716
https://glia.atlassian.net/browse/MOB-2716

Show acknowledgment dialog for Call Visualizer engagement

---

widgetssdk/src/main/java/com/glia/widgets/filepreview/ui/FilePreviewActivity.kt
widgetssdk/src/main/java/com/glia/widgets/filepreview/ui/FilePreviewView.kt
widgetssdk/src/main/java/com/glia/widgets/helper/ContextExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.kt
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt

Fixing issues that came up during exploratory testing session

Fixes following exploratory testing

---

widgetssdk/src/main/java/com/glia/widgets/messagecenter/ConfirmationScreenView.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageView.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/main/res/values/new_strings.xml

[Verify/improve ADA compliance string use in Android SDK](https://glia.atlassian.net/browse/MOB-2726)

Improve ADA for message center and visitor code view

---

.github/PULL_REQUEST_TEMPLATE.md

Additional reminders for PR template

---

widgetssdk/src/main/java/com/glia/widgets/StringProvider.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt

MOB 2722
https://glia.atlassian.net/browse/MOB-2722

Refactor Opt-in dialog strings to support Custom Locales

---

build.gradle
version.properties

https://glia.atlassian.net/browse/MOB-2698
Added local WIP Core SDK build with Live Observation that is needed for the next steps of development

Add local WIP Core SDK build with Live Observation

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerRepository.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/AcknowledgmentDialogUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-2698

Acknowledgment dialog use site settings

---

build.gradle
version.properties
widgetssdk/src/main/java/com/glia/widgets/call/CallController.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallViewCallback.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerCallback.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatViewCallback.java
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/AcknowledgmentDialogUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/engagement/domain/ConfirmationDialogUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-2756

Rename acknowledgment/opt-in dialog into confirmation dialog

---

widgetssdk/src/main/java/com/glia/widgets/Constants.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/helper/ContextExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadLayout.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/SnackBarDelegate.kt
widgetssdk/src/main/res/values/dimens.xml
widgetssdk/src/main/res/values/new_strings.xml
widgetssdk/src/test/java/com/glia/widgets/view/snackbar/SnackBarDelegateTest.kt

https://glia.atlassian.net/browse/MOB-2786

Create configurable snack bar for lo indication

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt

https://glia.atlassian.net/browse/MOB-1215
Floating visitor video container is hidden when not in use

Hide floating video container, when not in use

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizer.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/WeakReferenceDelegate.kt
widgetssdk/src/main/java/com/glia/widgets/permissions/ActivityWatcherForPermissionsRequest.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/ActivityWatcherForChatHead.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/ActivityWatcherForLiveObservation.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/ActivityWatcherForLiveObservationContract.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/ActivityWatcherForLiveObservationController.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/LiveObservationUseCase.kt
widgetssdk/src/test/java/com/glia/widgets/view/snackbar/LiveObservationUseCaseTest.kt

MOB 2792
https://glia.atlassian.net/browse/MOB-2792

Show indication snackbar on LO start

---

build.gradle
version.properties

No ticket
Update Core SDK build with LO feature WIP

Update Core SDK build with LO feature WIP

---

widgetssdk/src/test/snapshots/images/com.glia.widgets.liveobservation_CallActivitySnackBarTest_withDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.liveobservation_CallActivitySnackBarTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.liveobservation_CallActivitySnackBarTest_withUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.liveobservation_ChatActivitySnackBarTest_withDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.liveobservation_ChatActivitySnackBarTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.liveobservation_ChatActivitySnackBarTest_withUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.liveobservation_CommonSnackBarTest_withDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.liveobservation_CommonSnackBarTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.liveobservation_CommonSnackBarTest_withUnifiedTheme.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/liveobservation/CallActivitySnackBarTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/liveobservation/ChatActivitySnackBarTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/liveobservation/CommonSnackBarTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/liveobservation/SnackBarTestHelper.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

Add snapshot tests for LO snack bar

---

app/src/main/java/com/glia/exampleapp/ExampleAppConfigManager.kt
app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/sdk_basic_prefs.xml

https://glia.atlassian.net/browse/MOB-2815
Added manual override possibility into testing app settings

Added manual override to test app settings

---

build.gradle
version.properties
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/ActivityWatcherForLiveObservationController.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/LiveObservationPopupUseCase.kt

https://glia.atlassian.net/browse/MOB-2799

Make confirmation dialog and LO toast message show by default

---

version.properties

Incremented version to 2.2.2

---

build.gradle

Update Core SDK version with Live Observation build that has LO WIP

---

widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/alert/AlertDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/screensharing/ScreenSharingDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/ThemeWrapper.kt
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_AlertDialogTest_withDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_AlertDialogTest_withDefaultThemeAndButton.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_AlertDialogTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_AlertDialogTest_withGlobalColorsAndButton.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_AlertDialogTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_AlertDialogTest_withUiThemeAndButton.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_AlertDialogTest_withUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_AlertDialogTest_withUnifiedThemeAndButton.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/dialog/AlertDialogTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/dialog/DialogData.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

MOB 2805
https://glia.atlassian.net/browse/MOB-2805
Added snapshot tests for Alert Dialog

Snapshot test for Alert Dialog

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.java

MOB 2848
https://glia.atlassian.net/browse/MOB-2848

Fix The Overlay Dialog is Shown in the wrong activity for the CV flow

---

widgetssdk/src/main/res/layout/operator_ended_engagement_dialog.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OperatorEndedEngagementTest_withDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OperatorEndedEngagementTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OperatorEndedEngagementTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OperatorEndedEngagementTest_withUnifiedTheme.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/dialog/OperatorEndedEngagementTest.kt

MOB 2805
https://glia.atlassian.net/browse/MOB-2805

Snapshot tests for operator ended engagement dialog

---

widgetssdk/src/main/res/layout/screensharing_dialog.xml
widgetssdk/src/main/res/layout/screensharing_dialog_vertical.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withUnifiedTheme.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/SnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/dialog/ScreenSharingDialogTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/snapshotutils/SnapshotTheme.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

MOB 2805
https://glia.atlassian.net/browse/MOB-2805

Snapshot tests for screen sharing dialog

---

widgetssdk/src/main/res/layout/upgrade_dialog.xml
widgetssdk/src/main/res/layout/upgrade_dialog_vertical.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OptionDialogTest_withDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OptionDialogTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OptionDialogTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OptionDialogTest_withUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ReversedOptionDialogTest_withDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ReversedOptionDialogTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ReversedOptionDialogTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ReversedOptionDialogTest_withUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_UpgradeDialogTest_withDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_UpgradeDialogTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_UpgradeDialogTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_UpgradeDialogTest_withUnifiedTheme.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/dialog/OptionDialogTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/dialog/ReversedOptionDialogTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/dialog/UpgradeDialogTest.kt

MOB 2805
https://glia.atlassian.net/browse/MOB-2805

Snapshot tests for Options and Upgrade dialogs

---

build.gradle
version.properties

Update Core SDK dependency version with development branch build

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
build.gradle
version.properties

No ticket
This is just for testing purposes. Actually, any screen/dialog would be fine. Selected authentication dialog because it sounds as a security feature that fits the sensitive information role

Add sensetive screen for observation in Test App

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/layout/main_fragment.xml
app/src/main/res/menu/menu_main_fragment.xml

Create pause and resume controls for LO in the testing app

---

build.gradle

Update Core SDK dependency to latest development build

---

widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.java

Corrected typo in 'Show Upgrade 1WayVideo Dialog' log message

Correct typo in 'Show Upgrade 1WayVideo Dialog' log message

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerController.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/ActivityWatcherForCallVisualizerControllerTest.kt

https://glia.atlassian.net/browse/MOB-2929

Fix No notification permission screen sharing on CV

---

widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoContainer.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoController.java
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/domain/IsShowVideoUseCase.java

https://glia.atlassian.net/browse/MOB-2928
Made visitor's video view visible during onHold

Fixed visitor's video view

---

build.gradle
version.properties

Upgrade Core SDK version

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ActivityWatcherForChatHeadController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.kt

https://glia.atlassian.net/browse/MOB-2994

Hide Bubble when chat or queueing ends without overlay permission

---

version.properties

This version increment is done because this release will contain new feature Live Observation and that is minor version update

Increment project version to 2.3.0

---

widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ActivityWatcherForChatHeadController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.kt

This is a result of refactoring, this feature is working well on development.
https://glia.atlassian.net/browse/MOB-3000

Show chat bubble for restored engagements

---

widgetssdk/src/test/snapshots/images/com.glia.widgets.filepreview_FilePreviewTest_defaultView.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/filepreview/FilePreviewTest.kt

https://glia.atlassian.net/browse/MOB-2955
Added test for File preview Activity. This screen has a few parameters for testing.

File preview snapshot test

---

widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_attachmentList.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_attachmentListWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_attachmentListWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_attachmentListWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_attachmentListWithUnifiedThemeWithoutChat.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_failedAttachmentList.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_failedAttachmentListWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_failedAttachmentListWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_failedAttachmentListWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_failedAttachmentListWithUnifiedThemeWithoutChat.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessaging.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithUnifiedThemeWithoutChat.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_transferring.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_transferringWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_transferringWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_transferringWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_transferringWithUnifiedThemeWithoutChat.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/ChatViewSnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/snapshotutils/SnapshotChatView.kt

https://glia.atlassian.net/browse/MOB-3015
Added snapshot tests for Chat Screen. These tests can be updated (while working on the next task) in the future with some message items.

Added snapshot tests for Chat Screen

---

widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt

https://glia.atlassian.net/browse/MOB-2989

Add unit tests for Engagement repository

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt

https://glia.atlassian.net/browse/MOB-3018

Fix close button doesn't work on Messaging Chat screen

---

widgetssdk/src/main/res/values/themes.xml

https://glia.atlassian.net/browse/MOB-3037

Fix Response card message default color is wrong

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/MediaUpgradeOfferUseCase.kt

https://glia.atlassian.net/browse/MOB-3036

Prevent media upgrades to be shown when sdk is minimized for non-CV engagements

---

widgetssdk/src/main/java/com/glia/widgets/chat/AttachmentPopup.kt
widgetssdk/src/main/res/layout/chat_attachment_popup.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_chatWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_defaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_secureConversationsWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_withGlobalColors.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/AttachmentPopupSnapshotTest.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

https://glia.atlassian.net/browse/MOB-3020
Added snapshot tests for the Add Attachment popup

Attachment menu snapshots

---

widgetssdk/src/main/java/com/glia/widgets/chat/AttachmentPopup.kt
widgetssdk/src/main/res/layout/chat_attachment_popup.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_defaultView.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_withUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_withUnifiedThemeWithoutOperatorMessage.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_chatWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_defaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_secureConversationsWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_withGlobalColors.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/AttachmentPopupSnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/adapter/holder/OperatorMessageViewHolderSnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/adapter/holder/SystemMessageViewHolderSnapshotTest.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

https://glia.atlassian.net/browse/MOB-3027
Add snapshot tests for the System Message chat item

Snapshot tests for the System Message chat item

---

widgetssdk/src/main/java/com/glia/widgets/chat/AttachmentPopup.kt
widgetssdk/src/main/res/layout/chat_attachment_popup.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_NewMessagesDividerViewHolderSnapshotTest_defaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_NewMessagesDividerViewHolderSnapshotTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_NewMessagesDividerViewHolderSnapshotTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_NewMessagesDividerViewHolderSnapshotTest_withUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_NewMessagesDividerViewHolderSnapshotTest_withUnifiedThemeWithoutChat.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_defaultView.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_withUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat.adapter.holder_SystemMessageViewHolderSnapshotTest_withUnifiedThemeWithoutOperatorMessage.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_chatWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_defaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_secureConversationsWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_AttachmentPopupSnapshotTest_withGlobalColors.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/AttachmentPopupSnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/adapter/holder/NewMessagesDividerViewHolderSnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/adapter/holder/OperatorMessageViewHolderSnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/adapter/holder/SystemMessageViewHolderSnapshotTest.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

https://glia.atlassian.net/browse/MOB-3026
Added snapshot tests for the New Messages Divider chat item

Snapshot tests for the New Messages Divider chat item

---

widgetssdk/src/test/snapshots/images/com.glia.widgets.webbrowser_WebBrowserViewSnapshotTest_defaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.webbrowser_WebBrowserViewSnapshotTest_defaultThemeWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.webbrowser_WebBrowserViewSnapshotTest_defaultThemeWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.webbrowser_WebBrowserViewSnapshotTest_defaultThemeWithUnifiedThemeWithoutWebBrowser.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/webbrowser/WebBrowserViewSnapshotTest.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

https://glia.atlassian.net/browse/MOB-3049
Added snapshot tests for WebBrowserView

Snapshot tests for WebBrowserView

---

widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/helper/GliaActivityManager.kt
widgetssdk/src/main/java/com/glia/widgets/helper/IntentConfigurationHelper.kt
widgetssdk/src/main/java/com/glia/widgets/operator/RequestHandlerActivityWatcher.kt
widgetssdk/src/test/java/com/glia/widgets/helper/GliaActivityManagerTest.kt
widgetssdk/src/test/java/com/glia/widgets/operator/RequestHandlerActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/operator/RequestHandlerControllerTest.kt

https://glia.atlassian.net/browse/MOB-3051

Add tests for newly added classes

---

widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/alert/AlertDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewFactory.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/confirmation/ConfirmationDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/operatorendedengagement/OperatorEndedEngagementDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/option/OptionDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/screensharing/ScreenSharingDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/update/UpgradeDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/ThemeWrapper.kt
widgetssdk/src/main/res/layout/screensharing_dialog.xml
widgetssdk/src/main/res/layout/screensharing_dialog_vertical.xml
widgetssdk/src/main/res/values/themes.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_ScreenSharingDialogTest_withUnifiedTheme.png
widgetssdk/src/testSnapshot/res/values/themes_material.xml

https://glia.atlassian.net/browse/MOB-3067

[Backport] Fix Dialogs don't apply custom icons

---

app/src/main/res/values/themes.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/styles.xml

Deprecate Styles

---

app/src/main/res/values/themes.xml
widgetssdk/src/main/res/values/attrs.xml
widgetssdk/src/main/res/values/styles.xml

[Backport] Deprecate Styles

---

app/build.gradle
bitrise.yml
build.gradle
scripts/publish-module.gradle
widgetssdk/build.gradle

https://glia.atlassian.net/browse/MOB-2444
- Added ability to make local maven release.
- Set "minifyEnabled true" for the test application build that is used for the acceptance testing.
- Set "release" as a build variant for the testing app build task.

Made testing build with release settings

---

widgetssdk/src/main/java/com/glia/widgets/operator/OperatorRequestActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/operator/OperatorRequestContract.kt
widgetssdk/src/main/java/com/glia/widgets/operator/OperatorRequestController.kt
widgetssdk/src/test/java/com/glia/widgets/operator/OperatorRequestActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/operator/OperatorRequestControllerTest.kt

https://glia.atlassian.net/browse/MOB-3138

Display the Overlay dialog after receiving a media projection result

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/drawable/ic_no_engagement.xml
app/src/main/res/drawable/ic_ongoing_engagement.xml
app/src/main/res/menu/menu_main_fragment.xml

Add Engagement state indicator to Widgets testing app

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/EndScreenSharingActivity.kt
widgetssdk/src/main/java/com/glia/widgets/core/chathead/ChatHeadService.kt
widgetssdk/src/main/java/com/glia/widgets/core/fileupload/GliaFileProvider.java
widgetssdk/src/main/java/com/glia/widgets/core/notification/NotificationActionReceiver.kt
widgetssdk/src/main/java/com/glia/widgets/core/notification/NotificationRemovalService.kt
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/MediaProjectionService.kt
widgetssdk/src/main/java/com/glia/widgets/filepreview/ui/FilePreviewActivity.kt
widgetssdk/src/main/java/com/glia/widgets/permissions/PermissionsSupportActivity.kt
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.java
widgetssdk/src/main/java/com/glia/widgets/view/dialog/holder/DialogHolderActivity.kt
widgetssdk/src/main/java/com/glia/widgets/webbrowser/WebBrowserActivity.kt

https://glia.atlassian.net/browse/MOB-3014
Add documentation to all classes that are visible in the manifest

Add documentation to all classes that are visible in manifest

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/MediaProjectionService.java

https://glia.atlassian.net/browse/MOB-3154

Fix app crashes on screen-sharing start on api 34

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/core/screensharing/MediaProjectionService.kt

MOB 3154
https://glia.atlassian.net/browse/MOB-3154

[Backport] Fix app crashes on screen-sharing start on api 34

---

widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java

Authentication instance is not achievable from IsAuthenticatedUseCase

---

widgetssdk/src/main/java/com/glia/widgets/core/dialog/DialogController.kt

This logic was designed for the old solution, with the current improved solution it interferes with the current logic.
MOB 3165
https://glia.atlassian.net/browse/MOB-3165

Fix The confirmation dialog is not displayed on the Call screen start

---

widgetssdk/src/main/java/com/glia/widgets/core/permissions/PermissionManager.kt
widgetssdk/src/test/java/com/glia/widgets/core/permissions/PermissionManagerTest.kt

https://glia.atlassian.net/browse/MOB-3168

Fix Camera permission asked for 1-way video

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/glia/exampleapp/MainFragment.kt

Minor fixes in testing app

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java

https://glia.atlassian.net/browse/MOB-3193

Fix crash after call resumed from bubble

---

app/src/main/java/com/glia/exampleapp/Utils.java
app/src/main/res/xml/sdk_basic_prefs.xml

This change makes writing acceptance tests for authentication during ongoing engagement easier

Change default authentication behavior for testing app (for acceptance tests)

---

widgetssdk/src/main/java/com/glia/widgets/core/notification/NotificationFactory.kt
widgetssdk/src/main/java/com/glia/widgets/core/notification/device/NotificationManager.kt

https://glia.atlassian.net/browse/MOB-3208

Decrease notification priority to the LOW level

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/helper/IntentConfigurationHelper.kt

https://glia.atlassian.net/browse/MOB-3211

Migrate all permission requests in Call screen to an activity result api

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.java
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/helper/IntentConfigurationHelper.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/IsPushNotificationsSetUpUseCase.kt

https://glia.atlassian.net/browse/MOB-3209

Implement mechanisms to check Firebase availability in widgets SDK

---

.github/PULL_REQUEST_TEMPLATE.md

MOB-3229
https://glia.atlassian.net/browse/MOB-3229
Add reminder that will help us to consider keeping logs unified between platforms.

Update PULL_REQUEST_TEMPLATE.md regarding logs unification

---

app/build.gradle
build.gradle
gradle/libs.versions.toml
lint_checker/build.gradle
widgetssdk/build.gradle

https://glia.atlassian.net/browse/MOB-2460
- Migrated dependencies to version catalogs  

Migrated dependencies to version catalogs

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/menu/menu_main_fragment.xml

https://glia.atlassian.net/browse/MOB-3238

Add button in testing app to simulate end screen sharing button click from notifiations

---

widgetssdk/src/main/java/com/glia/widgets/base/BaseActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/operator/OperatorRequestActivityWatcher.kt
widgetssdk/src/test/java/com/glia/widgets/operator/OperatorRequestActivityWatcherTest.kt

https://glia.atlassian.net/browse/MOB-3240
Fixed Configuration changes in call visualizer break screen-sharing dialog

Fix Configuration changes in call visualizer break screen-sharing dialog

---

widgetssdk/src/main/java/com/glia/widgets/engagement/domain/VisitorMediaUseCase.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/completion/EngagementCompletionActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/completion/EngagementCompletionControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/domain/EngagementDomainTest.kt

https://glia.atlassian.net/browse/MOB-3019

Add tests for the engagement domain layer

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.kt

https://glia.atlassian.net/browse/MOB-3294
During every 2-way audio or 2-way video media upgrade there is an error "GliaHub does not support one-way audio calls" because operator and visitor media states were received async with a difference of a few seconds.

Fix media state error in logs

---

app/src/main/res/raw/sample_unified_config.json
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoContainer.kt
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoView.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/UnifiedUiExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/call/CallRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/config/call/VisitorVideoRemoteConfig.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/call/CallTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/call/VisitorVideoTheme.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Call.kt

https://glia.atlassian.net/browse/MOB-3283
Added unified theme for the flip camera button

Added unified theme for the flip camera button

---

widgetssdk/src/main/java/com/glia/widgets/call/CallState.java
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_video2WayWithFlipButton.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_video2WayWithFlipButtonWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_video2WayWithFlipButtonWithUiTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_video2WayWithFlipButtonWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_video2WayWithFlipButtonWithUnifiedThemeWithoutFlipButton.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/call/CallViewVideoSnapshotTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/call/SnapshotCallView.kt
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

https://glia.atlassian.net/browse/MOB-3335
Added snapshot tests for the flip visitor camera button

Flip camera snapshot tests

---

widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/FlipCameraButtonStateUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoContainer.kt

https://glia.atlassian.net/browse/MOB-3339
Some bugs that prevented a visitor video and flip button from showing were fixed.

Fix: Visitor video and flip button are sometimes gone

---

widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewAudioSnapshotTest_audioCallStartedWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewAudioSnapshotTest_initCallWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewAudioSnapshotTest_onHoldWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewAudioSnapshotTest_operatorConnectedWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_initCallWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_onHoldWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_operatorConnectedWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_video1WayCallStartedWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_video2WayCallStartedWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_video2WayWithFlipButtonWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.call_CallViewVideoSnapshotTest_video2WayWithFlipButtonWithUnifiedThemeWithoutFlipButton.png
widgetssdk/src/testSnapshot/res/raw/test_unified_config.json

https://glia.atlassian.net/browse/MOB-3363
Fix snapshot tests Unified UI configuration

Snapshot tests unified UI fix

---

version.properties

Incremented widgets version to 2.6.0

---

app/build.gradle
build.gradle
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
lint_checker/build.gradle
widgetssdk/build.gradle
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/AppendNewOperatorMessageUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/AppendNewResponseCardOrTextItemUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-3371

Align AGP and Kotlin versions between Sdks

---

widgetssdk/src/main/java/com/glia/widgets/GliaWidgets.java
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt
widgetssdk/src/main/java/com/glia/widgets/UiTheme.kt
widgetssdk/src/main/java/com/glia/widgets/core/configuration/GliaSdkConfiguration.kt

https://glia.atlassian.net/browse/MOB-3421

Deprecate UiTheme to make its removal smooth

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetContract.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetView.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetErrorStateViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetItemDecoration.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetMediaTypeItemViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetPoweredByViewHolder.kt
widgetssdk/src/main/res/drawable/bg_circle.xml
widgetssdk/src/main/res/drawable/bg_entry_widget_loading.xml
widgetssdk/src/main/res/drawable/ic_audio.xml
widgetssdk/src/main/res/drawable/ic_chat.xml
widgetssdk/src/main/res/drawable/ic_video.xml
widgetssdk/src/main/res/layout/entry_widget_error_item.xml
widgetssdk/src/main/res/layout/entry_widget_media_type_item.xml
widgetssdk/src/main/res/layout/entry_widget_powered_by_item.xml
widgetssdk/src/main/res/values/dimens.xml
widgetssdk/src/main/res/values/new_strings.xml

https://glia.atlassian.net/browse/MOB-3478
Added Entry Widget (embedded view). By this PR added just UI.
An interface for integrators will be added in the next tasks.
The Unified UI support and UI improvements will be added in the next tasks.

Entry Widget (embedded view)

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/layout/main_fragment.xml
app/src/main/res/values/strings.xml
widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetActivity.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetContract.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetFragment.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetView.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetErrorStateViewHolder.kt
widgetssdk/src/main/res/drawable/bg_bottom_sheet.xml
widgetssdk/src/main/res/drawable/bg_entry_widget_divider.xml
widgetssdk/src/main/res/drawable/ic_drag_handle.xml
widgetssdk/src/main/res/layout/entry_widget_fragment.xml
widgetssdk/src/main/res/values/dimens.xml
widgetssdk/src/main/res/values/themes.xml

https://glia.atlassian.net/browse/MOB-3476
Added Entry Widget (bottom sheet).
An interface for integrators will be added in the next tasks.
https://github.com/user-attachments/assets/79c0887e-e8ae-4529-87f6-fb6b6d77259a

Entry Widget (bottom sheet)

---

widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/EnqueueForEngagementUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/ConfigurationManager.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/domain/EngagementDomainTest.kt

https://glia.atlassian.net/browse/MOB-3672

Devs want to use integrator/default queues from QueueRepository

---

widgetssdk/src/main/res/values/new_strings.xml
widgetssdk/src/main/res/values/strings.xml

https://glia.atlassian.net/browse/MOB-3621
These changes are to make secure conversations align with new UI designs. 
Part of Secure Conversations V2 project.

Update existing secure conversation string

---

widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/WebViewViewHolder.java
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/webbrowser/WebBrowserView.kt

https://glia.atlassian.net/browse/MOB-3701

Fix security flaw related to WebView.

---

widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Chat.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/SecureConversations.kt

https://glia.atlassian.net/browse/MOB-3633

Add global colors support for SCv2

---

widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetMediaTypeItemViewHolder.kt
widgetssdk/src/main/res/values/new_strings.xml

https://glia.atlassian.net/browse/MOB-3696
Add accessibility labels to the Entry Widget

Entry Widget ADA

---

build.gradle
gradle/libs.versions.toml
version.properties
widgetssdk/build.gradle
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetBottomSheetTest_contactsWithUnifiedTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.entrywidget_EntryWidgetEmbeddedViewTest_contactsWithUnifiedTheme.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/SnapshotTest.kt

I have upgraded all dependencies, and regenerated snapshots to align them with a new version of the paparazzi.

Upgrade all dependencies.

---

widgetssdk/src/main/java/com/glia/widgets/chat/Intention.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/EngagementLauncher.kt
widgetssdk/src/test/java/com/glia/widgets/launcher/EngagementLauncherTest.kt

https://glia.atlassian.net/browse/MOB-3759

Add Secure Conversation business logic into EngagementLauncher remaining functions

---

widgetssdk/src/main/java/com/glia/widgets/helper/Insets.kt

https://glia.atlassian.net/browse/MOB-3765

Visitors message input gets hidden behind the keyboard

---

widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/SecureConversationTopBannerVisibilityUseCase.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/SecureConversationTopBannerVisibilityUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-3639

Add use case for SC top banner visibility

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatContract.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapter.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/ChatAdapterDiffCallback.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/OperatorFileAttachmentViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/adapter/holder/fileattachment/VisitorFileAttachmentViewHolder.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/MapChatItemUseCases.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatItems.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt
widgetssdk/src/test/java/com/glia/widgets/chat/ChatManagerTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/MapOperatorAttachmentUseCaseTest.kt
widgetssdk/src/testSnapshot/java/com/glia/widgets/snapshotutils/SnapshotAttachment.kt

https://glia.atlassian.net/browse/MOB-3766

Fix Operator file status does not update after downloading file

---

widgetssdk/src/main/java/com/glia/widgets/helper/IntentHelper.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/ActivityLauncher.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/EngagementLauncher.kt

[MOB-3801](https://glia.atlassian.net/browse/MOB-3801)
[Discussion](https://salemove.slack.com/archives/C07DM3JD8R1/p1731075883777469)
- Replace Activity with Context in EngagementLauncher
[MOB-3801]: https://glia.atlassian.net/browse/MOB-3801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Replace Activity with Context in EngagementLauncher

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt

https://glia.atlassian.net/browse/MOB-3812
This is a corner case and the visitor should have deleted the file they just sent during the live chat. So I decided to add an error message.

Fix Deleted files can be provided but as a black screen

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-3809

Fix Chat screen is opened incorrectly from Call screen

---

widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/HasOngoingSecureConversationUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetContract.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetController.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidgetView.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/test/java/com/glia/widgets/entrywidget/EntryWidgetControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/helper/SupportedMediaTypesTest.kt

https://glia.atlassian.net/browse/MOB-3652

Consider the ongoing sc when checking for secure messaging availability

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-3859

Refactor SC logic to make switching between Live and SC seamless

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatContract.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/adapter/EntryWidgetAdapter.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt

https://glia.atlassian.net/browse/MOB-3859

Devs want to handle SC chat top banner item click

---

widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithTopBannerClosed.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithTopBannerClosedWithGlobalColors.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithTopBannerOpen.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.chat_ChatViewSnapshotTest_secureMessagingWithTopBannerOpenWithGlobalColors.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/chat/ChatViewSnapshotTest.kt

https://glia.atlassian.net/browse/MOB-3639

Add snapshot tests for SC top banner

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogType.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/base/DialogViewFactory.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/option/OptionDialogViewInflater.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/UnifiedUiExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Alert.kt
widgetssdk/src/main/java/com/glia/widgets/view/unifiedui/theme/defaulttheme/Button.kt
widgetssdk/src/main/res/values/new_strings.xml
widgetssdk/src/main/res/values/strings.xml
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OptionDialogTest_negativeNeutralDefaultTheme.png
widgetssdk/src/test/snapshots/images/com.glia.widgets.dialog_OptionDialogTest_negativeNeutralGlobalColors.png
widgetssdk/src/testSnapshot/java/com/glia/widgets/dialog/OptionDialogTest.kt

https://glia.atlassian.net/browse/MOB-3637

Implement Leave Current Conversation dialog

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/data/ChatScreenRepository.kt
widgetssdk/src/main/java/com/glia/widgets/chat/data/ChatScreenRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/SetChatScreenOpenUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/MarkMessagesReadWithDelayUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/ManagerFactory.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/chat/ChatManagerTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/MarkMessagesReadWithDelayUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-3913
Mark Secure Message on received without 6sec delay.

Immediately mark as read

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/SecureConversationTopBannerVisibilityUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/SecureConversationTopBannerVisibilityUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-3939

Remove the ongoing secure conversation check from the SC top banner.

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
build.gradle
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/CallVisualizerActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/CallVisualizerController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/HasOngoingSecureConversationUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/domain/SecureConversationTopBannerVisibilityUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/EngagementTypeUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/entrywidget/EntryWidget.kt
widgetssdk/src/main/java/com/glia/widgets/launcher/EngagementLauncher.kt
widgetssdk/src/main/java/com/glia/widgets/locale/LocaleProvider.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterActivity.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterContract.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterController.kt
widgetssdk/src/main/java/com/glia/widgets/messagecenter/MessageCenterView.kt
widgetssdk/src/main/java/com/glia/widgets/view/snackbar/SnackBarDelegate.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/controller/CallVisualizerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/HasOngoingSecureConversationUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/core/secureconversations/domain/SecureConversationTopBannerVisibilityUseCaseTest.kt
widgetssdk/src/test/java/com/glia/widgets/launcher/EngagementLauncherTest.kt
widgetssdk/src/test/java/com/glia/widgets/messagecenter/MessageCenterControllerTest.kt

https://glia.atlassian.net/browse/MOB-3932

Implement EngagementLauncher business logic for ongoing live engagement

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.kt

https://glia.atlassian.net/browse/MOB-3961

Fix SC bottom banner shows up when transferred sc upgrades to live

---

build.gradle
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/model/ChatState.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt

https://glia.atlassian.net/browse/MOB-3957

Do not end transferred SC

---

widgetssdk/src/main/java/com/glia/widgets/engagement/completion/EngagementCompletionActivityWatcher.kt

https://glia.atlassian.net/browse/MOB-3975
- [] Feature

Add logs with warning about unknown on_end case

---

widgetssdk/src/main/java/com/glia/widgets/view/head/ActivityWatcherForChatHead.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadLayout.kt

https://glia.atlassian.net/browse/MOB-4009

Fix Application chat bubble remains after CV engagement end

---

build.gradle
version.properties
widgetssdk/src/main/java/com/glia/widgets/core/secureconversations/SecureConversationsRepository.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepository.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/EnqueueForEngagementUseCase.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/domain/EngagementDomainTest.kt

… related logic
https://glia.atlassian.net/browse/MOB-4015

Add replaceExisting parameter to queueForEngagement method

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatManager.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/AppendNewChatItemUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/di/ManagerFactory.kt
widgetssdk/src/main/java/com/glia/widgets/helper/TimeCounter.kt
widgetssdk/src/test/java/com/glia/widgets/chat/ChatManagerTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/AppendNewOperatorMessageUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-4042

Fix message count calculation

---

widgetssdk/src/main/res/values/strings.xml

[[Android] Update texts as per comments from tech writer](https://glia.atlassian.net/browse/MOB-4053)
- Updated default texts as per comments from tech writer [here](https://github.com/salemove/mobile-locale/pull/28 MOB-4053).

Update texts as per comments from tech writer

---

widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt

https://glia.atlassian.net/browse/MOB-4061

Fix - Chat box show pre-engagement hint after upgrading SC to Live.

---

widgetssdk/src/main/java/com/glia/widgets/call/CallController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/chat/domain/DecideOnQueueingUseCase.kt
widgetssdk/src/main/res/layout/chat_view.xml
widgetssdk/src/test/java/com/glia/widgets/chat/controller/ChatControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/chat/domain/DecideOnQueueingUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-4072

Fix - All of the subsequent enqueue requests per session are dropped.

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/network_security_config.xml
widgetssdk/src/main/java/com/glia/widgets/engagement/EngagementRepositoryImpl.kt
widgetssdk/src/test/java/com/glia/widgets/engagement/EngagementRepositoryTest.kt

https://glia.atlassian.net/browse/MOB-4075

Fix - Canceled transferred SC ticket triggers end-engagement event

---

widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ApplicationChatHeadLayoutController.kt
widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatHeadController.kt

https://glia.atlassian.net/browse/MOB-4078

Fix - Chat bubble does not update when upgraded from SC to Live

---

bitrise.yml

https://glia.atlassian.net/browse/MOB-4117
- Update Gradle runner plugin to latest version. I have not seen anything in the changelog that should affect us.
- Added titles to some steps to clarify what they are doing

Small Bitrise file maintainance

---

app/src/main/java/com/glia/exampleapp/Application.java

https://glia.atlassian.net/browse/MOB-4198
To unblock development and acceptance tests before the Core SDK's next release.

Fix for the testing app

---

widgetssdk/src/main/java/com/glia/widgets/core/authentication/AuthenticationManager.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/ActivityWatcherForDialog.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/GlobalDialogController.kt
widgetssdk/src/test/java/android/TestExtensions.kt
widgetssdk/src/test/java/com/glia/widgets/view/dialog/ActivityWatcherForDialogTest.kt
widgetssdk/src/test/java/com/glia/widgets/view/dialog/GlobalDialogControllerTest.kt

https://glia.atlassian.net/browse/MOB-4312

Add ActivityWatcher for Permissions Dialog

---

app/src/main/java/com/glia/exampleapp/ExampleAppConfigManager.kt

https://glia.atlassian.net/browse/MOB-4325

Add support for suppressing push notification dialog with deep link

---

app/src/main/java/com/glia/exampleapp/ExampleAppConfigManager.kt
app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/sdk_basic_prefs.xml
widgetssdk/src/main/java/com/glia/widgets/GliaWidgetsConfig.kt
widgetssdk/src/main/java/com/glia/widgets/di/UseCaseFactory.java
widgetssdk/src/main/java/com/glia/widgets/launcher/ConfigurationManager.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/RequestPushNotificationDuringAuthenticationUseCase.kt
widgetssdk/src/test/java/com/glia/widgets/push/notifications/RequestPushNotificationDuringAuthenticationUseCaseTest.kt

https://glia.atlassian.net/browse/MOB-4322
https://github.com/user-attachments/assets/da752896-f45b-47a8-a5e7-b6b250c01d35

Add configuration option to suppress PN permission during auth

---

app/src/main/java/com/glia/exampleapp/VisitorInfoFragment.kt
app/src/main/res/layout/visitor_info_fragment.xml
app/src/main/res/values/strings.xml
widgetssdk/src/main/java/com/glia/widgets/visitor/VisitorInfoUpdateRequest.kt

https://glia.atlassian.net/browse/MOB-4347
Add `externalId` to the `VisitorInfoUpdateRequest` class.

Add externalId to the update visitor info class

---

widgetssdk/src/main/java/com/glia/widgets/view/Dialogs.kt
widgetssdk/src/main/res/values/new_strings.xml

https://glia.atlassian.net/browse/MOB-4351

Update intermediate dialog strings

---

widgetssdk/src/main/AndroidManifest.xml
widgetssdk/src/main/java/com/glia/widgets/base/FadeTransitionActivity.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/PushClickHandlerActivity.kt

https://glia.atlassian.net/browse/MOB-4369

Add PushClickHandlerActivity to handle notification clicks

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.kt
widgetssdk/src/main/java/com/glia/widgets/internal/authentication/AuthenticationManager.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/PushClickHandlerActivity.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/PushClickHandlerController.kt
widgetssdk/src/test/java/com/glia/widgets/push/notifications/PushClickHandlerControllerTest.kt

https://glia.atlassian.net/browse/MOB-4379

Implement push notification click handling

---

widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/PushClickHandlerController.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/UiComponentsActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/UiComponentsDispatcher.kt
widgetssdk/src/test/java/com/glia/widgets/push/notifications/PushClickHandlerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/view/dialog/UiComponentsActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/view/dialog/UiComponentsDispatcherTest.kt

https://glia.atlassian.net/browse/MOB-4386

Fix PN click is not handled properly for upgraded to live engagements.

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/di/ControllerFactory.java
widgetssdk/src/main/java/com/glia/widgets/di/GliaCore.kt
widgetssdk/src/main/java/com/glia/widgets/di/GliaCoreImpl.kt
widgetssdk/src/main/java/com/glia/widgets/fcm/PushNotifications.kt
widgetssdk/src/main/java/com/glia/widgets/helper/IntentHelper.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/PushClickHandlerActivity.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/PushClickHandlerController.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/RequestPushNotificationDuringAuthenticationUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/push/notifications/SecureMessagingPushController.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/UiComponentsActivityWatcher.kt
widgetssdk/src/main/java/com/glia/widgets/view/dialog/UiComponentsDispatcher.kt
widgetssdk/src/test/java/com/glia/widgets/push/notifications/PushClickHandlerControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/push/notifications/SecureMessagingPushControllerTest.kt
widgetssdk/src/test/java/com/glia/widgets/view/dialog/UiComponentsActivityWatcherTest.kt
widgetssdk/src/test/java/com/glia/widgets/view/dialog/UiComponentsDispatcherTest.kt

https://glia.atlassian.net/browse/MOB-4384

Add visitor ID handling to push notification and authentication flow

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
app/src/main/res/layout/main_fragment.xml
app/src/main/res/values/themes.xml

Added checkbox for stopping PN.
https://github.com/user-attachments/assets/e9f1647b-2b7b-45ec-8877-77796c10d172

Add confirmation dialog for stopping push notifications during deauth

---

app/src/main/java/com/glia/exampleapp/MainFragment.kt
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.kt
widgetssdk/src/main/res/layout/survey_activity.xml
widgetssdk/src/main/res/layout/survey_view.xml
widgetssdk/src/main/res/values/dimens.xml

[[Android] Survey Bottom Sheet](https://glia.atlassian.net/browse/MOB-4496)
- Adjusted the layout
- Adjusted the show/hide screen animations
https://github.com/user-attachments/assets/b388b456-fe0f-4d69-b478-c7021791a50f
https://github.com/user-attachments/assets/b25acb06-3ab3-4cab-bd46-70401c6b35d2

Change survey implementation to make it look like a bottom sheet

---

widgetssdk/src/main/java/com/glia/widgets/call/CallActivity.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallContract.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallController.kt
widgetssdk/src/main/java/com/glia/widgets/call/CallView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatContract.kt
widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/ToggleVisitorAudioMediaStateUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/engagement/domain/ToggleVisitorVideoMediaStateUseCase.kt
widgetssdk/src/main/java/com/glia/widgets/helper/CommonExtensions.kt
widgetssdk/src/main/java/com/glia/widgets/internal/dialog/DialogController.kt
widgetssdk/src/main/java/com/glia/widgets/view/floatingvisitorvideoview/FloatingVisitorVideoView.kt
widgetssdk/src/main/java/com/glia/widgets/view/header/AppBarView.kt

https://glia.atlassian.net/browse/MOB-4650
- Added telemetry for Call Screen
- Renamed some methods to match the click action

Add Call Screen telemetry

---

widgetssdk/src/main/java/com/glia/widgets/survey/SurveyActivity.kt
widgetssdk/src/main/java/com/glia/widgets/survey/SurveyView.kt

https://glia.atlassian.net/browse/MOB-4652

Add logging for Survey screen events

---

widgetssdk/src/main/java/com/glia/widgets/callvisualizer/VisitorCodeContract.kt
widgetssdk/src/main/java/com/glia/widgets/callvisualizer/controller/VisitorCodeController.kt
widgetssdk/src/main/java/com/glia/widgets/view/VisitorCodeView.kt
widgetssdk/src/test/java/com/glia/widgets/callvisualizer/controller/VisitorCodeControllerTest.kt

https://glia.atlassian.net/browse/MOB-4743
Add Visitor Code telemetry events

Add Visitor Code telemetry events

---

widgetssdk/src/main/java/com/glia/widgets/InitializationProvider.kt
widgetssdk/src/main/java/com/glia/widgets/helper/DeviceMonitor.kt

Switch telemetry to beta environment

---

widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.kt
widgetssdk/src/main/java/com/glia/widgets/helper/ViewExtensions.kt

https://glia.atlassian.net/browse/MOB-4755

Add telemetry for secure conversation banner visibility changes

---

widgetssdk/src/main/java/com/glia/widgets/InitializationProvider.kt

https://glia.atlassian.net/browse/MOB-4719
This method has been changed in telemetry lib.

Update GliaTelemetry initialisation API
